/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HandlerPostResponse } from "./PostResponse.ts";

export type HandlerDiscoverResponse = {
    /**
     * @type array | undefined
    */
    data?: HandlerPostResponse[];
    /**
     * @type string | undefined
    */
    next_cursor?: string;
};