/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HandlerFeedItemResponse } from "./FeedItemResponse.ts";

export type HandlerFeedResponse = {
    /**
     * @type array | undefined
    */
    data?: HandlerFeedItemResponse[];
    /**
     * @type string | undefined
    */
    next_cursor?: string;
};