/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HandlerAuthorResponse } from "./AuthorResponse.ts";
import type { HandlerMediaResponse } from "./MediaResponse.ts";

export type HandlerPostResponse = {
    /**
     * @type object | undefined
    */
    author?: HandlerAuthorResponse;
    /**
     * @type string | undefined
    */
    author_id?: string;
    /**
     * @type integer | undefined
    */
    comment_count?: number;
    /**
     * @type string | undefined
    */
    content?: string;
    /**
     * @type string | undefined
    */
    created_at?: string;
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type boolean | undefined
    */
    is_liked?: boolean;
    /**
     * @type integer | undefined
    */
    like_count?: number;
    /**
     * @type array | undefined
    */
    media?: HandlerMediaResponse[];
    /**
     * @type string | undefined
    */
    updated_at?: string;
    /**
     * @type string | undefined
    */
    visibility?: string;
};