/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type HandlerUploadResponse = {
    /**
     * @type string | undefined
    */
    key?: string;
    /**
     * @type string | undefined
    */
    media_type?: string;
    /**
     * @type string | undefined
    */
    url?: string;
};