/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PaginationPaginationResponse = {
    /**
     * @description Max items per page
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Number of items to skip
     * @type integer | undefined
    */
    offset?: number;
    /**
     * @description Total number of records
     * @type integer | undefined
    */
    total?: number;
};