/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoAdminStatsResponse = {
    /**
     * @type integer | undefined
    */
    active_users?: number;
    /**
     * @type integer | undefined
    */
    inactive_users?: number;
    /**
     * @type integer | undefined
    */
    total_posts?: number;
    /**
     * @type integer | undefined
    */
    total_roles?: number;
    /**
     * @type integer | undefined
    */
    total_users?: number;
};