/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAdminUserResponse } from "./AdminUserResponse.ts";

export type DtoAdminListUsersResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoAdminUserResponse[];
    /**
     * @description Max items per page
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Number of items to skip
     * @type integer | undefined
    */
    offset?: number;
    /**
     * @description Total number of records
     * @type integer | undefined
    */
    total?: number;
};