/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoAdminBroadcastNotificationResponse = {
    /**
     * @type integer | undefined
    */
    sent_count?: number;
};