/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoChangePasswordRequest = {
    /**
     * @type string | undefined
    */
    new_password?: string;
    /**
     * @type string | undefined
    */
    old_password?: string;
};