/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoCreatePostRequest = {
    /**
     * @type string | undefined
    */
    content?: string;
    /**
     * @type array | undefined
    */
    media_keys?: string[];
    /**
     * @type array | undefined
    */
    mention_user_ids?: string[];
    /**
     * @type array | undefined
    */
    tags?: string[];
    /**
     * @type string | undefined
    */
    visibility?: string;
};