/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoFeedSettingsResponse = {
    /**
     * @type number | undefined
    */
    decay_exponent?: number;
    /**
     * @type boolean | undefined
    */
    fanout_enabled?: boolean;
    /**
     * @type integer | undefined
    */
    fanout_max_followers?: number;
    /**
     * @type number | undefined
    */
    recency_scale?: number;
    /**
     * @type number | undefined
    */
    relationship_bonus?: number;
    /**
     * @type boolean | undefined
    */
    timeline_enabled?: boolean;
    /**
     * @type integer | undefined
    */
    timeline_max_items?: number;
    /**
     * @type boolean | undefined
    */
    timeline_refresh_on_miss?: boolean;
    /**
     * @type integer | undefined
    */
    timeline_rollout_percent?: number;
    /**
     * @type integer | undefined
    */
    timeline_ttl_seconds?: number;
    /**
     * @type string | undefined
    */
    updated_at?: string;
    /**
     * @type string | undefined
    */
    updated_by?: string;
};