/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoFollowResponse } from "./FollowResponse.ts";
import type { PaginationPaginationResponse } from "../pagination/PaginationResponse.ts";

export type DtoFollowListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoFollowResponse[];
    /**
     * @type object | undefined
    */
    pagination?: PaginationPaginationResponse;
};