/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoFollowResponse = {
    /**
     * @type string | undefined
    */
    followed_at?: string;
    /**
     * @type string | undefined
    */
    user_id?: string;
};