/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoHashtagSearchResponse = {
    /**
     * @type string | undefined
    */
    prefix?: string;
    /**
     * @type array | undefined
    */
    results?: string[];
};