/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoRoleResponse } from "./RoleResponse.ts";

export type DtoListRolesResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoRoleResponse[];
};