/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUserResponse } from "./UserResponse.ts";

export type DtoLoginResponse = {
    /**
     * @type integer | undefined
    */
    access_expires_in?: number;
    /**
     * @type string | undefined
    */
    access_token?: string;
    /**
     * @type integer | undefined
    */
    refresh_expires_in?: number;
    /**
     * @type string | undefined
    */
    refresh_token?: string;
    /**
     * @type string | undefined
    */
    token_type?: string;
    /**
     * @type object | undefined
    */
    user?: DtoUserResponse;
};