/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoLoginRequest = {
    /**
     * @type string | undefined
    */
    password?: string;
    /**
     * @type string | undefined
    */
    username?: string;
};