/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoMediaResponse = {
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    media_type?: string;
    /**
     * @type integer | undefined
    */
    position?: number;
    /**
     * @type string | undefined
    */
    url?: string;
};