/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoNotificationResponse } from "./NotificationResponse.ts";

export type DtoNotificationListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoNotificationResponse[];
    /**
     * @type string | undefined
    */
    next_cursor?: string;
};