/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPostResponse } from "./PostResponse.ts";

export type DtoPostListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoPostResponse[];
    /**
     * @type string | undefined
    */
    next_cursor?: string;
};