/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoPostResult = {
    /**
     * @type string | undefined
    */
    author_id?: string;
    /**
     * @type integer | undefined
    */
    comment_count?: number;
    /**
     * @type string | undefined
    */
    content?: string;
    /**
     * @type string | undefined
    */
    created_at?: string;
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type integer | undefined
    */
    like_count?: number;
};