/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoProfileResponse = {
    /**
     * @type string | undefined
    */
    avatar_url?: string;
    /**
     * @type string | undefined
    */
    bio?: string;
    /**
     * @type string | undefined
    */
    cover_url?: string;
    /**
     * @type string | undefined
    */
    display_name?: string;
    /**
     * @type integer | undefined
    */
    follower_count?: number;
    /**
     * @type integer | undefined
    */
    following_count?: number;
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type boolean | undefined
    */
    is_following?: boolean;
    /**
     * @type string | undefined
    */
    joined_at?: string;
    /**
     * @type string | undefined
    */
    location?: string;
    /**
     * @type string | undefined
    */
    username?: string;
    /**
     * @type string | undefined
    */
    website?: string;
};