/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoRegisterRequest = {
    /**
     * @type string | undefined
    */
    display_name?: string;
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    password?: string;
    /**
     * @type string | undefined
    */
    username?: string;
};