/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoResetPasswordRequest = {
    /**
     * @type string | undefined
    */
    new_password?: string;
    /**
     * @type string | undefined
    */
    token?: string;
};