/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoRoleResponse = {
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type string | undefined
    */
    name?: string;
};