/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPostResult } from "./PostResult.ts";
import type { DtoUserResult } from "./UserResult.ts";

export type DtoSearchResponse = {
    /**
     * @type array | undefined
    */
    hashtags?: string[];
    /**
     * @type array | undefined
    */
    posts?: DtoPostResult[];
    /**
     * @type string | undefined
    */
    query?: string;
    /**
     * @type string | undefined
    */
    type?: string;
    /**
     * @type array | undefined
    */
    users?: DtoUserResult[];
};