/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoTrendingHashtagResponse } from "./TrendingHashtagResponse.ts";

export type DtoTrendingHashtagListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoTrendingHashtagResponse[];
};