/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoTrendingHashtagResponse = {
    /**
     * @type integer | undefined
    */
    count?: number;
    /**
     * @type string | undefined
    */
    name?: string;
};