/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoUpdateProfileRequest = {
    /**
     * @type string | undefined
    */
    bio?: string;
    /**
     * @type string | undefined
    */
    display_name?: string;
    /**
     * @type string | undefined
    */
    location?: string;
    /**
     * @type string | undefined
    */
    website?: string;
};