/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoUpdateFeedSettingsRequest = {
    /**
     * @description DecayExponent must be greater than 0. At 0 the recency term is the same\nconstant for every post, which removes recency from the formula rather than\nflattening it — a small exponent is how to ask for a slow decay.
     * @type number | undefined
    */
    decay_exponent?: number;
    /**
     * @description FanoutEnabled is the kill switch for writing prepared timelines. The workers\nstay running and idle, so it is reversible without a restart.
     * @type boolean | undefined
    */
    fanout_enabled?: boolean;
    /**
     * @description FanoutMaxFollowers bounds how many followers one event writes to.
     * @type integer | undefined
    */
    fanout_max_followers?: number;
    /**
     * @type number | undefined
    */
    recency_scale?: number;
    /**
     * @description The local ranking weights:\n\n	score = log(1+likes)*10 + recency_scale/(1+hours)^decay_exponent + relationship_bonus\n\nThe three components are meant to sit on a comparable scale, which is what\nthe 0-1000 bounds protect: a relationship_bonus far above the others stops\nranking the feed and merely sorts followed authors to the top.
     * @type number | undefined
    */
    relationship_bonus?: number;
    /**
     * @description TimelineEnabled gates prepared-timeline serving; TimelineRolloutPercent\n(0-100) decides for what share of users. They are separate so a rollout can\nbe paused without losing the percentage to return to.
     * @type boolean | undefined
    */
    timeline_enabled?: boolean;
    /**
     * @description TimelineMaxItems is entries retained per user timeline, 1-10000. It is a\nper-user memory cost in Redis, not a global one.
     * @type integer | undefined
    */
    timeline_max_items?: number;
    /**
     * @description TimelineRefreshOnMiss lets a miss rebuild that user\'s timeline inline, on the\nrequest goroutine. Turn it off first when a cold cache is making reads slow.
     * @type boolean | undefined
    */
    timeline_refresh_on_miss?: boolean;
    /**
     * @type integer | undefined
    */
    timeline_rollout_percent?: number;
    /**
     * @description TimelineTTLSeconds is how long a prepared timeline survives without a write,\n1 second to 90 days.
     * @type integer | undefined
    */
    timeline_ttl_seconds?: number;
};