/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUserRoleResponse } from "./UserRoleResponse.ts";

export type DtoUserRolesResponse = {
    /**
     * @type array | undefined
    */
    roles?: DtoUserRoleResponse[];
    /**
     * @type string | undefined
    */
    user_id?: string;
};