/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoUserResult = {
    /**
     * @type string | undefined
    */
    avatar_url?: string;
    /**
     * @type string | undefined
    */
    display_name?: string;
    /**
     * @type integer | undefined
    */
    follower_count?: number;
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    username?: string;
};