/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoUserRoleResponse = {
    /**
     * @type string | undefined
    */
    assigned_at?: string;
    /**
     * @type string | undefined
    */
    assigned_by?: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type string | undefined
    */
    role?: string;
};