/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminUpdateFeedSettingsMutationRequest, AdminUpdateFeedSettingsMutationResponse, AdminUpdateFeedSettings400, AdminUpdateFeedSettings401, AdminUpdateFeedSettings403, AdminUpdateFeedSettings500 } from "../models/AdminUpdateFeedSettings.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getAdminUpdateFeedSettingsUrl() {
  const res = { method: 'PATCH', url: `/admin/settings/feed` as const }
  return res
}

/**
 * @description Partial update — an omitted field keeps its stored value, and a body naming no field at all is a 400 rather than an edit that changes nothing. Takes effect on this instance immediately and on any other instance within one refresh interval, without a restart.
 * @summary Update feed runtime settings
 * {@link /admin/settings/feed}
 */
export async function adminUpdateFeedSettings(data: AdminUpdateFeedSettingsMutationRequest, config: Partial<RequestConfig<AdminUpdateFeedSettingsMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<AdminUpdateFeedSettingsMutationResponse, ResponseErrorConfig<AdminUpdateFeedSettings400 | AdminUpdateFeedSettings401 | AdminUpdateFeedSettings403 | AdminUpdateFeedSettings500>, AdminUpdateFeedSettingsMutationRequest>({ method : "PATCH", url : getAdminUpdateFeedSettingsUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}