/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminAssignRoleMutationRequest, AdminAssignRoleMutationResponse, AdminAssignRolePathParams, AdminAssignRole400, AdminAssignRole401, AdminAssignRole403, AdminAssignRole404 } from "../models/AdminAssignRole.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getAdminAssignRoleUrl(id: AdminAssignRolePathParams["id"]) {
  const res = { method: 'POST', url: `/admin/users/${id}/roles` as const }
  return res
}

/**
 * @description Grants a role to the specified user.
 * @summary Assign a role to a user
 * {@link /admin/users/:id/roles}
 */
export async function adminAssignRole(id: AdminAssignRolePathParams["id"], data: AdminAssignRoleMutationRequest, config: Partial<RequestConfig<AdminAssignRoleMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<AdminAssignRoleMutationResponse, ResponseErrorConfig<AdminAssignRole400 | AdminAssignRole401 | AdminAssignRole403 | AdminAssignRole404>, AdminAssignRoleMutationRequest>({ method : "POST", url : getAdminAssignRoleUrl(id).url.toString(), data : requestData, ... requestConfig })
  return res.data
}