/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminBroadcastNotificationMutationRequest, AdminBroadcastNotificationMutationResponse, AdminBroadcastNotification400, AdminBroadcastNotification401, AdminBroadcastNotification403 } from "../models/AdminBroadcastNotification.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getAdminBroadcastNotificationUrl() {
  const res = { method: 'POST', url: `/admin/notifications/broadcast` as const }
  return res
}

/**
 * @description Sends a system announcement notification to all active users.
 * @summary Broadcast notification to all users
 * {@link /admin/notifications/broadcast}
 */
export async function adminBroadcastNotification(data: AdminBroadcastNotificationMutationRequest, config: Partial<RequestConfig<AdminBroadcastNotificationMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<AdminBroadcastNotificationMutationResponse, ResponseErrorConfig<AdminBroadcastNotification400 | AdminBroadcastNotification401 | AdminBroadcastNotification403>, AdminBroadcastNotificationMutationRequest>({ method : "POST", url : getAdminBroadcastNotificationUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}