/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminRemoveRoleMutationResponse, AdminRemoveRolePathParams, AdminRemoveRole400, AdminRemoveRole401, AdminRemoveRole403 } from "../models/AdminRemoveRole.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getAdminRemoveRoleUrl(id: AdminRemoveRolePathParams["id"], role: AdminRemoveRolePathParams["role"]) {
  const res = { method: 'DELETE', url: `/admin/users/${id}/roles/${role}` as const }
  return res
}

/**
 * @description Revokes a role from the specified user.
 * @summary Remove a role from a user
 * {@link /admin/users/:id/roles/:role}
 */
export async function adminRemoveRole(id: AdminRemoveRolePathParams["id"], role: AdminRemoveRolePathParams["role"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminRemoveRoleMutationResponse, ResponseErrorConfig<AdminRemoveRole400 | AdminRemoveRole401 | AdminRemoveRole403>, unknown>({ method : "DELETE", url : getAdminRemoveRoleUrl(id, role).url.toString(), ... requestConfig })
  return res.data
}