/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminSendNotificationToUserMutationRequest, AdminSendNotificationToUserMutationResponse, AdminSendNotificationToUserPathParams, AdminSendNotificationToUser400, AdminSendNotificationToUser401, AdminSendNotificationToUser403, AdminSendNotificationToUser404 } from "../models/AdminSendNotificationToUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getAdminSendNotificationToUserUrl(id: AdminSendNotificationToUserPathParams["id"]) {
  const res = { method: 'POST', url: `/admin/notifications/users/${id}` as const }
  return res
}

/**
 * @description Sends a system announcement notification to a specific user.
 * @summary Send notification to a user
 * {@link /admin/notifications/users/:id}
 */
export async function adminSendNotificationToUser(id: AdminSendNotificationToUserPathParams["id"], data: AdminSendNotificationToUserMutationRequest, config: Partial<RequestConfig<AdminSendNotificationToUserMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<AdminSendNotificationToUserMutationResponse, ResponseErrorConfig<AdminSendNotificationToUser400 | AdminSendNotificationToUser401 | AdminSendNotificationToUser403 | AdminSendNotificationToUser404>, AdminSendNotificationToUserMutationRequest>({ method : "POST", url : getAdminSendNotificationToUserUrl(id).url.toString(), data : requestData, ... requestConfig })
  return res.data
}