/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminListRolesQueryResponse, AdminListRoles401, AdminListRoles403 } from "../models/AdminListRoles.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getAdminListRolesUrl() {
  const res = { method: 'GET', url: `/admin/roles` as const }
  return res
}

/**
 * @description Returns the fixed set of roles that can be assigned to users. Roles are defined by the application, not created at runtime.
 * @summary List assignable roles
 * {@link /admin/roles}
 */
export async function adminListRoles(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminListRolesQueryResponse, ResponseErrorConfig<AdminListRoles401 | AdminListRoles403>, unknown>({ method : "GET", url : getAdminListRolesUrl().url.toString(), ... requestConfig })
  return res.data
}