/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminSetUserStatusMutationRequest, AdminSetUserStatusMutationResponse, AdminSetUserStatusPathParams, AdminSetUserStatus400, AdminSetUserStatus401, AdminSetUserStatus403, AdminSetUserStatus404 } from "../models/AdminSetUserStatus.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getAdminSetUserStatusUrl(id: AdminSetUserStatusPathParams["id"]) {
  const res = { method: 'PATCH', url: `/admin/users/${id}/status` as const }
  return res
}

/**
 * @description Sets the active status of a user account. Deactivated users cannot log in.
 * @summary Activate or deactivate a user
 * {@link /admin/users/:id/status}
 */
export async function adminSetUserStatus(id: AdminSetUserStatusPathParams["id"], data: AdminSetUserStatusMutationRequest, config: Partial<RequestConfig<AdminSetUserStatusMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<AdminSetUserStatusMutationResponse, ResponseErrorConfig<AdminSetUserStatus400 | AdminSetUserStatus401 | AdminSetUserStatus403 | AdminSetUserStatus404>, AdminSetUserStatusMutationRequest>({ method : "PATCH", url : getAdminSetUserStatusUrl(id).url.toString(), data : requestData, ... requestConfig })
  return res.data
}