/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminGetUserQueryResponse, AdminGetUserPathParams, AdminGetUser400, AdminGetUser401, AdminGetUser403, AdminGetUser404 } from "../models/AdminGetUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getAdminGetUserUrl(id: AdminGetUserPathParams["id"]) {
  const res = { method: 'GET', url: `/admin/users/${id}` as const }
  return res
}

/**
 * @description Returns the admin view of a single user including email and active status.
 * @summary Get user details
 * {@link /admin/users/:id}
 */
export async function adminGetUser(id: AdminGetUserPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminGetUserQueryResponse, ResponseErrorConfig<AdminGetUser400 | AdminGetUser401 | AdminGetUser403 | AdminGetUser404>, unknown>({ method : "GET", url : getAdminGetUserUrl(id).url.toString(), ... requestConfig })
  return res.data
}