/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminGetUserRolesQueryResponse, AdminGetUserRolesPathParams, AdminGetUserRoles400, AdminGetUserRoles401, AdminGetUserRoles403, AdminGetUserRoles404 } from "../models/AdminGetUserRoles.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getAdminGetUserRolesUrl(id: AdminGetUserRolesPathParams["id"]) {
  const res = { method: 'GET', url: `/admin/users/${id}/roles` as const }
  return res
}

/**
 * @description Returns all roles currently assigned to the specified user.
 * @summary Get roles for a user
 * {@link /admin/users/:id/roles}
 */
export async function adminGetUserRoles(id: AdminGetUserRolesPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminGetUserRolesQueryResponse, ResponseErrorConfig<AdminGetUserRoles400 | AdminGetUserRoles401 | AdminGetUserRoles403 | AdminGetUserRoles404>, unknown>({ method : "GET", url : getAdminGetUserRolesUrl(id).url.toString(), ... requestConfig })
  return res.data
}