/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminGetStatsQueryResponse, AdminGetStats401, AdminGetStats403, AdminGetStats500 } from "../models/AdminGetStats.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getAdminGetStatsUrl() {
  const res = { method: 'GET', url: `/admin/stats` as const }
  return res
}

/**
 * @description Returns basic counts for users and roles.
 * @summary Get platform statistics
 * {@link /admin/stats}
 */
export async function adminGetStats(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminGetStatsQueryResponse, ResponseErrorConfig<AdminGetStats401 | AdminGetStats403 | AdminGetStats500>, unknown>({ method : "GET", url : getAdminGetStatsUrl().url.toString(), ... requestConfig })
  return res.data
}