/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminListUsersQueryResponse, AdminListUsersQueryParams, AdminListUsers401, AdminListUsers403, AdminListUsers500 } from "../models/AdminListUsers.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getAdminListUsersUrl() {
  const res = { method: 'GET', url: `/admin/users` as const }
  return res
}

/**
 * @description Returns a paginated list of all users. Supports filtering by status and search query.
 * @summary List all users
 * {@link /admin/users}
 */
export async function adminListUsers(params?: AdminListUsersQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminListUsersQueryResponse, ResponseErrorConfig<AdminListUsers401 | AdminListUsers403 | AdminListUsers500>, unknown>({ method : "GET", url : getAdminListUsersUrl().url.toString(), params, ... requestConfig })
  return res.data
}