/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminGetFeedSettingsQueryResponse, AdminGetFeedSettings401, AdminGetFeedSettings403, AdminGetFeedSettings500 } from "../models/AdminGetFeedSettings.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getAdminGetFeedSettingsUrl() {
  const res = { method: 'GET', url: `/admin/settings/feed` as const }
  return res
}

/**
 * @description Returns the feed knobs that can be changed while the API is running: prepared-timeline serving and its rollout, fanout, and the three local ranking weights. Fanout worker count and queue size are not here — they size a goroutine pool at construction and still require a restart, so they stay in the environment.
 * @summary Get feed runtime settings
 * {@link /admin/settings/feed}
 */
export async function adminGetFeedSettings(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminGetFeedSettingsQueryResponse, ResponseErrorConfig<AdminGetFeedSettings401 | AdminGetFeedSettings403 | AdminGetFeedSettings500>, unknown>({ method : "GET", url : getAdminGetFeedSettingsUrl().url.toString(), ... requestConfig })
  return res.data
}