/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ChangePasswordMutationRequest, ChangePasswordMutationResponse, ChangePassword400, ChangePassword401, ChangePassword500 } from "../models/ChangePassword.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getChangePasswordUrl() {
  const res = { method: 'PUT', url: `/auth/password` as const }
  return res
}

/**
 * @description Change the authenticated user's password (requires old password)
 * @summary Change password
 * {@link /auth/password}
 */
export async function changePassword(data: ChangePasswordMutationRequest, config: Partial<RequestConfig<ChangePasswordMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<ChangePasswordMutationResponse, ResponseErrorConfig<ChangePassword400 | ChangePassword401 | ChangePassword500>, ChangePasswordMutationRequest>({ method : "PUT", url : getChangePasswordUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}