/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { CreatePostMutationRequest, CreatePostMutationResponse, CreatePost400, CreatePost401, CreatePost500 } from "../models/CreatePost.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getCreatePostUrl() {
  const res = { method: 'POST', url: `/posts` as const }
  return res
}

/**
 * @description Create a new post with optional media attachments
 * @summary Create a post
 * {@link /posts}
 */
export async function createPost(data: CreatePostMutationRequest, config: Partial<RequestConfig<CreatePostMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<CreatePostMutationResponse, ResponseErrorConfig<CreatePost400 | CreatePost401 | CreatePost500>, CreatePostMutationRequest>({ method : "POST", url : getCreatePostUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}