/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { CreateCommentMutationRequest, CreateCommentMutationResponse, CreateCommentPathParams, CreateComment400, CreateComment401, CreateComment404, CreateComment500 } from "../models/CreateComment.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getCreateCommentUrl(postID: CreateCommentPathParams["postID"]) {
  const res = { method: 'POST', url: `/posts/${postID}/comments` as const }
  return res
}

/**
 * @description Add a comment (or reply) to a post
 * @summary Create a comment
 * {@link /posts/:postID/comments}
 */
export async function createComment(postID: CreateCommentPathParams["postID"], data: CreateCommentMutationRequest, config: Partial<RequestConfig<CreateCommentMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<CreateCommentMutationResponse, ResponseErrorConfig<CreateComment400 | CreateComment401 | CreateComment404 | CreateComment500>, CreateCommentMutationRequest>({ method : "POST", url : getCreateCommentUrl(postID).url.toString(), data : requestData, ... requestConfig })
  return res.data
}