/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { DeactivateUserMutationResponse, DeactivateUserPathParams, DeactivateUserQueryParams, DeactivateUser400, DeactivateUser404, DeactivateUser500 } from "../models/DeactivateUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getDeactivateUserUrl(userKey: DeactivateUserPathParams["userKey"]) {
  const res = { method: 'DELETE', url: `/users/${userKey}` as const }
  return res
}

/**
 * @description Soft delete a user account (sets is_active to false) by UUID or username (with ?by=username)
 * @summary Deactivate user
 * {@link /users/:userKey}
 */
export async function deactivateUser(userKey: DeactivateUserPathParams["userKey"], params?: DeactivateUserQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeactivateUserMutationResponse, ResponseErrorConfig<DeactivateUser400 | DeactivateUser404 | DeactivateUser500>, unknown>({ method : "DELETE", url : getDeactivateUserUrl(userKey).url.toString(), params, ... requestConfig })
  return res.data
}