/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { DeleteCommentMutationResponse, DeleteCommentPathParams, DeleteComment400, DeleteComment401, DeleteComment403, DeleteComment404, DeleteComment500 } from "../models/DeleteComment.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getDeleteCommentUrl(postID: DeleteCommentPathParams["postID"], commentID: DeleteCommentPathParams["commentID"]) {
  const res = { method: 'DELETE', url: `/posts/${postID}/comments/${commentID}` as const }
  return res
}

/**
 * @description Soft-delete an owned comment
 * @summary Delete a comment
 * {@link /posts/:postID/comments/:commentID}
 */
export async function deleteComment(postID: DeleteCommentPathParams["postID"], commentID: DeleteCommentPathParams["commentID"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteCommentMutationResponse, ResponseErrorConfig<DeleteComment400 | DeleteComment401 | DeleteComment403 | DeleteComment404 | DeleteComment500>, unknown>({ method : "DELETE", url : getDeleteCommentUrl(postID, commentID).url.toString(), ... requestConfig })
  return res.data
}