/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { DeletePostMutationResponse, DeletePostPathParams, DeletePost400, DeletePost401, DeletePost403, DeletePost404, DeletePost500 } from "../models/DeletePost.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getDeletePostUrl(postID: DeletePostPathParams["postID"]) {
  const res = { method: 'DELETE', url: `/posts/${postID}` as const }
  return res
}

/**
 * @description Soft-delete an owned post
 * @summary Delete a post
 * {@link /posts/:postID}
 */
export async function deletePost(postID: DeletePostPathParams["postID"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeletePostMutationResponse, ResponseErrorConfig<DeletePost400 | DeletePost401 | DeletePost403 | DeletePost404 | DeletePost500>, unknown>({ method : "DELETE", url : getDeletePostUrl(postID).url.toString(), ... requestConfig })
  return res.data
}