/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { FollowUserMutationResponse, FollowUserPathParams, FollowUserQueryParams, FollowUser400, FollowUser401, FollowUser500 } from "../models/FollowUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getFollowUserUrl(userKey: FollowUserPathParams["userKey"]) {
  const res = { method: 'POST', url: `/users/${userKey}/follow` as const }
  return res
}

/**
 * @description Follow a user by UUID or username (with ?by=username). No-op if already following.
 * @summary Follow a user
 * {@link /users/:userKey/follow}
 */
export async function followUser(userKey: FollowUserPathParams["userKey"], params?: FollowUserQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<FollowUserMutationResponse, ResponseErrorConfig<FollowUser400 | FollowUser401 | FollowUser500>, unknown>({ method : "POST", url : getFollowUserUrl(userKey).url.toString(), params, ... requestConfig })
  return res.data
}