/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ForgotPasswordMutationRequest, ForgotPasswordMutationResponse, ForgotPassword400, ForgotPassword500 } from "../models/ForgotPassword.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getForgotPasswordUrl() {
  const res = { method: 'POST', url: `/auth/forgot-password` as const }
  return res
}

/**
 * @description Send a password reset link to the specified email address
 * @summary Request password reset
 * {@link /auth/forgot-password}
 */
export async function forgotPassword(data: ForgotPasswordMutationRequest, config: Partial<RequestConfig<ForgotPasswordMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<ForgotPasswordMutationResponse, ResponseErrorConfig<ForgotPassword400 | ForgotPassword500>, ForgotPasswordMutationRequest>({ method : "POST", url : getForgotPasswordUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}