/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetCommentsQueryResponse, GetCommentsPathParams, GetCommentsQueryParams, GetComments400, GetComments404, GetComments500 } from "../models/GetComments.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetCommentsUrl(postID: GetCommentsPathParams["postID"]) {
  const res = { method: 'GET', url: `/posts/${postID}/comments` as const }
  return res
}

/**
 * @description Get a paginated list of top-level comments for a post
 * @summary Get comments
 * {@link /posts/:postID/comments}
 */
export async function getComments(postID: GetCommentsPathParams["postID"], params?: GetCommentsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetCommentsQueryResponse, ResponseErrorConfig<GetComments400 | GetComments404 | GetComments500>, unknown>({ method : "GET", url : getGetCommentsUrl(postID).url.toString(), params, ... requestConfig })
  return res.data
}