/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetDiscoverQueryResponse, GetDiscoverQueryParams, GetDiscover400, GetDiscover500 } from "../models/GetDiscover.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetDiscoverUrl() {
  const res = { method: 'GET', url: `/discover` as const }
  return res
}

/**
 * @description Get a cursor-paginated discovery feed of public posts. No authentication required; if a valid token is provided, is_liked is populated.
 * @summary Discover posts
 * {@link /discover}
 */
export async function getDiscover(params?: GetDiscoverQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetDiscoverQueryResponse, ResponseErrorConfig<GetDiscover400 | GetDiscover500>, unknown>({ method : "GET", url : getGetDiscoverUrl().url.toString(), params, ... requestConfig })
  return res.data
}