/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetFollowersQueryResponse, GetFollowersPathParams, GetFollowersQueryParams, GetFollowers400, GetFollowers500 } from "../models/GetFollowers.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetFollowersUrl(userKey: GetFollowersPathParams["userKey"]) {
  const res = { method: 'GET', url: `/users/${userKey}/followers` as const }
  return res
}

/**
 * @description Get a paginated list of users who follow the specified user by UUID or username (with ?by=username)
 * @summary Get followers
 * {@link /users/:userKey/followers}
 */
export async function getFollowers(userKey: GetFollowersPathParams["userKey"], params?: GetFollowersQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetFollowersQueryResponse, ResponseErrorConfig<GetFollowers400 | GetFollowers500>, unknown>({ method : "GET", url : getGetFollowersUrl(userKey).url.toString(), params, ... requestConfig })
  return res.data
}