/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetFollowingQueryResponse, GetFollowingPathParams, GetFollowingQueryParams, GetFollowing400, GetFollowing500 } from "../models/GetFollowing.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetFollowingUrl(userKey: GetFollowingPathParams["userKey"]) {
  const res = { method: 'GET', url: `/users/${userKey}/following` as const }
  return res
}

/**
 * @description Get a paginated list of users that the specified user follows by UUID or username (with ?by=username)
 * @summary Get following
 * {@link /users/:userKey/following}
 */
export async function getFollowing(userKey: GetFollowingPathParams["userKey"], params?: GetFollowingQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetFollowingQueryResponse, ResponseErrorConfig<GetFollowing400 | GetFollowing500>, unknown>({ method : "GET", url : getGetFollowingUrl(userKey).url.toString(), params, ... requestConfig })
  return res.data
}