/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetFeedQueryResponse, GetFeedQueryParams, GetFeed400, GetFeed401, GetFeed500 } from "../models/GetFeed.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetFeedUrl() {
  const res = { method: 'GET', url: `/feed` as const }
  return res
}

/**
 * @description Get a scored, paginated feed of posts mixed from followed users and trending posts
 * @summary Get feed
 * {@link /feed}
 */
export async function getFeed(params?: GetFeedQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetFeedQueryResponse, ResponseErrorConfig<GetFeed400 | GetFeed401 | GetFeed500>, unknown>({ method : "GET", url : getGetFeedUrl().url.toString(), params, ... requestConfig })
  return res.data
}