/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetMyProfileQueryResponse, GetMyProfile401, GetMyProfile404, GetMyProfile500 } from "../models/GetMyProfile.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetMyProfileUrl() {
  const res = { method: 'GET', url: `/me` as const }
  return res
}

/**
 * @description Get the authenticated user's social profile
 * @summary Get my profile
 * {@link /me}
 */
export async function getMyProfile(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetMyProfileQueryResponse, ResponseErrorConfig<GetMyProfile401 | GetMyProfile404 | GetMyProfile500>, unknown>({ method : "GET", url : getGetMyProfileUrl().url.toString(), ... requestConfig })
  return res.data
}