/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetMeQueryResponse, GetMe401, GetMe404, GetMe500 } from "../models/GetMe.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetMeUrl() {
  const res = { method: 'GET', url: `/auth/me` as const }
  return res
}

/**
 * @description Get the authenticated user's information
 * @summary Get current user
 * {@link /auth/me}
 */
export async function getMe(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetMeQueryResponse, ResponseErrorConfig<GetMe401 | GetMe404 | GetMe500>, unknown>({ method : "GET", url : getGetMeUrl().url.toString(), ... requestConfig })
  return res.data
}