/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetNotificationsQueryResponse, GetNotificationsQueryParams, GetNotifications400, GetNotifications401, GetNotifications500 } from "../models/GetNotifications.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetNotificationsUrl() {
  const res = { method: 'GET', url: `/notifications` as const }
  return res
}

/**
 * @description Get a cursor-paginated list of notifications for the authenticated user
 * @summary Get notifications
 * {@link /notifications}
 */
export async function getNotifications(params?: GetNotificationsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetNotificationsQueryResponse, ResponseErrorConfig<GetNotifications400 | GetNotifications401 | GetNotifications500>, unknown>({ method : "GET", url : getGetNotificationsUrl().url.toString(), params, ... requestConfig })
  return res.data
}