/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetPostsByHashtagQueryResponse, GetPostsByHashtagPathParams, GetPostsByHashtagQueryParams, GetPostsByHashtag400, GetPostsByHashtag500 } from "../models/GetPostsByHashtag.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetPostsByHashtagUrl(name: GetPostsByHashtagPathParams["name"]) {
  const res = { method: 'GET', url: `/hashtags/${name}/posts` as const }
  return res
}

/**
 * @description Returns cursor-paginated public posts for a hashtag
 * @summary Posts by hashtag
 * {@link /hashtags/:name/posts}
 */
export async function getPostsByHashtag(name: GetPostsByHashtagPathParams["name"], params?: GetPostsByHashtagQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetPostsByHashtagQueryResponse, ResponseErrorConfig<GetPostsByHashtag400 | GetPostsByHashtag500>, unknown>({ method : "GET", url : getGetPostsByHashtagUrl(name).url.toString(), params, ... requestConfig })
  return res.data
}