/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetPostQueryResponse, GetPostPathParams, GetPost400, GetPost404, GetPost500 } from "../models/GetPost.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetPostUrl(postID: GetPostPathParams["postID"]) {
  const res = { method: 'GET', url: `/posts/${postID}` as const }
  return res
}

/**
 * @description Get a post by ID
 * @summary Get a post
 * {@link /posts/:postID}
 */
export async function getPost(postID: GetPostPathParams["postID"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetPostQueryResponse, ResponseErrorConfig<GetPost400 | GetPost404 | GetPost500>, unknown>({ method : "GET", url : getGetPostUrl(postID).url.toString(), ... requestConfig })
  return res.data
}