/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetRepliesQueryResponse, GetRepliesPathParams, GetRepliesQueryParams, GetReplies400, GetReplies404, GetReplies500 } from "../models/GetReplies.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetRepliesUrl(postID: GetRepliesPathParams["postID"], commentID: GetRepliesPathParams["commentID"]) {
  const res = { method: 'GET', url: `/posts/${postID}/comments/${commentID}/replies` as const }
  return res
}

/**
 * @description Get a paginated list of replies for a comment
 * @summary Get replies
 * {@link /posts/:postID/comments/:commentID/replies}
 */
export async function getReplies(postID: GetRepliesPathParams["postID"], commentID: GetRepliesPathParams["commentID"], params?: GetRepliesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetRepliesQueryResponse, ResponseErrorConfig<GetReplies400 | GetReplies404 | GetReplies500>, unknown>({ method : "GET", url : getGetRepliesUrl(postID, commentID).url.toString(), params, ... requestConfig })
  return res.data
}