/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetTrendingHashtagsQueryResponse, GetTrendingHashtags500 } from "../models/GetTrendingHashtags.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetTrendingHashtagsUrl() {
  const res = { method: 'GET', url: `/hashtags/trending` as const }
  return res
}

/**
 * @description Returns the top trending hashtags based on post usage in the last 24 hours
 * @summary Trending hashtags
 * {@link /hashtags/trending}
 */
export async function getTrendingHashtags(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetTrendingHashtagsQueryResponse, ResponseErrorConfig<GetTrendingHashtags500>, unknown>({ method : "GET", url : getGetTrendingHashtagsUrl().url.toString(), ... requestConfig })
  return res.data
}