/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetUserProfileQueryResponse, GetUserProfilePathParams, GetUserProfileQueryParams, GetUserProfile400, GetUserProfile404, GetUserProfile500 } from "../models/GetUserProfile.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetUserProfileUrl(userKey: GetUserProfilePathParams["userKey"]) {
  const res = { method: 'GET', url: `/users/${userKey}/profile` as const }
  return res
}

/**
 * @description Get a user's public social profile by UUID or username (with ?by=username). Optionally enriches is_following when the viewer is authenticated.
 * @summary Get user profile
 * {@link /users/:userKey/profile}
 */
export async function getUserProfile(userKey: GetUserProfilePathParams["userKey"], params?: GetUserProfileQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetUserProfileQueryResponse, ResponseErrorConfig<GetUserProfile400 | GetUserProfile404 | GetUserProfile500>, unknown>({ method : "GET", url : getGetUserProfileUrl(userKey).url.toString(), params, ... requestConfig })
  return res.data
}