/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetUnreadCountQueryResponse, GetUnreadCount401, GetUnreadCount500 } from "../models/GetUnreadCount.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetUnreadCountUrl() {
  const res = { method: 'GET', url: `/notifications/unread-count` as const }
  return res
}

/**
 * @description Get the number of unread notifications for the authenticated user
 * @summary Get unread notification count
 * {@link /notifications/unread-count}
 */
export async function getUnreadCount(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetUnreadCountQueryResponse, ResponseErrorConfig<GetUnreadCount401 | GetUnreadCount500>, unknown>({ method : "GET", url : getGetUnreadCountUrl().url.toString(), ... requestConfig })
  return res.data
}