/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetUserPostsQueryResponse, GetUserPostsPathParams, GetUserPostsQueryParams, GetUserPosts400, GetUserPosts500 } from "../models/GetUserPosts.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetUserPostsUrl(userID: GetUserPostsPathParams["userID"]) {
  const res = { method: 'GET', url: `/users/${userID}/posts` as const }
  return res
}

/**
 * @description Get a cursor-paginated list of posts by a specific user
 * @summary Get user posts
 * {@link /users/:userID/posts}
 */
export async function getUserPosts(userID: GetUserPostsPathParams["userID"], params?: GetUserPostsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetUserPostsQueryResponse, ResponseErrorConfig<GetUserPosts400 | GetUserPosts500>, unknown>({ method : "GET", url : getGetUserPostsUrl(userID).url.toString(), params, ... requestConfig })
  return res.data
}