/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetUserQueryResponse, GetUserPathParams, GetUserQueryParams, GetUser400, GetUser404, GetUser500 } from "../models/GetUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetUserUrl(userKey: GetUserPathParams["userKey"]) {
  const res = { method: 'GET', url: `/users/${userKey}` as const }
  return res
}

/**
 * @description Retrieve a user's information by UUID or username (with ?by=username)
 * @summary Get user by ID or username
 * {@link /users/:userKey}
 */
export async function getUser(userKey: GetUserPathParams["userKey"], params?: GetUserQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetUserQueryResponse, ResponseErrorConfig<GetUser400 | GetUser404 | GetUser500>, unknown>({ method : "GET", url : getGetUserUrl(userKey).url.toString(), params, ... requestConfig })
  return res.data
}