/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { LoginMutationRequest, LoginMutationResponse, LoginHeaderParams, Login400, Login401, Login403, Login500 } from "../models/Login.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getLoginUrl() {
  const res = { method: 'POST', url: `/auth/login` as const }
  return res
}

/**
 * @description Authenticate user with username and password, returns access and refresh tokens.
 * Web clients (default): refresh_token is set as an HttpOnly cookie; omitted from response body.
 * Mobile clients (X-Client-Type: mobile): refresh_token is returned in the response body.
 * @summary User login
 * {@link /auth/login}
 */
export async function login(data: LoginMutationRequest, headers?: LoginHeaderParams, config: Partial<RequestConfig<LoginMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<LoginMutationResponse, ResponseErrorConfig<Login400 | Login401 | Login403 | Login500>, LoginMutationRequest>({ method : "POST", url : getLoginUrl().url.toString(), data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })
  return res.data
}