/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { LogoutMutationRequest, LogoutMutationResponse, LogoutHeaderParams, Logout400, Logout401, Logout500 } from "../models/Logout.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getLogoutUrl() {
  const res = { method: 'POST', url: `/auth/logout` as const }
  return res
}

/**
 * @description Revoke a refresh token to logout user from current session.
 * Web clients (default): refresh_token is read from the HttpOnly cookie automatically; request body is not required. Cookie is cleared on success.
 * Mobile clients (X-Client-Type: mobile): refresh_token must be provided in the request body.
 * @summary User logout
 * {@link /auth/logout}
 */
export async function logout(data?: LogoutMutationRequest, headers?: LogoutHeaderParams, config: Partial<RequestConfig<LogoutMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<LogoutMutationResponse, ResponseErrorConfig<Logout400 | Logout401 | Logout500>, LogoutMutationRequest>({ method : "POST", url : getLogoutUrl().url.toString(), data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })
  return res.data
}