/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { LogoutAllSessionsMutationResponse, LogoutAllSessions401, LogoutAllSessions500 } from "../models/LogoutAllSessions.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getLogoutAllSessionsUrl() {
  const res = { method: 'POST', url: `/auth/logout-all` as const }
  return res
}

/**
 * @description Revoke all refresh tokens for the authenticated user
 * @summary Logout all sessions
 * {@link /auth/logout-all}
 */
export async function logoutAllSessions(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<LogoutAllSessionsMutationResponse, ResponseErrorConfig<LogoutAllSessions401 | LogoutAllSessions500>, unknown>({ method : "POST", url : getLogoutAllSessionsUrl().url.toString(), ... requestConfig })
  return res.data
}