/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { MarkAllNotificationsAsReadMutationResponse, MarkAllNotificationsAsRead401, MarkAllNotificationsAsRead500 } from "../models/MarkAllNotificationsAsRead.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getMarkAllNotificationsAsReadUrl() {
  const res = { method: 'POST', url: `/notifications/read-all` as const }
  return res
}

/**
 * @description Mark all notifications as read for the authenticated user
 * @summary Mark all notifications as read
 * {@link /notifications/read-all}
 */
export async function markAllNotificationsAsRead(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarkAllNotificationsAsReadMutationResponse, ResponseErrorConfig<MarkAllNotificationsAsRead401 | MarkAllNotificationsAsRead500>, unknown>({ method : "POST", url : getMarkAllNotificationsAsReadUrl().url.toString(), ... requestConfig })
  return res.data
}