/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { MarkNotificationAsReadMutationResponse, MarkNotificationAsReadPathParams, MarkNotificationAsRead400, MarkNotificationAsRead401, MarkNotificationAsRead500 } from "../models/MarkNotificationAsRead.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getMarkNotificationAsReadUrl(notificationID: MarkNotificationAsReadPathParams["notificationID"]) {
  const res = { method: 'POST', url: `/notifications/${notificationID}/read` as const }
  return res
}

/**
 * @description Mark a single notification as read
 * @summary Mark notification as read
 * {@link /notifications/:notificationID/read}
 */
export async function markNotificationAsRead(notificationID: MarkNotificationAsReadPathParams["notificationID"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarkNotificationAsReadMutationResponse, ResponseErrorConfig<MarkNotificationAsRead400 | MarkNotificationAsRead401 | MarkNotificationAsRead500>, unknown>({ method : "POST", url : getMarkNotificationAsReadUrl(notificationID).url.toString(), ... requestConfig })
  return res.data
}