/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RefreshTokenMutationRequest, RefreshTokenMutationResponse, RefreshTokenHeaderParams, RefreshToken400, RefreshToken401, RefreshToken500 } from "../models/RefreshToken.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getRefreshTokenUrl() {
  const res = { method: 'POST', url: `/auth/refresh` as const }
  return res
}

/**
 * @description Exchange a valid refresh token for a new access token and refresh token.
 * Web clients (default): refresh_token is read from the HttpOnly cookie automatically; request body is not required.
 * Mobile clients (X-Client-Type: mobile): refresh_token must be provided in the request body.
 * @summary Refresh access token
 * {@link /auth/refresh}
 */
export async function refreshToken(data?: RefreshTokenMutationRequest, headers?: RefreshTokenHeaderParams, config: Partial<RequestConfig<RefreshTokenMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<RefreshTokenMutationResponse, ResponseErrorConfig<RefreshToken400 | RefreshToken401 | RefreshToken500>, RefreshTokenMutationRequest>({ method : "POST", url : getRefreshTokenUrl().url.toString(), data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })
  return res.data
}