/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RegisterMutationRequest, RegisterMutationResponse, RegisterHeaderParams, Register400, Register409, Register500 } from "../models/Register.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getRegisterUrl() {
  const res = { method: 'POST', url: `/auth/register` as const }
  return res
}

/**
 * @description Create a new user account and return tokens (user is immediately logged in).
 * Web clients (default): refresh_token is set as an HttpOnly cookie; omitted from response body.
 * Mobile clients (X-Client-Type: mobile): refresh_token is returned in the response body.
 * @summary Register a new account
 * {@link /auth/register}
 */
export async function register(data: RegisterMutationRequest, headers?: RegisterHeaderParams, config: Partial<RequestConfig<RegisterMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<RegisterMutationResponse, ResponseErrorConfig<Register400 | Register409 | Register500>, RegisterMutationRequest>({ method : "POST", url : getRegisterUrl().url.toString(), data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })
  return res.data
}