/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ResendWebhookMutationResponse, ResendWebhook400, ResendWebhook401, ResendWebhook500 } from "../models/ResendWebhook.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getResendWebhookUrl() {
  const res = { method: 'POST', url: `/webhooks/resend` as const }
  return res
}

/**
 * @description Receives Resend delivery events (delivered, bounced, complained) and updates the email delivery log. Authenticated by the Svix signature headers, not by a bearer token. Only registered when RESEND_WEBHOOK_SECRET is configured.
 * @summary Resend delivery webhook
 * {@link /webhooks/resend}
 */
export async function resendWebhook(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ResendWebhookMutationResponse, ResponseErrorConfig<ResendWebhook400 | ResendWebhook401 | ResendWebhook500>, unknown>({ method : "POST", url : getResendWebhookUrl().url.toString(), ... requestConfig })
  return res.data
}