/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ResendVerificationMutationRequest, ResendVerificationMutationResponse, ResendVerification400, ResendVerification500 } from "../models/ResendVerification.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getResendVerificationUrl() {
  const res = { method: 'POST', url: `/auth/resend-verification` as const }
  return res
}

/**
 * @description Resend the email verification link to the specified email address
 * @summary Resend verification email
 * {@link /auth/resend-verification}
 */
export async function resendVerification(data: ResendVerificationMutationRequest, config: Partial<RequestConfig<ResendVerificationMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<ResendVerificationMutationResponse, ResponseErrorConfig<ResendVerification400 | ResendVerification500>, ResendVerificationMutationRequest>({ method : "POST", url : getResendVerificationUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}