/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SearchHashtagsQueryResponse, SearchHashtagsQueryParams, SearchHashtags400, SearchHashtags429, SearchHashtags500 } from "../models/SearchHashtags.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getSearchHashtagsUrl() {
  const res = { method: 'GET', url: `/hashtags/search` as const }
  return res
}

/**
 * @description Returns up to 10 hashtag names that start with the given prefix (min 2 chars). Results cached 2 minutes.
 * @summary Search hashtags by prefix
 * {@link /hashtags/search}
 */
export async function searchHashtags(params: SearchHashtagsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<SearchHashtagsQueryResponse, ResponseErrorConfig<SearchHashtags400 | SearchHashtags429 | SearchHashtags500>, unknown>({ method : "GET", url : getSearchHashtagsUrl().url.toString(), params, ... requestConfig })
  return res.data
}