/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SearchQueryResponse, SearchQueryParams, Search400, Search500 } from "../models/Search.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getSearchUrl() {
  const res = { method: 'GET', url: `/search` as const }
  return res
}

/**
 * @description Search across users, posts, and hashtags in a single request.
 * Use type=all (default) to fetch top results from every category,
 * or specify type=users|posts|hashtags for a focused search.
 * @summary Unified search
 * {@link /search}
 */
export async function search(params: SearchQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<SearchQueryResponse, ResponseErrorConfig<Search400 | Search500>, unknown>({ method : "GET", url : getSearchUrl().url.toString(), params, ... requestConfig })
  return res.data
}