/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StreamNotificationsQueryResponse, StreamNotificationsQueryParams, StreamNotifications401, StreamNotifications501 } from "../models/StreamNotifications.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getStreamNotificationsUrl() {
  const res = { method: 'GET', url: `/notifications/stream` as const }
  return res
}

/**
 * @description Open a Server-Sent Events stream for real-time notifications. Pass JWT via Authorization header or ?token= query parameter.
 * @summary Stream notifications (SSE)
 * {@link /notifications/stream}
 */
export async function streamNotifications(params?: StreamNotificationsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<StreamNotificationsQueryResponse, ResponseErrorConfig<StreamNotifications401 | StreamNotifications501>, unknown>({ method : "GET", url : getStreamNotificationsUrl().url.toString(), params, ... requestConfig })
  return res.data
}