/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ToggleCommentLikeMutationResponse, ToggleCommentLikePathParams, ToggleCommentLike400, ToggleCommentLike401, ToggleCommentLike404, ToggleCommentLike500 } from "../models/ToggleCommentLike.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getToggleCommentLikeUrl(postID: ToggleCommentLikePathParams["postID"], commentID: ToggleCommentLikePathParams["commentID"]) {
  const res = { method: 'POST', url: `/posts/${postID}/comments/${commentID}/like` as const }
  return res
}

/**
 * @description Like the comment if not yet liked, unlike if already liked. Returns the new like state.
 * @summary Toggle like on a comment
 * {@link /posts/:postID/comments/:commentID/like}
 */
export async function toggleCommentLike(postID: ToggleCommentLikePathParams["postID"], commentID: ToggleCommentLikePathParams["commentID"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ToggleCommentLikeMutationResponse, ResponseErrorConfig<ToggleCommentLike400 | ToggleCommentLike401 | ToggleCommentLike404 | ToggleCommentLike500>, unknown>({ method : "POST", url : getToggleCommentLikeUrl(postID, commentID).url.toString(), ... requestConfig })
  return res.data
}