/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ToggleLikeMutationResponse, ToggleLikePathParams, ToggleLike400, ToggleLike401, ToggleLike404, ToggleLike500 } from "../models/ToggleLike.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getToggleLikeUrl(postID: ToggleLikePathParams["postID"]) {
  const res = { method: 'POST', url: `/posts/${postID}/like` as const }
  return res
}

/**
 * @description Like the post if not yet liked, unlike if already liked. Returns the new like state.
 * @summary Toggle like on a post
 * {@link /posts/:postID/like}
 */
export async function toggleLike(postID: ToggleLikePathParams["postID"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ToggleLikeMutationResponse, ResponseErrorConfig<ToggleLike400 | ToggleLike401 | ToggleLike404 | ToggleLike500>, unknown>({ method : "POST", url : getToggleLikeUrl(postID).url.toString(), ... requestConfig })
  return res.data
}