/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { UnfollowUserMutationResponse, UnfollowUserPathParams, UnfollowUserQueryParams, UnfollowUser400, UnfollowUser401, UnfollowUser500 } from "../models/UnfollowUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getUnfollowUserUrl(userKey: UnfollowUserPathParams["userKey"]) {
  const res = { method: 'DELETE', url: `/users/${userKey}/follow` as const }
  return res
}

/**
 * @description Unfollow a user by UUID or username (with ?by=username). No-op if not following.
 * @summary Unfollow a user
 * {@link /users/:userKey/follow}
 */
export async function unfollowUser(userKey: UnfollowUserPathParams["userKey"], params?: UnfollowUserQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<UnfollowUserMutationResponse, ResponseErrorConfig<UnfollowUser400 | UnfollowUser401 | UnfollowUser500>, unknown>({ method : "DELETE", url : getUnfollowUserUrl(userKey).url.toString(), params, ... requestConfig })
  return res.data
}