/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { UpdateMyProfileMutationRequest, UpdateMyProfileMutationResponse, UpdateMyProfile400, UpdateMyProfile401, UpdateMyProfile404, UpdateMyProfile500 } from "../models/UpdateMyProfile.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getUpdateMyProfileUrl() {
  const res = { method: 'PUT', url: `/me` as const }
  return res
}

/**
 * @description Update the authenticated user's social profile fields
 * @summary Update my profile
 * {@link /me}
 */
export async function updateMyProfile(data: UpdateMyProfileMutationRequest, config: Partial<RequestConfig<UpdateMyProfileMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<UpdateMyProfileMutationResponse, ResponseErrorConfig<UpdateMyProfile400 | UpdateMyProfile401 | UpdateMyProfile404 | UpdateMyProfile500>, UpdateMyProfileMutationRequest>({ method : "PUT", url : getUpdateMyProfileUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}