/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { UpdateUserMutationRequest, UpdateUserMutationResponse, UpdateUserPathParams, UpdateUserQueryParams, UpdateUser400, UpdateUser404, UpdateUser409, UpdateUser500 } from "../models/UpdateUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getUpdateUserUrl(userKey: UpdateUserPathParams["userKey"]) {
  const res = { method: 'PUT', url: `/users/${userKey}` as const }
  return res
}

/**
 * @description Update user account fields (e.g. email) by UUID or username (with ?by=username)
 * @summary Update user account
 * {@link /users/:userKey}
 */
export async function updateUser(userKey: UpdateUserPathParams["userKey"], data: UpdateUserMutationRequest, params?: UpdateUserQueryParams, config: Partial<RequestConfig<UpdateUserMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<UpdateUserMutationResponse, ResponseErrorConfig<UpdateUser400 | UpdateUser404 | UpdateUser409 | UpdateUser500>, UpdateUserMutationRequest>({ method : "PUT", url : getUpdateUserUrl(userKey).url.toString(), params, data : requestData, ... requestConfig })
  return res.data
}