/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { UpdatePostMutationRequest, UpdatePostMutationResponse, UpdatePostPathParams, UpdatePost400, UpdatePost401, UpdatePost403, UpdatePost404, UpdatePost500 } from "../models/UpdatePost.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getUpdatePostUrl(postID: UpdatePostPathParams["postID"]) {
  const res = { method: 'PUT', url: `/posts/${postID}` as const }
  return res
}

/**
 * @description Update content or visibility of an owned post
 * @summary Update a post
 * {@link /posts/:postID}
 */
export async function updatePost(postID: UpdatePostPathParams["postID"], data: UpdatePostMutationRequest, config: Partial<RequestConfig<UpdatePostMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<UpdatePostMutationResponse, ResponseErrorConfig<UpdatePost400 | UpdatePost401 | UpdatePost403 | UpdatePost404 | UpdatePost500>, UpdatePostMutationRequest>({ method : "PUT", url : getUpdatePostUrl(postID).url.toString(), data : requestData, ... requestConfig })
  return res.data
}