/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { UploadAvatarMutationRequest, UploadAvatarMutationResponse, UploadAvatar400, UploadAvatar401, UploadAvatar404, UploadAvatar500 } from "../models/UploadAvatar.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { buildFormData } from "../.kubb/config.ts";

function getUploadAvatarUrl() {
  const res = { method: 'PUT', url: `/me/avatar` as const }
  return res
}

/**
 * @description Upload a new avatar image for the authenticated user
 * @summary Upload avatar
 * {@link /me/avatar}
 */
export async function uploadAvatar(data: UploadAvatarMutationRequest, config: Partial<RequestConfig<UploadAvatarMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data
  const formData = buildFormData(requestData)
  const res = await request<UploadAvatarMutationResponse, ResponseErrorConfig<UploadAvatar400 | UploadAvatar401 | UploadAvatar404 | UploadAvatar500>, UploadAvatarMutationRequest>({ method : "PUT", url : getUploadAvatarUrl().url.toString(), data : formData as FormData, ... requestConfig })
  return res.data
}