/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { UploadMediaMutationRequest, UploadMediaMutationResponse, UploadMedia400, UploadMedia401, UploadMedia413, UploadMedia415, UploadMedia500 } from "../models/UploadMedia.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { buildFormData } from "../.kubb/config.ts";

function getUploadMediaUrl() {
  const res = { method: 'POST', url: `/media/upload` as const }
  return res
}

/**
 * @description Upload an image or video file. Returns the storage key and public URL.
 * Supported types: image/jpeg, image/png, image/webp, image/gif, video/mp4, video/webm
 * Max size: 10 MB for images, 100 MB for videos.
 * @summary Upload a media file
 * {@link /media/upload}
 */
export async function uploadMedia(data: UploadMediaMutationRequest, config: Partial<RequestConfig<UploadMediaMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data
  const formData = buildFormData(requestData)
  const res = await request<UploadMediaMutationResponse, ResponseErrorConfig<UploadMedia400 | UploadMedia401 | UploadMedia413 | UploadMedia415 | UploadMedia500>, UploadMediaMutationRequest>({ method : "POST", url : getUploadMediaUrl().url.toString(), data : formData as FormData, ... requestConfig })
  return res.data
}