/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { UploadCoverMutationRequest, UploadCoverMutationResponse, UploadCover400, UploadCover401, UploadCover404, UploadCover500 } from "../models/UploadCover.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { buildFormData } from "../.kubb/config.ts";

function getUploadCoverUrl() {
  const res = { method: 'PUT', url: `/me/cover` as const }
  return res
}

/**
 * @description Upload a new cover image for the authenticated user
 * @summary Upload cover image
 * {@link /me/cover}
 */
export async function uploadCover(data: UploadCoverMutationRequest, config: Partial<RequestConfig<UploadCoverMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data
  const formData = buildFormData(requestData)
  const res = await request<UploadCoverMutationResponse, ResponseErrorConfig<UploadCover400 | UploadCover401 | UploadCover404 | UploadCover500>, UploadCoverMutationRequest>({ method : "PUT", url : getUploadCoverUrl().url.toString(), data : formData as FormData, ... requestConfig })
  return res.data
}