/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { VerifyEmailMutationRequest, VerifyEmailMutationResponse, VerifyEmail400, VerifyEmail500 } from "../models/VerifyEmail.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getVerifyEmailUrl() {
  const res = { method: 'POST', url: `/auth/verify-email` as const }
  return res
}

/**
 * @description Verify a user's email address using the token sent via email
 * @summary Verify email address
 * {@link /auth/verify-email}
 */
export async function verifyEmail(data: VerifyEmailMutationRequest, config: Partial<RequestConfig<VerifyEmailMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<VerifyEmailMutationResponse, ResponseErrorConfig<VerifyEmail400 | VerifyEmail500>, VerifyEmailMutationRequest>({ method : "POST", url : getVerifyEmailUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}