// Builds the icon sprite and its name union from the individual files in src/icons/.
// Each src/icons/<name>.svg becomes a <symbol id="<name>"> in public/icons.svg.
// Run via `npm run icons` — also runs automatically before `dev` and `build`.
import { readFileSync, writeFileSync, readdirSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const iconDir = join(root, "src/icons")
const spriteOut = join(root, "public/icons.svg")
const typesOut = join(root, "src/components/ui/icon-names.ts")

// Presentation attributes worth carrying onto the <symbol>. Anything else
// (xmlns, class, width/height) is dropped — the sprite has no use for it.
const KEEP = ["viewBox", "fill", "stroke", "stroke-width", "stroke-linecap", "stroke-linejoin"]

const names = readdirSync(iconDir)
  .filter((f) => f.endsWith(".svg"))
  .map((f) => f.replace(/\.svg$/, ""))
  .sort()

if (names.length === 0) {
  console.error("build-icons: no .svg files found in src/icons/")
  process.exit(1)
}

const symbols = names.map((name) => {
  const raw = readFileSync(join(iconDir, `${name}.svg`), "utf8")
  const open = raw.match(/<svg([^>]*)>/)
  const body = raw.match(/<svg[^>]*>([\s\S]*)<\/svg>/)

  if (!open || !body) {
    console.error(`build-icons: ${name}.svg is not a well-formed <svg> element`)
    process.exit(1)
  }

  const attrs = KEEP.map((key) => {
    const found = open[1].match(new RegExp(`\\s${key}="([^"]*)"`))
    return found ? `${key}="${found[1]}"` : null
  }).filter(Boolean)

  // Without a viewBox the symbol renders at its intrinsic size and gets
  // cropped by the <svg> the Icon component sizes — always a bug.
  if (!attrs.some((a) => a.startsWith("viewBox="))) {
    console.error(`build-icons: ${name}.svg is missing a viewBox`)
    process.exit(1)
  }

  const inner = body[1].trim().replace(/\s*\n\s*/g, "")
  return `  <symbol id="${name}" ${attrs.join(" ")}>${inner}</symbol>`
})

writeFileSync(
  spriteOut,
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n${symbols.join("\n")}\n</svg>\n`,
)

writeFileSync(
  typesOut,
  `// Generated by scripts/build-icons.mjs from src/icons/ — do not edit.\n` +
    `export type IconName =\n${names.map((n) => `  | "${n}"`).join("\n")}\n`,
)

console.log(
  `build-icons: ${names.length} icons -> public/icons.svg, src/components/ui/icon-names.ts`,
)
