/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminSendNotificationToUserMutationRequest, AdminSendNotificationToUserMutationResponse, AdminSendNotificationToUserPathParams, AdminSendNotificationToUser400, AdminSendNotificationToUser401, AdminSendNotificationToUser403, AdminSendNotificationToUser404 } from "../models/AdminSendNotificationToUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminSendNotificationToUser } from "../clients/adminSendNotificationToUser.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminSendNotificationToUserMutationKey = () => [{ url: '/admin/notifications/users/:id' }] as const

export type AdminSendNotificationToUserMutationKey = ReturnType<typeof adminSendNotificationToUserMutationKey>

export function adminSendNotificationToUserMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AdminSendNotificationToUserMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = adminSendNotificationToUserMutationKey()
        return mutationOptions<AdminSendNotificationToUserMutationResponse, ResponseErrorConfig<AdminSendNotificationToUser400 | AdminSendNotificationToUser401 | AdminSendNotificationToUser403 | AdminSendNotificationToUser404>, {id: AdminSendNotificationToUserPathParams["id"], data: AdminSendNotificationToUserMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return adminSendNotificationToUser(id, data, config)
          },
        })

}

/**
 * @description Sends a system announcement notification to a specific user.
 * @summary Send notification to a user
 * {@link /admin/notifications/users/:id}
 */
export function useAdminSendNotificationToUser<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminSendNotificationToUserMutationResponse, ResponseErrorConfig<AdminSendNotificationToUser400 | AdminSendNotificationToUser401 | AdminSendNotificationToUser403 | AdminSendNotificationToUser404>, {id: AdminSendNotificationToUserPathParams["id"], data: AdminSendNotificationToUserMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AdminSendNotificationToUserMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminSendNotificationToUserMutationKey()

          const baseOptions = adminSendNotificationToUserMutationOptions(config) as UseMutationOptions<AdminSendNotificationToUserMutationResponse, ResponseErrorConfig<AdminSendNotificationToUser400 | AdminSendNotificationToUser401 | AdminSendNotificationToUser403 | AdminSendNotificationToUser404>, {id: AdminSendNotificationToUserPathParams["id"], data: AdminSendNotificationToUserMutationRequest}, TContext>
          

          return useMutation<AdminSendNotificationToUserMutationResponse, ResponseErrorConfig<AdminSendNotificationToUser400 | AdminSendNotificationToUser401 | AdminSendNotificationToUser403 | AdminSendNotificationToUser404>, {id: AdminSendNotificationToUserPathParams["id"], data: AdminSendNotificationToUserMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminSendNotificationToUserMutationResponse, ResponseErrorConfig<AdminSendNotificationToUser400 | AdminSendNotificationToUser401 | AdminSendNotificationToUser403 | AdminSendNotificationToUser404>, {id: AdminSendNotificationToUserPathParams["id"], data: AdminSendNotificationToUserMutationRequest}, TContext>
      
}