/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminGetFeedSettingsQueryResponse, AdminGetFeedSettings401, AdminGetFeedSettings403, AdminGetFeedSettings500 } from "../models/AdminGetFeedSettings.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { adminGetFeedSettings } from "../clients/adminGetFeedSettings.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const adminGetFeedSettingsSuspenseQueryKey = () => [{ url: '/admin/settings/feed' }] as const

export type AdminGetFeedSettingsSuspenseQueryKey = ReturnType<typeof adminGetFeedSettingsSuspenseQueryKey>

export function adminGetFeedSettingsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminGetFeedSettingsSuspenseQueryKey()
        return queryOptions<AdminGetFeedSettingsQueryResponse, ResponseErrorConfig<AdminGetFeedSettings401 | AdminGetFeedSettings403 | AdminGetFeedSettings500>, AdminGetFeedSettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminGetFeedSettings({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns the feed knobs that can be changed while the API is running: prepared-timeline serving and its rollout, fanout, and the three local ranking weights. Fanout worker count and queue size are not here — they size a goroutine pool at construction and still require a restart, so they stay in the environment.
 * @summary Get feed runtime settings
 * {@link /admin/settings/feed}
 */
export function useAdminGetFeedSettingsSuspense<TData = AdminGetFeedSettingsQueryResponse, TQueryKey extends QueryKey = AdminGetFeedSettingsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AdminGetFeedSettingsQueryResponse, ResponseErrorConfig<AdminGetFeedSettings401 | AdminGetFeedSettings403 | AdminGetFeedSettings500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminGetFeedSettingsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...adminGetFeedSettingsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<AdminGetFeedSettings401 | AdminGetFeedSettings403 | AdminGetFeedSettings500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}