/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminSetUserStatusMutationRequest, AdminSetUserStatusMutationResponse, AdminSetUserStatusPathParams, AdminSetUserStatus400, AdminSetUserStatus401, AdminSetUserStatus403, AdminSetUserStatus404 } from "../models/AdminSetUserStatus.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminSetUserStatus } from "../clients/adminSetUserStatus.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminSetUserStatusMutationKey = () => [{ url: '/admin/users/:id/status' }] as const

export type AdminSetUserStatusMutationKey = ReturnType<typeof adminSetUserStatusMutationKey>

export function adminSetUserStatusMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AdminSetUserStatusMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = adminSetUserStatusMutationKey()
        return mutationOptions<AdminSetUserStatusMutationResponse, ResponseErrorConfig<AdminSetUserStatus400 | AdminSetUserStatus401 | AdminSetUserStatus403 | AdminSetUserStatus404>, {id: AdminSetUserStatusPathParams["id"], data: AdminSetUserStatusMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return adminSetUserStatus(id, data, config)
          },
        })

}

/**
 * @description Sets the active status of a user account. Deactivated users cannot log in.
 * @summary Activate or deactivate a user
 * {@link /admin/users/:id/status}
 */
export function useAdminSetUserStatus<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminSetUserStatusMutationResponse, ResponseErrorConfig<AdminSetUserStatus400 | AdminSetUserStatus401 | AdminSetUserStatus403 | AdminSetUserStatus404>, {id: AdminSetUserStatusPathParams["id"], data: AdminSetUserStatusMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AdminSetUserStatusMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminSetUserStatusMutationKey()

          const baseOptions = adminSetUserStatusMutationOptions(config) as UseMutationOptions<AdminSetUserStatusMutationResponse, ResponseErrorConfig<AdminSetUserStatus400 | AdminSetUserStatus401 | AdminSetUserStatus403 | AdminSetUserStatus404>, {id: AdminSetUserStatusPathParams["id"], data: AdminSetUserStatusMutationRequest}, TContext>
          

          return useMutation<AdminSetUserStatusMutationResponse, ResponseErrorConfig<AdminSetUserStatus400 | AdminSetUserStatus401 | AdminSetUserStatus403 | AdminSetUserStatus404>, {id: AdminSetUserStatusPathParams["id"], data: AdminSetUserStatusMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminSetUserStatusMutationResponse, ResponseErrorConfig<AdminSetUserStatus400 | AdminSetUserStatus401 | AdminSetUserStatus403 | AdminSetUserStatus404>, {id: AdminSetUserStatusPathParams["id"], data: AdminSetUserStatusMutationRequest}, TContext>
      
}