/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminGetStatsQueryResponse, AdminGetStats401, AdminGetStats403, AdminGetStats500 } from "../models/AdminGetStats.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { adminGetStats } from "../clients/adminGetStats.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const adminGetStatsSuspenseQueryKey = () => [{ url: '/admin/stats' }] as const

export type AdminGetStatsSuspenseQueryKey = ReturnType<typeof adminGetStatsSuspenseQueryKey>

export function adminGetStatsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminGetStatsSuspenseQueryKey()
        return queryOptions<AdminGetStatsQueryResponse, ResponseErrorConfig<AdminGetStats401 | AdminGetStats403 | AdminGetStats500>, AdminGetStatsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminGetStats({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns basic counts for users and roles.
 * @summary Get platform statistics
 * {@link /admin/stats}
 */
export function useAdminGetStatsSuspense<TData = AdminGetStatsQueryResponse, TQueryKey extends QueryKey = AdminGetStatsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AdminGetStatsQueryResponse, ResponseErrorConfig<AdminGetStats401 | AdminGetStats403 | AdminGetStats500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminGetStatsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...adminGetStatsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<AdminGetStats401 | AdminGetStats403 | AdminGetStats500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}