/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminUpdateFeedSettingsMutationRequest, AdminUpdateFeedSettingsMutationResponse, AdminUpdateFeedSettings400, AdminUpdateFeedSettings401, AdminUpdateFeedSettings403, AdminUpdateFeedSettings500 } from "../models/AdminUpdateFeedSettings.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminUpdateFeedSettings } from "../clients/adminUpdateFeedSettings.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminUpdateFeedSettingsMutationKey = () => [{ url: '/admin/settings/feed' }] as const

export type AdminUpdateFeedSettingsMutationKey = ReturnType<typeof adminUpdateFeedSettingsMutationKey>

export function adminUpdateFeedSettingsMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AdminUpdateFeedSettingsMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = adminUpdateFeedSettingsMutationKey()
        return mutationOptions<AdminUpdateFeedSettingsMutationResponse, ResponseErrorConfig<AdminUpdateFeedSettings400 | AdminUpdateFeedSettings401 | AdminUpdateFeedSettings403 | AdminUpdateFeedSettings500>, {data: AdminUpdateFeedSettingsMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return adminUpdateFeedSettings(data, config)
          },
        })

}

/**
 * @description Partial update — an omitted field keeps its stored value, and a body naming no field at all is a 400 rather than an edit that changes nothing. Takes effect on this instance immediately and on any other instance within one refresh interval, without a restart.
 * @summary Update feed runtime settings
 * {@link /admin/settings/feed}
 */
export function useAdminUpdateFeedSettings<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminUpdateFeedSettingsMutationResponse, ResponseErrorConfig<AdminUpdateFeedSettings400 | AdminUpdateFeedSettings401 | AdminUpdateFeedSettings403 | AdminUpdateFeedSettings500>, {data: AdminUpdateFeedSettingsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AdminUpdateFeedSettingsMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminUpdateFeedSettingsMutationKey()

          const baseOptions = adminUpdateFeedSettingsMutationOptions(config) as UseMutationOptions<AdminUpdateFeedSettingsMutationResponse, ResponseErrorConfig<AdminUpdateFeedSettings400 | AdminUpdateFeedSettings401 | AdminUpdateFeedSettings403 | AdminUpdateFeedSettings500>, {data: AdminUpdateFeedSettingsMutationRequest}, TContext>
          

          return useMutation<AdminUpdateFeedSettingsMutationResponse, ResponseErrorConfig<AdminUpdateFeedSettings400 | AdminUpdateFeedSettings401 | AdminUpdateFeedSettings403 | AdminUpdateFeedSettings500>, {data: AdminUpdateFeedSettingsMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminUpdateFeedSettingsMutationResponse, ResponseErrorConfig<AdminUpdateFeedSettings400 | AdminUpdateFeedSettings401 | AdminUpdateFeedSettings403 | AdminUpdateFeedSettings500>, {data: AdminUpdateFeedSettingsMutationRequest}, TContext>
      
}