/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminGetUserQueryResponse, AdminGetUserPathParams, AdminGetUser400, AdminGetUser401, AdminGetUser403, AdminGetUser404 } from "../models/AdminGetUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { adminGetUser } from "../clients/adminGetUser.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const adminGetUserSuspenseQueryKey = (id: AdminGetUserPathParams["id"]) => [{ url: '/admin/users/:id', params: {id:id} }] as const

export type AdminGetUserSuspenseQueryKey = ReturnType<typeof adminGetUserSuspenseQueryKey>

export function adminGetUserSuspenseQueryOptions(id: AdminGetUserPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminGetUserSuspenseQueryKey(id)
        return queryOptions<AdminGetUserQueryResponse, ResponseErrorConfig<AdminGetUser400 | AdminGetUser401 | AdminGetUser403 | AdminGetUser404>, AdminGetUserQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            return adminGetUser(id, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns the admin view of a single user including email and active status.
 * @summary Get user details
 * {@link /admin/users/:id}
 */
export function useAdminGetUserSuspense<TData = AdminGetUserQueryResponse, TQueryKey extends QueryKey = AdminGetUserSuspenseQueryKey>(id: AdminGetUserPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<AdminGetUserQueryResponse, ResponseErrorConfig<AdminGetUser400 | AdminGetUser401 | AdminGetUser403 | AdminGetUser404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminGetUserSuspenseQueryKey(id)
         

         const query = useSuspenseQuery({
          ...adminGetUserSuspenseQueryOptions(id, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<AdminGetUser400 | AdminGetUser401 | AdminGetUser403 | AdminGetUser404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}