/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminBroadcastNotificationMutationRequest, AdminBroadcastNotificationMutationResponse, AdminBroadcastNotification400, AdminBroadcastNotification401, AdminBroadcastNotification403 } from "../models/AdminBroadcastNotification.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminBroadcastNotification } from "../clients/adminBroadcastNotification.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminBroadcastNotificationMutationKey = () => [{ url: '/admin/notifications/broadcast' }] as const

export type AdminBroadcastNotificationMutationKey = ReturnType<typeof adminBroadcastNotificationMutationKey>

export function adminBroadcastNotificationMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AdminBroadcastNotificationMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = adminBroadcastNotificationMutationKey()
        return mutationOptions<AdminBroadcastNotificationMutationResponse, ResponseErrorConfig<AdminBroadcastNotification400 | AdminBroadcastNotification401 | AdminBroadcastNotification403>, {data: AdminBroadcastNotificationMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return adminBroadcastNotification(data, config)
          },
        })

}

/**
 * @description Sends a system announcement notification to all active users.
 * @summary Broadcast notification to all users
 * {@link /admin/notifications/broadcast}
 */
export function useAdminBroadcastNotification<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminBroadcastNotificationMutationResponse, ResponseErrorConfig<AdminBroadcastNotification400 | AdminBroadcastNotification401 | AdminBroadcastNotification403>, {data: AdminBroadcastNotificationMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AdminBroadcastNotificationMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminBroadcastNotificationMutationKey()

          const baseOptions = adminBroadcastNotificationMutationOptions(config) as UseMutationOptions<AdminBroadcastNotificationMutationResponse, ResponseErrorConfig<AdminBroadcastNotification400 | AdminBroadcastNotification401 | AdminBroadcastNotification403>, {data: AdminBroadcastNotificationMutationRequest}, TContext>
          

          return useMutation<AdminBroadcastNotificationMutationResponse, ResponseErrorConfig<AdminBroadcastNotification400 | AdminBroadcastNotification401 | AdminBroadcastNotification403>, {data: AdminBroadcastNotificationMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminBroadcastNotificationMutationResponse, ResponseErrorConfig<AdminBroadcastNotification400 | AdminBroadcastNotification401 | AdminBroadcastNotification403>, {data: AdminBroadcastNotificationMutationRequest}, TContext>
      
}