/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminGetStatsQueryResponse, AdminGetStats401, AdminGetStats403, AdminGetStats500 } from "../models/AdminGetStats.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { adminGetStats } from "../clients/adminGetStats.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const adminGetStatsQueryKey = () => [{ url: '/admin/stats' }] as const

export type AdminGetStatsQueryKey = ReturnType<typeof adminGetStatsQueryKey>

export function adminGetStatsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminGetStatsQueryKey()
        return queryOptions<AdminGetStatsQueryResponse, ResponseErrorConfig<AdminGetStats401 | AdminGetStats403 | AdminGetStats500>, AdminGetStatsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminGetStats({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns basic counts for users and roles.
 * @summary Get platform statistics
 * {@link /admin/stats}
 */
export function useAdminGetStats<TData = AdminGetStatsQueryResponse, TQueryData = AdminGetStatsQueryResponse, TQueryKey extends QueryKey = AdminGetStatsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<AdminGetStatsQueryResponse, ResponseErrorConfig<AdminGetStats401 | AdminGetStats403 | AdminGetStats500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminGetStatsQueryKey()
         

         const query = useQuery({
          ...adminGetStatsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<AdminGetStats401 | AdminGetStats403 | AdminGetStats500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}