/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminListUsersQueryResponse, AdminListUsersQueryParams, AdminListUsers401, AdminListUsers403, AdminListUsers500 } from "../models/AdminListUsers.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { adminListUsers } from "../clients/adminListUsers.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const adminListUsersQueryKey = (params?: AdminListUsersQueryParams) => [{ url: '/admin/users' }, ...(params ? [params] : [])] as const

export type AdminListUsersQueryKey = ReturnType<typeof adminListUsersQueryKey>

export function adminListUsersQueryOptions(params?: AdminListUsersQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminListUsersQueryKey(params)
        return queryOptions<AdminListUsersQueryResponse, ResponseErrorConfig<AdminListUsers401 | AdminListUsers403 | AdminListUsers500>, AdminListUsersQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminListUsers(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns a paginated list of all users. Supports filtering by status and search query.
 * @summary List all users
 * {@link /admin/users}
 */
export function useAdminListUsers<TData = AdminListUsersQueryResponse, TQueryData = AdminListUsersQueryResponse, TQueryKey extends QueryKey = AdminListUsersQueryKey>(params?: AdminListUsersQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<AdminListUsersQueryResponse, ResponseErrorConfig<AdminListUsers401 | AdminListUsers403 | AdminListUsers500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminListUsersQueryKey(params)
         

         const query = useQuery({
          ...adminListUsersQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<AdminListUsers401 | AdminListUsers403 | AdminListUsers500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}