/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminGetUserRolesQueryResponse, AdminGetUserRolesPathParams, AdminGetUserRoles400, AdminGetUserRoles401, AdminGetUserRoles403, AdminGetUserRoles404 } from "../models/AdminGetUserRoles.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { adminGetUserRoles } from "../clients/adminGetUserRoles.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const adminGetUserRolesQueryKey = (id: AdminGetUserRolesPathParams["id"]) => [{ url: '/admin/users/:id/roles', params: {id:id} }] as const

export type AdminGetUserRolesQueryKey = ReturnType<typeof adminGetUserRolesQueryKey>

export function adminGetUserRolesQueryOptions(id: AdminGetUserRolesPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminGetUserRolesQueryKey(id)
        return queryOptions<AdminGetUserRolesQueryResponse, ResponseErrorConfig<AdminGetUserRoles400 | AdminGetUserRoles401 | AdminGetUserRoles403 | AdminGetUserRoles404>, AdminGetUserRolesQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            return adminGetUserRoles(id, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns all roles currently assigned to the specified user.
 * @summary Get roles for a user
 * {@link /admin/users/:id/roles}
 */
export function useAdminGetUserRoles<TData = AdminGetUserRolesQueryResponse, TQueryData = AdminGetUserRolesQueryResponse, TQueryKey extends QueryKey = AdminGetUserRolesQueryKey>(id: AdminGetUserRolesPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<AdminGetUserRolesQueryResponse, ResponseErrorConfig<AdminGetUserRoles400 | AdminGetUserRoles401 | AdminGetUserRoles403 | AdminGetUserRoles404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminGetUserRolesQueryKey(id)
         

         const query = useQuery({
          ...adminGetUserRolesQueryOptions(id, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<AdminGetUserRoles400 | AdminGetUserRoles401 | AdminGetUserRoles403 | AdminGetUserRoles404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}