/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminAssignRoleMutationRequest, AdminAssignRoleMutationResponse, AdminAssignRolePathParams, AdminAssignRole400, AdminAssignRole401, AdminAssignRole403, AdminAssignRole404 } from "../models/AdminAssignRole.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminAssignRole } from "../clients/adminAssignRole.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminAssignRoleMutationKey = () => [{ url: '/admin/users/:id/roles' }] as const

export type AdminAssignRoleMutationKey = ReturnType<typeof adminAssignRoleMutationKey>

export function adminAssignRoleMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AdminAssignRoleMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = adminAssignRoleMutationKey()
        return mutationOptions<AdminAssignRoleMutationResponse, ResponseErrorConfig<AdminAssignRole400 | AdminAssignRole401 | AdminAssignRole403 | AdminAssignRole404>, {id: AdminAssignRolePathParams["id"], data: AdminAssignRoleMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return adminAssignRole(id, data, config)
          },
        })

}

/**
 * @description Grants a role to the specified user.
 * @summary Assign a role to a user
 * {@link /admin/users/:id/roles}
 */
export function useAdminAssignRole<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminAssignRoleMutationResponse, ResponseErrorConfig<AdminAssignRole400 | AdminAssignRole401 | AdminAssignRole403 | AdminAssignRole404>, {id: AdminAssignRolePathParams["id"], data: AdminAssignRoleMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AdminAssignRoleMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminAssignRoleMutationKey()

          const baseOptions = adminAssignRoleMutationOptions(config) as UseMutationOptions<AdminAssignRoleMutationResponse, ResponseErrorConfig<AdminAssignRole400 | AdminAssignRole401 | AdminAssignRole403 | AdminAssignRole404>, {id: AdminAssignRolePathParams["id"], data: AdminAssignRoleMutationRequest}, TContext>
          

          return useMutation<AdminAssignRoleMutationResponse, ResponseErrorConfig<AdminAssignRole400 | AdminAssignRole401 | AdminAssignRole403 | AdminAssignRole404>, {id: AdminAssignRolePathParams["id"], data: AdminAssignRoleMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminAssignRoleMutationResponse, ResponseErrorConfig<AdminAssignRole400 | AdminAssignRole401 | AdminAssignRole403 | AdminAssignRole404>, {id: AdminAssignRolePathParams["id"], data: AdminAssignRoleMutationRequest}, TContext>
      
}