/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminListRolesQueryResponse, AdminListRoles401, AdminListRoles403 } from "../models/AdminListRoles.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { adminListRoles } from "../clients/adminListRoles.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const adminListRolesSuspenseQueryKey = () => [{ url: '/admin/roles' }] as const

export type AdminListRolesSuspenseQueryKey = ReturnType<typeof adminListRolesSuspenseQueryKey>

export function adminListRolesSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminListRolesSuspenseQueryKey()
        return queryOptions<AdminListRolesQueryResponse, ResponseErrorConfig<AdminListRoles401 | AdminListRoles403>, AdminListRolesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminListRoles({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns the fixed set of roles that can be assigned to users. Roles are defined by the application, not created at runtime.
 * @summary List assignable roles
 * {@link /admin/roles}
 */
export function useAdminListRolesSuspense<TData = AdminListRolesQueryResponse, TQueryKey extends QueryKey = AdminListRolesSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AdminListRolesQueryResponse, ResponseErrorConfig<AdminListRoles401 | AdminListRoles403>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminListRolesSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...adminListRolesSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<AdminListRoles401 | AdminListRoles403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}