/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminRemoveRoleMutationResponse, AdminRemoveRolePathParams, AdminRemoveRole400, AdminRemoveRole401, AdminRemoveRole403 } from "../models/AdminRemoveRole.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminRemoveRole } from "../clients/adminRemoveRole.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminRemoveRoleMutationKey = () => [{ url: '/admin/users/:id/roles/:role' }] as const

export type AdminRemoveRoleMutationKey = ReturnType<typeof adminRemoveRoleMutationKey>

export function adminRemoveRoleMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = adminRemoveRoleMutationKey()
        return mutationOptions<AdminRemoveRoleMutationResponse, ResponseErrorConfig<AdminRemoveRole400 | AdminRemoveRole401 | AdminRemoveRole403>, {id: AdminRemoveRolePathParams["id"], role: AdminRemoveRolePathParams["role"]}, TContext>({
          mutationKey,
          mutationFn: async({ id, role }) => {
            return adminRemoveRole(id, role, config)
          },
        })

}

/**
 * @description Revokes a role from the specified user.
 * @summary Remove a role from a user
 * {@link /admin/users/:id/roles/:role}
 */
export function useAdminRemoveRole<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminRemoveRoleMutationResponse, ResponseErrorConfig<AdminRemoveRole400 | AdminRemoveRole401 | AdminRemoveRole403>, {id: AdminRemoveRolePathParams["id"], role: AdminRemoveRolePathParams["role"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminRemoveRoleMutationKey()

          const baseOptions = adminRemoveRoleMutationOptions(config) as UseMutationOptions<AdminRemoveRoleMutationResponse, ResponseErrorConfig<AdminRemoveRole400 | AdminRemoveRole401 | AdminRemoveRole403>, {id: AdminRemoveRolePathParams["id"], role: AdminRemoveRolePathParams["role"]}, TContext>
          

          return useMutation<AdminRemoveRoleMutationResponse, ResponseErrorConfig<AdminRemoveRole400 | AdminRemoveRole401 | AdminRemoveRole403>, {id: AdminRemoveRolePathParams["id"], role: AdminRemoveRolePathParams["role"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminRemoveRoleMutationResponse, ResponseErrorConfig<AdminRemoveRole400 | AdminRemoveRole401 | AdminRemoveRole403>, {id: AdminRemoveRolePathParams["id"], role: AdminRemoveRolePathParams["role"]}, TContext>
      
}