/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminListUsersQueryResponse, AdminListUsersQueryParams, AdminListUsers401, AdminListUsers403, AdminListUsers500 } from "../models/AdminListUsers.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { adminListUsers } from "../clients/adminListUsers.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const adminListUsersSuspenseQueryKey = (params?: AdminListUsersQueryParams) => [{ url: '/admin/users' }, ...(params ? [params] : [])] as const

export type AdminListUsersSuspenseQueryKey = ReturnType<typeof adminListUsersSuspenseQueryKey>

export function adminListUsersSuspenseQueryOptions(params?: AdminListUsersQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminListUsersSuspenseQueryKey(params)
        return queryOptions<AdminListUsersQueryResponse, ResponseErrorConfig<AdminListUsers401 | AdminListUsers403 | AdminListUsers500>, AdminListUsersQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminListUsers(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns a paginated list of all users. Supports filtering by status and search query.
 * @summary List all users
 * {@link /admin/users}
 */
export function useAdminListUsersSuspense<TData = AdminListUsersQueryResponse, TQueryKey extends QueryKey = AdminListUsersSuspenseQueryKey>(params?: AdminListUsersQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<AdminListUsersQueryResponse, ResponseErrorConfig<AdminListUsers401 | AdminListUsers403 | AdminListUsers500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminListUsersSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...adminListUsersSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<AdminListUsers401 | AdminListUsers403 | AdminListUsers500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}