/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminListRolesQueryResponse, AdminListRoles401, AdminListRoles403 } from "../models/AdminListRoles.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { adminListRoles } from "../clients/adminListRoles.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const adminListRolesQueryKey = () => [{ url: '/admin/roles' }] as const

export type AdminListRolesQueryKey = ReturnType<typeof adminListRolesQueryKey>

export function adminListRolesQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminListRolesQueryKey()
        return queryOptions<AdminListRolesQueryResponse, ResponseErrorConfig<AdminListRoles401 | AdminListRoles403>, AdminListRolesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminListRoles({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns the fixed set of roles that can be assigned to users. Roles are defined by the application, not created at runtime.
 * @summary List assignable roles
 * {@link /admin/roles}
 */
export function useAdminListRoles<TData = AdminListRolesQueryResponse, TQueryData = AdminListRolesQueryResponse, TQueryKey extends QueryKey = AdminListRolesQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<AdminListRolesQueryResponse, ResponseErrorConfig<AdminListRoles401 | AdminListRoles403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminListRolesQueryKey()
         

         const query = useQuery({
          ...adminListRolesQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<AdminListRoles401 | AdminListRoles403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}