/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateCommentMutationRequest, CreateCommentMutationResponse, CreateCommentPathParams, CreateComment400, CreateComment401, CreateComment404, CreateComment500 } from "../models/CreateComment.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { createComment } from "../clients/createComment.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createCommentMutationKey = () => [{ url: '/posts/:postID/comments' }] as const

export type CreateCommentMutationKey = ReturnType<typeof createCommentMutationKey>

export function createCommentMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CreateCommentMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = createCommentMutationKey()
        return mutationOptions<CreateCommentMutationResponse, ResponseErrorConfig<CreateComment400 | CreateComment401 | CreateComment404 | CreateComment500>, {postID: CreateCommentPathParams["postID"], data: CreateCommentMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ postID, data }) => {
            return createComment(postID, data, config)
          },
        })

}

/**
 * @description Add a comment (or reply) to a post
 * @summary Create a comment
 * {@link /posts/:postID/comments}
 */
export function useCreateComment<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateCommentMutationResponse, ResponseErrorConfig<CreateComment400 | CreateComment401 | CreateComment404 | CreateComment500>, {postID: CreateCommentPathParams["postID"], data: CreateCommentMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateCommentMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? createCommentMutationKey()

          const baseOptions = createCommentMutationOptions(config) as UseMutationOptions<CreateCommentMutationResponse, ResponseErrorConfig<CreateComment400 | CreateComment401 | CreateComment404 | CreateComment500>, {postID: CreateCommentPathParams["postID"], data: CreateCommentMutationRequest}, TContext>
          

          return useMutation<CreateCommentMutationResponse, ResponseErrorConfig<CreateComment400 | CreateComment401 | CreateComment404 | CreateComment500>, {postID: CreateCommentPathParams["postID"], data: CreateCommentMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CreateCommentMutationResponse, ResponseErrorConfig<CreateComment400 | CreateComment401 | CreateComment404 | CreateComment500>, {postID: CreateCommentPathParams["postID"], data: CreateCommentMutationRequest}, TContext>
      
}