/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeletePostMutationResponse, DeletePostPathParams, DeletePost400, DeletePost401, DeletePost403, DeletePost404, DeletePost500 } from "../models/DeletePost.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deletePost } from "../clients/deletePost.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deletePostMutationKey = () => [{ url: '/posts/:postID' }] as const

export type DeletePostMutationKey = ReturnType<typeof deletePostMutationKey>

export function deletePostMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deletePostMutationKey()
        return mutationOptions<DeletePostMutationResponse, ResponseErrorConfig<DeletePost400 | DeletePost401 | DeletePost403 | DeletePost404 | DeletePost500>, {postID: DeletePostPathParams["postID"]}, TContext>({
          mutationKey,
          mutationFn: async({ postID }) => {
            return deletePost(postID, config)
          },
        })

}

/**
 * @description Soft-delete an owned post
 * @summary Delete a post
 * {@link /posts/:postID}
 */
export function useDeletePost<TContext>(options: 
{
  mutation?: UseMutationOptions<DeletePostMutationResponse, ResponseErrorConfig<DeletePost400 | DeletePost401 | DeletePost403 | DeletePost404 | DeletePost500>, {postID: DeletePostPathParams["postID"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deletePostMutationKey()

          const baseOptions = deletePostMutationOptions(config) as UseMutationOptions<DeletePostMutationResponse, ResponseErrorConfig<DeletePost400 | DeletePost401 | DeletePost403 | DeletePost404 | DeletePost500>, {postID: DeletePostPathParams["postID"]}, TContext>
          

          return useMutation<DeletePostMutationResponse, ResponseErrorConfig<DeletePost400 | DeletePost401 | DeletePost403 | DeletePost404 | DeletePost500>, {postID: DeletePostPathParams["postID"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeletePostMutationResponse, ResponseErrorConfig<DeletePost400 | DeletePost401 | DeletePost403 | DeletePost404 | DeletePost500>, {postID: DeletePostPathParams["postID"]}, TContext>
      
}