/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeactivateUserMutationResponse, DeactivateUserPathParams, DeactivateUserQueryParams, DeactivateUser400, DeactivateUser404, DeactivateUser500 } from "../models/DeactivateUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deactivateUser } from "../clients/deactivateUser.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deactivateUserMutationKey = () => [{ url: '/users/:userKey' }] as const

export type DeactivateUserMutationKey = ReturnType<typeof deactivateUserMutationKey>

export function deactivateUserMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deactivateUserMutationKey()
        return mutationOptions<DeactivateUserMutationResponse, ResponseErrorConfig<DeactivateUser400 | DeactivateUser404 | DeactivateUser500>, {userKey: DeactivateUserPathParams["userKey"], params?: DeactivateUserQueryParams}, TContext>({
          mutationKey,
          mutationFn: async({ userKey, params }) => {
            return deactivateUser(userKey, params, config)
          },
        })

}

/**
 * @description Soft delete a user account (sets is_active to false) by UUID or username (with ?by=username)
 * @summary Deactivate user
 * {@link /users/:userKey}
 */
export function useDeactivateUser<TContext>(options: 
{
  mutation?: UseMutationOptions<DeactivateUserMutationResponse, ResponseErrorConfig<DeactivateUser400 | DeactivateUser404 | DeactivateUser500>, {userKey: DeactivateUserPathParams["userKey"], params?: DeactivateUserQueryParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deactivateUserMutationKey()

          const baseOptions = deactivateUserMutationOptions(config) as UseMutationOptions<DeactivateUserMutationResponse, ResponseErrorConfig<DeactivateUser400 | DeactivateUser404 | DeactivateUser500>, {userKey: DeactivateUserPathParams["userKey"], params?: DeactivateUserQueryParams}, TContext>
          

          return useMutation<DeactivateUserMutationResponse, ResponseErrorConfig<DeactivateUser400 | DeactivateUser404 | DeactivateUser500>, {userKey: DeactivateUserPathParams["userKey"], params?: DeactivateUserQueryParams}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeactivateUserMutationResponse, ResponseErrorConfig<DeactivateUser400 | DeactivateUser404 | DeactivateUser500>, {userKey: DeactivateUserPathParams["userKey"], params?: DeactivateUserQueryParams}, TContext>
      
}