/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteCommentMutationResponse, DeleteCommentPathParams, DeleteComment400, DeleteComment401, DeleteComment403, DeleteComment404, DeleteComment500 } from "../models/DeleteComment.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deleteComment } from "../clients/deleteComment.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteCommentMutationKey = () => [{ url: '/posts/:postID/comments/:commentID' }] as const

export type DeleteCommentMutationKey = ReturnType<typeof deleteCommentMutationKey>

export function deleteCommentMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deleteCommentMutationKey()
        return mutationOptions<DeleteCommentMutationResponse, ResponseErrorConfig<DeleteComment400 | DeleteComment401 | DeleteComment403 | DeleteComment404 | DeleteComment500>, {postID: DeleteCommentPathParams["postID"], commentID: DeleteCommentPathParams["commentID"]}, TContext>({
          mutationKey,
          mutationFn: async({ postID, commentID }) => {
            return deleteComment(postID, commentID, config)
          },
        })

}

/**
 * @description Soft-delete an owned comment
 * @summary Delete a comment
 * {@link /posts/:postID/comments/:commentID}
 */
export function useDeleteComment<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteCommentMutationResponse, ResponseErrorConfig<DeleteComment400 | DeleteComment401 | DeleteComment403 | DeleteComment404 | DeleteComment500>, {postID: DeleteCommentPathParams["postID"], commentID: DeleteCommentPathParams["commentID"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteCommentMutationKey()

          const baseOptions = deleteCommentMutationOptions(config) as UseMutationOptions<DeleteCommentMutationResponse, ResponseErrorConfig<DeleteComment400 | DeleteComment401 | DeleteComment403 | DeleteComment404 | DeleteComment500>, {postID: DeleteCommentPathParams["postID"], commentID: DeleteCommentPathParams["commentID"]}, TContext>
          

          return useMutation<DeleteCommentMutationResponse, ResponseErrorConfig<DeleteComment400 | DeleteComment401 | DeleteComment403 | DeleteComment404 | DeleteComment500>, {postID: DeleteCommentPathParams["postID"], commentID: DeleteCommentPathParams["commentID"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteCommentMutationResponse, ResponseErrorConfig<DeleteComment400 | DeleteComment401 | DeleteComment403 | DeleteComment404 | DeleteComment500>, {postID: DeleteCommentPathParams["postID"], commentID: DeleteCommentPathParams["commentID"]}, TContext>
      
}