/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ForgotPasswordMutationRequest, ForgotPasswordMutationResponse, ForgotPassword400, ForgotPassword500 } from "../models/ForgotPassword.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { forgotPassword } from "../clients/forgotPassword.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const forgotPasswordMutationKey = () => [{ url: '/auth/forgot-password' }] as const

export type ForgotPasswordMutationKey = ReturnType<typeof forgotPasswordMutationKey>

export function forgotPasswordMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ForgotPasswordMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = forgotPasswordMutationKey()
        return mutationOptions<ForgotPasswordMutationResponse, ResponseErrorConfig<ForgotPassword400 | ForgotPassword500>, {data: ForgotPasswordMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return forgotPassword(data, config)
          },
        })

}

/**
 * @description Send a password reset link to the specified email address
 * @summary Request password reset
 * {@link /auth/forgot-password}
 */
export function useForgotPassword<TContext>(options: 
{
  mutation?: UseMutationOptions<ForgotPasswordMutationResponse, ResponseErrorConfig<ForgotPassword400 | ForgotPassword500>, {data: ForgotPasswordMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ForgotPasswordMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? forgotPasswordMutationKey()

          const baseOptions = forgotPasswordMutationOptions(config) as UseMutationOptions<ForgotPasswordMutationResponse, ResponseErrorConfig<ForgotPassword400 | ForgotPassword500>, {data: ForgotPasswordMutationRequest}, TContext>
          

          return useMutation<ForgotPasswordMutationResponse, ResponseErrorConfig<ForgotPassword400 | ForgotPassword500>, {data: ForgotPasswordMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ForgotPasswordMutationResponse, ResponseErrorConfig<ForgotPassword400 | ForgotPassword500>, {data: ForgotPasswordMutationRequest}, TContext>
      
}