/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FollowUserMutationResponse, FollowUserPathParams, FollowUserQueryParams, FollowUser400, FollowUser401, FollowUser500 } from "../models/FollowUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { followUser } from "../clients/followUser.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const followUserMutationKey = () => [{ url: '/users/:userKey/follow' }] as const

export type FollowUserMutationKey = ReturnType<typeof followUserMutationKey>

export function followUserMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = followUserMutationKey()
        return mutationOptions<FollowUserMutationResponse, ResponseErrorConfig<FollowUser400 | FollowUser401 | FollowUser500>, {userKey: FollowUserPathParams["userKey"], params?: FollowUserQueryParams}, TContext>({
          mutationKey,
          mutationFn: async({ userKey, params }) => {
            return followUser(userKey, params, config)
          },
        })

}

/**
 * @description Follow a user by UUID or username (with ?by=username). No-op if already following.
 * @summary Follow a user
 * {@link /users/:userKey/follow}
 */
export function useFollowUser<TContext>(options: 
{
  mutation?: UseMutationOptions<FollowUserMutationResponse, ResponseErrorConfig<FollowUser400 | FollowUser401 | FollowUser500>, {userKey: FollowUserPathParams["userKey"], params?: FollowUserQueryParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? followUserMutationKey()

          const baseOptions = followUserMutationOptions(config) as UseMutationOptions<FollowUserMutationResponse, ResponseErrorConfig<FollowUser400 | FollowUser401 | FollowUser500>, {userKey: FollowUserPathParams["userKey"], params?: FollowUserQueryParams}, TContext>
          

          return useMutation<FollowUserMutationResponse, ResponseErrorConfig<FollowUser400 | FollowUser401 | FollowUser500>, {userKey: FollowUserPathParams["userKey"], params?: FollowUserQueryParams}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<FollowUserMutationResponse, ResponseErrorConfig<FollowUser400 | FollowUser401 | FollowUser500>, {userKey: FollowUserPathParams["userKey"], params?: FollowUserQueryParams}, TContext>
      
}