/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetRepliesQueryResponse, GetRepliesPathParams, GetRepliesQueryParams, GetReplies400, GetReplies404, GetReplies500 } from "../models/GetReplies.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getReplies } from "../clients/getReplies.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getRepliesSuspenseQueryKey = (postID: GetRepliesPathParams["postID"], commentID: GetRepliesPathParams["commentID"], params?: GetRepliesQueryParams) => [{ url: '/posts/:postID/comments/:commentID/replies', params: {postID:postID,commentID:commentID} }, ...(params ? [params] : [])] as const

export type GetRepliesSuspenseQueryKey = ReturnType<typeof getRepliesSuspenseQueryKey>

export function getRepliesSuspenseQueryOptions(postID: GetRepliesPathParams["postID"], commentID: GetRepliesPathParams["commentID"], params?: GetRepliesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getRepliesSuspenseQueryKey(postID, commentID, params)
        return queryOptions<GetRepliesQueryResponse, ResponseErrorConfig<GetReplies400 | GetReplies404 | GetReplies500>, GetRepliesQueryResponse, typeof queryKey>({
         enabled: !!(postID&& commentID),
         queryKey,
         queryFn: async ({ signal }) => {
            return getReplies(postID, commentID, params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get a paginated list of replies for a comment
 * @summary Get replies
 * {@link /posts/:postID/comments/:commentID/replies}
 */
export function useGetRepliesSuspense<TData = GetRepliesQueryResponse, TQueryKey extends QueryKey = GetRepliesSuspenseQueryKey>(postID: GetRepliesPathParams["postID"], commentID: GetRepliesPathParams["commentID"], params?: GetRepliesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetRepliesQueryResponse, ResponseErrorConfig<GetReplies400 | GetReplies404 | GetReplies500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getRepliesSuspenseQueryKey(postID, commentID, params)
         

         const query = useSuspenseQuery({
          ...getRepliesSuspenseQueryOptions(postID, commentID, params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetReplies400 | GetReplies404 | GetReplies500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}