/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetFeedQueryResponse, GetFeedQueryParams, GetFeed400, GetFeed401, GetFeed500 } from "../models/GetFeed.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getFeed } from "../clients/getFeed.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getFeedSuspenseQueryKey = (params?: GetFeedQueryParams) => [{ url: '/feed' }, ...(params ? [params] : [])] as const

export type GetFeedSuspenseQueryKey = ReturnType<typeof getFeedSuspenseQueryKey>

export function getFeedSuspenseQueryOptions(params?: GetFeedQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getFeedSuspenseQueryKey(params)
        return queryOptions<GetFeedQueryResponse, ResponseErrorConfig<GetFeed400 | GetFeed401 | GetFeed500>, GetFeedQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getFeed(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get a scored, paginated feed of posts mixed from followed users and trending posts
 * @summary Get feed
 * {@link /feed}
 */
export function useGetFeedSuspense<TData = GetFeedQueryResponse, TQueryKey extends QueryKey = GetFeedSuspenseQueryKey>(params?: GetFeedQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetFeedQueryResponse, ResponseErrorConfig<GetFeed400 | GetFeed401 | GetFeed500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getFeedSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getFeedSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetFeed400 | GetFeed401 | GetFeed500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}