/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetPostQueryResponse, GetPostPathParams, GetPost400, GetPost404, GetPost500 } from "../models/GetPost.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getPost } from "../clients/getPost.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getPostQueryKey = (postID: GetPostPathParams["postID"]) => [{ url: '/posts/:postID', params: {postID:postID} }] as const

export type GetPostQueryKey = ReturnType<typeof getPostQueryKey>

export function getPostQueryOptions(postID: GetPostPathParams["postID"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getPostQueryKey(postID)
        return queryOptions<GetPostQueryResponse, ResponseErrorConfig<GetPost400 | GetPost404 | GetPost500>, GetPostQueryResponse, typeof queryKey>({
         enabled: !!(postID),
         queryKey,
         queryFn: async ({ signal }) => {
            return getPost(postID, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get a post by ID
 * @summary Get a post
 * {@link /posts/:postID}
 */
export function useGetPost<TData = GetPostQueryResponse, TQueryData = GetPostQueryResponse, TQueryKey extends QueryKey = GetPostQueryKey>(postID: GetPostPathParams["postID"], options: 
{
  query?: Partial<QueryObserverOptions<GetPostQueryResponse, ResponseErrorConfig<GetPost400 | GetPost404 | GetPost500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getPostQueryKey(postID)
         

         const query = useQuery({
          ...getPostQueryOptions(postID, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetPost400 | GetPost404 | GetPost500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}