/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetNotificationsQueryResponse, GetNotificationsQueryParams, GetNotifications400, GetNotifications401, GetNotifications500 } from "../models/GetNotifications.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getNotifications } from "../clients/getNotifications.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getNotificationsQueryKey = (params?: GetNotificationsQueryParams) => [{ url: '/notifications' }, ...(params ? [params] : [])] as const

export type GetNotificationsQueryKey = ReturnType<typeof getNotificationsQueryKey>

export function getNotificationsQueryOptions(params?: GetNotificationsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getNotificationsQueryKey(params)
        return queryOptions<GetNotificationsQueryResponse, ResponseErrorConfig<GetNotifications400 | GetNotifications401 | GetNotifications500>, GetNotificationsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getNotifications(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get a cursor-paginated list of notifications for the authenticated user
 * @summary Get notifications
 * {@link /notifications}
 */
export function useGetNotifications<TData = GetNotificationsQueryResponse, TQueryData = GetNotificationsQueryResponse, TQueryKey extends QueryKey = GetNotificationsQueryKey>(params?: GetNotificationsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetNotificationsQueryResponse, ResponseErrorConfig<GetNotifications400 | GetNotifications401 | GetNotifications500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getNotificationsQueryKey(params)
         

         const query = useQuery({
          ...getNotificationsQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetNotifications400 | GetNotifications401 | GetNotifications500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}