/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetMeQueryResponse, GetMe401, GetMe404, GetMe500 } from "../models/GetMe.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getMe } from "../clients/getMe.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getMeQueryKey = () => [{ url: '/auth/me' }] as const

export type GetMeQueryKey = ReturnType<typeof getMeQueryKey>

export function getMeQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getMeQueryKey()
        return queryOptions<GetMeQueryResponse, ResponseErrorConfig<GetMe401 | GetMe404 | GetMe500>, GetMeQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getMe({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get the authenticated user's information
 * @summary Get current user
 * {@link /auth/me}
 */
export function useGetMe<TData = GetMeQueryResponse, TQueryData = GetMeQueryResponse, TQueryKey extends QueryKey = GetMeQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetMeQueryResponse, ResponseErrorConfig<GetMe401 | GetMe404 | GetMe500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getMeQueryKey()
         

         const query = useQuery({
          ...getMeQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetMe401 | GetMe404 | GetMe500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}