/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetNotificationsQueryResponse, GetNotificationsQueryParams, GetNotifications400, GetNotifications401, GetNotifications500 } from "../models/GetNotifications.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getNotifications } from "../clients/getNotifications.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getNotificationsSuspenseQueryKey = (params?: GetNotificationsQueryParams) => [{ url: '/notifications' }, ...(params ? [params] : [])] as const

export type GetNotificationsSuspenseQueryKey = ReturnType<typeof getNotificationsSuspenseQueryKey>

export function getNotificationsSuspenseQueryOptions(params?: GetNotificationsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getNotificationsSuspenseQueryKey(params)
        return queryOptions<GetNotificationsQueryResponse, ResponseErrorConfig<GetNotifications400 | GetNotifications401 | GetNotifications500>, GetNotificationsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getNotifications(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get a cursor-paginated list of notifications for the authenticated user
 * @summary Get notifications
 * {@link /notifications}
 */
export function useGetNotificationsSuspense<TData = GetNotificationsQueryResponse, TQueryKey extends QueryKey = GetNotificationsSuspenseQueryKey>(params?: GetNotificationsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetNotificationsQueryResponse, ResponseErrorConfig<GetNotifications400 | GetNotifications401 | GetNotifications500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getNotificationsSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getNotificationsSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetNotifications400 | GetNotifications401 | GetNotifications500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}