/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetUserQueryResponse, GetUserPathParams, GetUserQueryParams, GetUser400, GetUser404, GetUser500 } from "../models/GetUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getUser } from "../clients/getUser.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getUserQueryKey = (userKey: GetUserPathParams["userKey"], params?: GetUserQueryParams) => [{ url: '/users/:userKey', params: {userKey:userKey} }, ...(params ? [params] : [])] as const

export type GetUserQueryKey = ReturnType<typeof getUserQueryKey>

export function getUserQueryOptions(userKey: GetUserPathParams["userKey"], params?: GetUserQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getUserQueryKey(userKey, params)
        return queryOptions<GetUserQueryResponse, ResponseErrorConfig<GetUser400 | GetUser404 | GetUser500>, GetUserQueryResponse, typeof queryKey>({
         enabled: !!(userKey),
         queryKey,
         queryFn: async ({ signal }) => {
            return getUser(userKey, params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Retrieve a user's information by UUID or username (with ?by=username)
 * @summary Get user by ID or username
 * {@link /users/:userKey}
 */
export function useGetUser<TData = GetUserQueryResponse, TQueryData = GetUserQueryResponse, TQueryKey extends QueryKey = GetUserQueryKey>(userKey: GetUserPathParams["userKey"], params?: GetUserQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetUserQueryResponse, ResponseErrorConfig<GetUser400 | GetUser404 | GetUser500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getUserQueryKey(userKey, params)
         

         const query = useQuery({
          ...getUserQueryOptions(userKey, params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetUser400 | GetUser404 | GetUser500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}