/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetPostQueryResponse, GetPostPathParams, GetPost400, GetPost404, GetPost500 } from "../models/GetPost.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getPost } from "../clients/getPost.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getPostSuspenseQueryKey = (postID: GetPostPathParams["postID"]) => [{ url: '/posts/:postID', params: {postID:postID} }] as const

export type GetPostSuspenseQueryKey = ReturnType<typeof getPostSuspenseQueryKey>

export function getPostSuspenseQueryOptions(postID: GetPostPathParams["postID"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getPostSuspenseQueryKey(postID)
        return queryOptions<GetPostQueryResponse, ResponseErrorConfig<GetPost400 | GetPost404 | GetPost500>, GetPostQueryResponse, typeof queryKey>({
         enabled: !!(postID),
         queryKey,
         queryFn: async ({ signal }) => {
            return getPost(postID, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get a post by ID
 * @summary Get a post
 * {@link /posts/:postID}
 */
export function useGetPostSuspense<TData = GetPostQueryResponse, TQueryKey extends QueryKey = GetPostSuspenseQueryKey>(postID: GetPostPathParams["postID"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetPostQueryResponse, ResponseErrorConfig<GetPost400 | GetPost404 | GetPost500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getPostSuspenseQueryKey(postID)
         

         const query = useSuspenseQuery({
          ...getPostSuspenseQueryOptions(postID, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetPost400 | GetPost404 | GetPost500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}