/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetPostsByHashtagQueryResponse, GetPostsByHashtagPathParams, GetPostsByHashtagQueryParams, GetPostsByHashtag400, GetPostsByHashtag500 } from "../models/GetPostsByHashtag.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getPostsByHashtag } from "../clients/getPostsByHashtag.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getPostsByHashtagQueryKey = (name: GetPostsByHashtagPathParams["name"], params?: GetPostsByHashtagQueryParams) => [{ url: '/hashtags/:name/posts', params: {name:name} }, ...(params ? [params] : [])] as const

export type GetPostsByHashtagQueryKey = ReturnType<typeof getPostsByHashtagQueryKey>

export function getPostsByHashtagQueryOptions(name: GetPostsByHashtagPathParams["name"], params?: GetPostsByHashtagQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getPostsByHashtagQueryKey(name, params)
        return queryOptions<GetPostsByHashtagQueryResponse, ResponseErrorConfig<GetPostsByHashtag400 | GetPostsByHashtag500>, GetPostsByHashtagQueryResponse, typeof queryKey>({
         enabled: !!(name),
         queryKey,
         queryFn: async ({ signal }) => {
            return getPostsByHashtag(name, params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns cursor-paginated public posts for a hashtag
 * @summary Posts by hashtag
 * {@link /hashtags/:name/posts}
 */
export function useGetPostsByHashtag<TData = GetPostsByHashtagQueryResponse, TQueryData = GetPostsByHashtagQueryResponse, TQueryKey extends QueryKey = GetPostsByHashtagQueryKey>(name: GetPostsByHashtagPathParams["name"], params?: GetPostsByHashtagQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetPostsByHashtagQueryResponse, ResponseErrorConfig<GetPostsByHashtag400 | GetPostsByHashtag500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getPostsByHashtagQueryKey(name, params)
         

         const query = useQuery({
          ...getPostsByHashtagQueryOptions(name, params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetPostsByHashtag400 | GetPostsByHashtag500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}