/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetDiscoverQueryResponse, GetDiscoverQueryParams, GetDiscover400, GetDiscover500 } from "../models/GetDiscover.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getDiscover } from "../clients/getDiscover.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getDiscoverQueryKey = (params?: GetDiscoverQueryParams) => [{ url: '/discover' }, ...(params ? [params] : [])] as const

export type GetDiscoverQueryKey = ReturnType<typeof getDiscoverQueryKey>

export function getDiscoverQueryOptions(params?: GetDiscoverQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getDiscoverQueryKey(params)
        return queryOptions<GetDiscoverQueryResponse, ResponseErrorConfig<GetDiscover400 | GetDiscover500>, GetDiscoverQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getDiscover(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get a cursor-paginated discovery feed of public posts. No authentication required; if a valid token is provided, is_liked is populated.
 * @summary Discover posts
 * {@link /discover}
 */
export function useGetDiscover<TData = GetDiscoverQueryResponse, TQueryData = GetDiscoverQueryResponse, TQueryKey extends QueryKey = GetDiscoverQueryKey>(params?: GetDiscoverQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetDiscoverQueryResponse, ResponseErrorConfig<GetDiscover400 | GetDiscover500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getDiscoverQueryKey(params)
         

         const query = useQuery({
          ...getDiscoverQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetDiscover400 | GetDiscover500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}