/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetUserProfileQueryResponse, GetUserProfilePathParams, GetUserProfileQueryParams, GetUserProfile400, GetUserProfile404, GetUserProfile500 } from "../models/GetUserProfile.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getUserProfile } from "../clients/getUserProfile.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getUserProfileSuspenseQueryKey = (userKey: GetUserProfilePathParams["userKey"], params?: GetUserProfileQueryParams) => [{ url: '/users/:userKey/profile', params: {userKey:userKey} }, ...(params ? [params] : [])] as const

export type GetUserProfileSuspenseQueryKey = ReturnType<typeof getUserProfileSuspenseQueryKey>

export function getUserProfileSuspenseQueryOptions(userKey: GetUserProfilePathParams["userKey"], params?: GetUserProfileQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getUserProfileSuspenseQueryKey(userKey, params)
        return queryOptions<GetUserProfileQueryResponse, ResponseErrorConfig<GetUserProfile400 | GetUserProfile404 | GetUserProfile500>, GetUserProfileQueryResponse, typeof queryKey>({
         enabled: !!(userKey),
         queryKey,
         queryFn: async ({ signal }) => {
            return getUserProfile(userKey, params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get a user's public social profile by UUID or username (with ?by=username). Optionally enriches is_following when the viewer is authenticated.
 * @summary Get user profile
 * {@link /users/:userKey/profile}
 */
export function useGetUserProfileSuspense<TData = GetUserProfileQueryResponse, TQueryKey extends QueryKey = GetUserProfileSuspenseQueryKey>(userKey: GetUserProfilePathParams["userKey"], params?: GetUserProfileQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetUserProfileQueryResponse, ResponseErrorConfig<GetUserProfile400 | GetUserProfile404 | GetUserProfile500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getUserProfileSuspenseQueryKey(userKey, params)
         

         const query = useSuspenseQuery({
          ...getUserProfileSuspenseQueryOptions(userKey, params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetUserProfile400 | GetUserProfile404 | GetUserProfile500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}