/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetMyProfileQueryResponse, GetMyProfile401, GetMyProfile404, GetMyProfile500 } from "../models/GetMyProfile.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getMyProfile } from "../clients/getMyProfile.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMyProfileSuspenseQueryKey = () => [{ url: '/me' }] as const

export type GetMyProfileSuspenseQueryKey = ReturnType<typeof getMyProfileSuspenseQueryKey>

export function getMyProfileSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getMyProfileSuspenseQueryKey()
        return queryOptions<GetMyProfileQueryResponse, ResponseErrorConfig<GetMyProfile401 | GetMyProfile404 | GetMyProfile500>, GetMyProfileQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getMyProfile({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get the authenticated user's social profile
 * @summary Get my profile
 * {@link /me}
 */
export function useGetMyProfileSuspense<TData = GetMyProfileQueryResponse, TQueryKey extends QueryKey = GetMyProfileSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetMyProfileQueryResponse, ResponseErrorConfig<GetMyProfile401 | GetMyProfile404 | GetMyProfile500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getMyProfileSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getMyProfileSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetMyProfile401 | GetMyProfile404 | GetMyProfile500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}