/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetCommentsQueryResponse, GetCommentsPathParams, GetCommentsQueryParams, GetComments400, GetComments404, GetComments500 } from "../models/GetComments.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getComments } from "../clients/getComments.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getCommentsSuspenseQueryKey = (postID: GetCommentsPathParams["postID"], params?: GetCommentsQueryParams) => [{ url: '/posts/:postID/comments', params: {postID:postID} }, ...(params ? [params] : [])] as const

export type GetCommentsSuspenseQueryKey = ReturnType<typeof getCommentsSuspenseQueryKey>

export function getCommentsSuspenseQueryOptions(postID: GetCommentsPathParams["postID"], params?: GetCommentsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getCommentsSuspenseQueryKey(postID, params)
        return queryOptions<GetCommentsQueryResponse, ResponseErrorConfig<GetComments400 | GetComments404 | GetComments500>, GetCommentsQueryResponse, typeof queryKey>({
         enabled: !!(postID),
         queryKey,
         queryFn: async ({ signal }) => {
            return getComments(postID, params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get a paginated list of top-level comments for a post
 * @summary Get comments
 * {@link /posts/:postID/comments}
 */
export function useGetCommentsSuspense<TData = GetCommentsQueryResponse, TQueryKey extends QueryKey = GetCommentsSuspenseQueryKey>(postID: GetCommentsPathParams["postID"], params?: GetCommentsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetCommentsQueryResponse, ResponseErrorConfig<GetComments400 | GetComments404 | GetComments500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getCommentsSuspenseQueryKey(postID, params)
         

         const query = useSuspenseQuery({
          ...getCommentsSuspenseQueryOptions(postID, params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetComments400 | GetComments404 | GetComments500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}