/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetUnreadCountQueryResponse, GetUnreadCount401, GetUnreadCount500 } from "../models/GetUnreadCount.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getUnreadCount } from "../clients/getUnreadCount.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getUnreadCountSuspenseQueryKey = () => [{ url: '/notifications/unread-count' }] as const

export type GetUnreadCountSuspenseQueryKey = ReturnType<typeof getUnreadCountSuspenseQueryKey>

export function getUnreadCountSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getUnreadCountSuspenseQueryKey()
        return queryOptions<GetUnreadCountQueryResponse, ResponseErrorConfig<GetUnreadCount401 | GetUnreadCount500>, GetUnreadCountQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getUnreadCount({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get the number of unread notifications for the authenticated user
 * @summary Get unread notification count
 * {@link /notifications/unread-count}
 */
export function useGetUnreadCountSuspense<TData = GetUnreadCountQueryResponse, TQueryKey extends QueryKey = GetUnreadCountSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetUnreadCountQueryResponse, ResponseErrorConfig<GetUnreadCount401 | GetUnreadCount500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getUnreadCountSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getUnreadCountSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetUnreadCount401 | GetUnreadCount500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}