/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetDiscoverQueryResponse, GetDiscoverQueryParams, GetDiscover400, GetDiscover500 } from "../models/GetDiscover.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getDiscover } from "../clients/getDiscover.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getDiscoverSuspenseQueryKey = (params?: GetDiscoverQueryParams) => [{ url: '/discover' }, ...(params ? [params] : [])] as const

export type GetDiscoverSuspenseQueryKey = ReturnType<typeof getDiscoverSuspenseQueryKey>

export function getDiscoverSuspenseQueryOptions(params?: GetDiscoverQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getDiscoverSuspenseQueryKey(params)
        return queryOptions<GetDiscoverQueryResponse, ResponseErrorConfig<GetDiscover400 | GetDiscover500>, GetDiscoverQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getDiscover(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get a cursor-paginated discovery feed of public posts. No authentication required; if a valid token is provided, is_liked is populated.
 * @summary Discover posts
 * {@link /discover}
 */
export function useGetDiscoverSuspense<TData = GetDiscoverQueryResponse, TQueryKey extends QueryKey = GetDiscoverSuspenseQueryKey>(params?: GetDiscoverQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetDiscoverQueryResponse, ResponseErrorConfig<GetDiscover400 | GetDiscover500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getDiscoverSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getDiscoverSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetDiscover400 | GetDiscover500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}