/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetUserPostsQueryResponse, GetUserPostsPathParams, GetUserPostsQueryParams, GetUserPosts400, GetUserPosts500 } from "../models/GetUserPosts.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getUserPosts } from "../clients/getUserPosts.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getUserPostsQueryKey = (userID: GetUserPostsPathParams["userID"], params?: GetUserPostsQueryParams) => [{ url: '/users/:userID/posts', params: {userID:userID} }, ...(params ? [params] : [])] as const

export type GetUserPostsQueryKey = ReturnType<typeof getUserPostsQueryKey>

export function getUserPostsQueryOptions(userID: GetUserPostsPathParams["userID"], params?: GetUserPostsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getUserPostsQueryKey(userID, params)
        return queryOptions<GetUserPostsQueryResponse, ResponseErrorConfig<GetUserPosts400 | GetUserPosts500>, GetUserPostsQueryResponse, typeof queryKey>({
         enabled: !!(userID),
         queryKey,
         queryFn: async ({ signal }) => {
            return getUserPosts(userID, params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get a cursor-paginated list of posts by a specific user
 * @summary Get user posts
 * {@link /users/:userID/posts}
 */
export function useGetUserPosts<TData = GetUserPostsQueryResponse, TQueryData = GetUserPostsQueryResponse, TQueryKey extends QueryKey = GetUserPostsQueryKey>(userID: GetUserPostsPathParams["userID"], params?: GetUserPostsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetUserPostsQueryResponse, ResponseErrorConfig<GetUserPosts400 | GetUserPosts500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getUserPostsQueryKey(userID, params)
         

         const query = useQuery({
          ...getUserPostsQueryOptions(userID, params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetUserPosts400 | GetUserPosts500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}