/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetTrendingHashtagsQueryResponse, GetTrendingHashtags500 } from "../models/GetTrendingHashtags.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getTrendingHashtags } from "../clients/getTrendingHashtags.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getTrendingHashtagsSuspenseQueryKey = () => [{ url: '/hashtags/trending' }] as const

export type GetTrendingHashtagsSuspenseQueryKey = ReturnType<typeof getTrendingHashtagsSuspenseQueryKey>

export function getTrendingHashtagsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getTrendingHashtagsSuspenseQueryKey()
        return queryOptions<GetTrendingHashtagsQueryResponse, ResponseErrorConfig<GetTrendingHashtags500>, GetTrendingHashtagsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getTrendingHashtags({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns the top trending hashtags based on post usage in the last 24 hours
 * @summary Trending hashtags
 * {@link /hashtags/trending}
 */
export function useGetTrendingHashtagsSuspense<TData = GetTrendingHashtagsQueryResponse, TQueryKey extends QueryKey = GetTrendingHashtagsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetTrendingHashtagsQueryResponse, ResponseErrorConfig<GetTrendingHashtags500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getTrendingHashtagsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getTrendingHashtagsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetTrendingHashtags500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}