/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetFollowingQueryResponse, GetFollowingPathParams, GetFollowingQueryParams, GetFollowing400, GetFollowing500 } from "../models/GetFollowing.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getFollowing } from "../clients/getFollowing.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getFollowingSuspenseQueryKey = (userKey: GetFollowingPathParams["userKey"], params?: GetFollowingQueryParams) => [{ url: '/users/:userKey/following', params: {userKey:userKey} }, ...(params ? [params] : [])] as const

export type GetFollowingSuspenseQueryKey = ReturnType<typeof getFollowingSuspenseQueryKey>

export function getFollowingSuspenseQueryOptions(userKey: GetFollowingPathParams["userKey"], params?: GetFollowingQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getFollowingSuspenseQueryKey(userKey, params)
        return queryOptions<GetFollowingQueryResponse, ResponseErrorConfig<GetFollowing400 | GetFollowing500>, GetFollowingQueryResponse, typeof queryKey>({
         enabled: !!(userKey),
         queryKey,
         queryFn: async ({ signal }) => {
            return getFollowing(userKey, params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get a paginated list of users that the specified user follows by UUID or username (with ?by=username)
 * @summary Get following
 * {@link /users/:userKey/following}
 */
export function useGetFollowingSuspense<TData = GetFollowingQueryResponse, TQueryKey extends QueryKey = GetFollowingSuspenseQueryKey>(userKey: GetFollowingPathParams["userKey"], params?: GetFollowingQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetFollowingQueryResponse, ResponseErrorConfig<GetFollowing400 | GetFollowing500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getFollowingSuspenseQueryKey(userKey, params)
         

         const query = useSuspenseQuery({
          ...getFollowingSuspenseQueryOptions(userKey, params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetFollowing400 | GetFollowing500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}