/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetFollowersQueryResponse, GetFollowersPathParams, GetFollowersQueryParams, GetFollowers400, GetFollowers500 } from "../models/GetFollowers.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getFollowers } from "../clients/getFollowers.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getFollowersSuspenseQueryKey = (userKey: GetFollowersPathParams["userKey"], params?: GetFollowersQueryParams) => [{ url: '/users/:userKey/followers', params: {userKey:userKey} }, ...(params ? [params] : [])] as const

export type GetFollowersSuspenseQueryKey = ReturnType<typeof getFollowersSuspenseQueryKey>

export function getFollowersSuspenseQueryOptions(userKey: GetFollowersPathParams["userKey"], params?: GetFollowersQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getFollowersSuspenseQueryKey(userKey, params)
        return queryOptions<GetFollowersQueryResponse, ResponseErrorConfig<GetFollowers400 | GetFollowers500>, GetFollowersQueryResponse, typeof queryKey>({
         enabled: !!(userKey),
         queryKey,
         queryFn: async ({ signal }) => {
            return getFollowers(userKey, params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get a paginated list of users who follow the specified user by UUID or username (with ?by=username)
 * @summary Get followers
 * {@link /users/:userKey/followers}
 */
export function useGetFollowersSuspense<TData = GetFollowersQueryResponse, TQueryKey extends QueryKey = GetFollowersSuspenseQueryKey>(userKey: GetFollowersPathParams["userKey"], params?: GetFollowersQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetFollowersQueryResponse, ResponseErrorConfig<GetFollowers400 | GetFollowers500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getFollowersSuspenseQueryKey(userKey, params)
         

         const query = useSuspenseQuery({
          ...getFollowersSuspenseQueryOptions(userKey, params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetFollowers400 | GetFollowers500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}