/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetMyProfileQueryResponse, GetMyProfile401, GetMyProfile404, GetMyProfile500 } from "../models/GetMyProfile.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getMyProfile } from "../clients/getMyProfile.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getMyProfileQueryKey = () => [{ url: '/me' }] as const

export type GetMyProfileQueryKey = ReturnType<typeof getMyProfileQueryKey>

export function getMyProfileQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getMyProfileQueryKey()
        return queryOptions<GetMyProfileQueryResponse, ResponseErrorConfig<GetMyProfile401 | GetMyProfile404 | GetMyProfile500>, GetMyProfileQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getMyProfile({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get the authenticated user's social profile
 * @summary Get my profile
 * {@link /me}
 */
export function useGetMyProfile<TData = GetMyProfileQueryResponse, TQueryData = GetMyProfileQueryResponse, TQueryKey extends QueryKey = GetMyProfileQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetMyProfileQueryResponse, ResponseErrorConfig<GetMyProfile401 | GetMyProfile404 | GetMyProfile500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getMyProfileQueryKey()
         

         const query = useQuery({
          ...getMyProfileQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetMyProfile401 | GetMyProfile404 | GetMyProfile500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}