/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetUnreadCountQueryResponse, GetUnreadCount401, GetUnreadCount500 } from "../models/GetUnreadCount.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getUnreadCount } from "../clients/getUnreadCount.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getUnreadCountQueryKey = () => [{ url: '/notifications/unread-count' }] as const

export type GetUnreadCountQueryKey = ReturnType<typeof getUnreadCountQueryKey>

export function getUnreadCountQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getUnreadCountQueryKey()
        return queryOptions<GetUnreadCountQueryResponse, ResponseErrorConfig<GetUnreadCount401 | GetUnreadCount500>, GetUnreadCountQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getUnreadCount({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Get the number of unread notifications for the authenticated user
 * @summary Get unread notification count
 * {@link /notifications/unread-count}
 */
export function useGetUnreadCount<TData = GetUnreadCountQueryResponse, TQueryData = GetUnreadCountQueryResponse, TQueryKey extends QueryKey = GetUnreadCountQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetUnreadCountQueryResponse, ResponseErrorConfig<GetUnreadCount401 | GetUnreadCount500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getUnreadCountQueryKey()
         

         const query = useQuery({
          ...getUnreadCountQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetUnreadCount401 | GetUnreadCount500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}