/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetTrendingHashtagsQueryResponse, GetTrendingHashtags500 } from "../models/GetTrendingHashtags.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getTrendingHashtags } from "../clients/getTrendingHashtags.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getTrendingHashtagsQueryKey = () => [{ url: '/hashtags/trending' }] as const

export type GetTrendingHashtagsQueryKey = ReturnType<typeof getTrendingHashtagsQueryKey>

export function getTrendingHashtagsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getTrendingHashtagsQueryKey()
        return queryOptions<GetTrendingHashtagsQueryResponse, ResponseErrorConfig<GetTrendingHashtags500>, GetTrendingHashtagsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getTrendingHashtags({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns the top trending hashtags based on post usage in the last 24 hours
 * @summary Trending hashtags
 * {@link /hashtags/trending}
 */
export function useGetTrendingHashtags<TData = GetTrendingHashtagsQueryResponse, TQueryData = GetTrendingHashtagsQueryResponse, TQueryKey extends QueryKey = GetTrendingHashtagsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetTrendingHashtagsQueryResponse, ResponseErrorConfig<GetTrendingHashtags500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getTrendingHashtagsQueryKey()
         

         const query = useQuery({
          ...getTrendingHashtagsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetTrendingHashtags500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}