/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { LogoutAllSessionsMutationResponse, LogoutAllSessions401, LogoutAllSessions500 } from "../models/LogoutAllSessions.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { logoutAllSessions } from "../clients/logoutAllSessions.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const logoutAllSessionsMutationKey = () => [{ url: '/auth/logout-all' }] as const

export type LogoutAllSessionsMutationKey = ReturnType<typeof logoutAllSessionsMutationKey>

export function logoutAllSessionsMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = logoutAllSessionsMutationKey()
        return mutationOptions<LogoutAllSessionsMutationResponse, ResponseErrorConfig<LogoutAllSessions401 | LogoutAllSessions500>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return logoutAllSessions(config)
          },
        })

}

/**
 * @description Revoke all refresh tokens for the authenticated user
 * @summary Logout all sessions
 * {@link /auth/logout-all}
 */
export function useLogoutAllSessions<TContext>(options: 
{
  mutation?: UseMutationOptions<LogoutAllSessionsMutationResponse, ResponseErrorConfig<LogoutAllSessions401 | LogoutAllSessions500>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? logoutAllSessionsMutationKey()

          const baseOptions = logoutAllSessionsMutationOptions(config) as UseMutationOptions<LogoutAllSessionsMutationResponse, ResponseErrorConfig<LogoutAllSessions401 | LogoutAllSessions500>, void, TContext>
          

          return useMutation<LogoutAllSessionsMutationResponse, ResponseErrorConfig<LogoutAllSessions401 | LogoutAllSessions500>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<LogoutAllSessionsMutationResponse, ResponseErrorConfig<LogoutAllSessions401 | LogoutAllSessions500>, void, TContext>
      
}