/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { LogoutMutationRequest, LogoutMutationResponse, LogoutHeaderParams, Logout400, Logout401, Logout500 } from "../models/Logout.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { logout } from "../clients/logout.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const logoutMutationKey = () => [{ url: '/auth/logout' }] as const

export type LogoutMutationKey = ReturnType<typeof logoutMutationKey>

export function logoutMutationOptions<TContext = unknown>(config: Partial<RequestConfig<LogoutMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = logoutMutationKey()
        return mutationOptions<LogoutMutationResponse, ResponseErrorConfig<Logout400 | Logout401 | Logout500>, {data?: LogoutMutationRequest, headers?: LogoutHeaderParams}, TContext>({
          mutationKey,
          mutationFn: async({ data, headers }) => {
            return logout(data, headers, config)
          },
        })

}

/**
 * @description Revoke a refresh token to logout user from current session.
 * Web clients (default): refresh_token is read from the HttpOnly cookie automatically; request body is not required. Cookie is cleared on success.
 * Mobile clients (X-Client-Type: mobile): refresh_token must be provided in the request body.
 * @summary User logout
 * {@link /auth/logout}
 */
export function useLogout<TContext>(options: 
{
  mutation?: UseMutationOptions<LogoutMutationResponse, ResponseErrorConfig<Logout400 | Logout401 | Logout500>, {data?: LogoutMutationRequest, headers?: LogoutHeaderParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<LogoutMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? logoutMutationKey()

          const baseOptions = logoutMutationOptions(config) as UseMutationOptions<LogoutMutationResponse, ResponseErrorConfig<Logout400 | Logout401 | Logout500>, {data?: LogoutMutationRequest, headers?: LogoutHeaderParams}, TContext>
          

          return useMutation<LogoutMutationResponse, ResponseErrorConfig<Logout400 | Logout401 | Logout500>, {data?: LogoutMutationRequest, headers?: LogoutHeaderParams}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<LogoutMutationResponse, ResponseErrorConfig<Logout400 | Logout401 | Logout500>, {data?: LogoutMutationRequest, headers?: LogoutHeaderParams}, TContext>
      
}