/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarkAllNotificationsAsReadMutationResponse, MarkAllNotificationsAsRead401, MarkAllNotificationsAsRead500 } from "../models/MarkAllNotificationsAsRead.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { markAllNotificationsAsRead } from "../clients/markAllNotificationsAsRead.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const markAllNotificationsAsReadMutationKey = () => [{ url: '/notifications/read-all' }] as const

export type MarkAllNotificationsAsReadMutationKey = ReturnType<typeof markAllNotificationsAsReadMutationKey>

export function markAllNotificationsAsReadMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = markAllNotificationsAsReadMutationKey()
        return mutationOptions<MarkAllNotificationsAsReadMutationResponse, ResponseErrorConfig<MarkAllNotificationsAsRead401 | MarkAllNotificationsAsRead500>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return markAllNotificationsAsRead(config)
          },
        })

}

/**
 * @description Mark all notifications as read for the authenticated user
 * @summary Mark all notifications as read
 * {@link /notifications/read-all}
 */
export function useMarkAllNotificationsAsRead<TContext>(options: 
{
  mutation?: UseMutationOptions<MarkAllNotificationsAsReadMutationResponse, ResponseErrorConfig<MarkAllNotificationsAsRead401 | MarkAllNotificationsAsRead500>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? markAllNotificationsAsReadMutationKey()

          const baseOptions = markAllNotificationsAsReadMutationOptions(config) as UseMutationOptions<MarkAllNotificationsAsReadMutationResponse, ResponseErrorConfig<MarkAllNotificationsAsRead401 | MarkAllNotificationsAsRead500>, void, TContext>
          

          return useMutation<MarkAllNotificationsAsReadMutationResponse, ResponseErrorConfig<MarkAllNotificationsAsRead401 | MarkAllNotificationsAsRead500>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<MarkAllNotificationsAsReadMutationResponse, ResponseErrorConfig<MarkAllNotificationsAsRead401 | MarkAllNotificationsAsRead500>, void, TContext>
      
}