/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarkNotificationAsReadMutationResponse, MarkNotificationAsReadPathParams, MarkNotificationAsRead400, MarkNotificationAsRead401, MarkNotificationAsRead500 } from "../models/MarkNotificationAsRead.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { markNotificationAsRead } from "../clients/markNotificationAsRead.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const markNotificationAsReadMutationKey = () => [{ url: '/notifications/:notificationID/read' }] as const

export type MarkNotificationAsReadMutationKey = ReturnType<typeof markNotificationAsReadMutationKey>

export function markNotificationAsReadMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = markNotificationAsReadMutationKey()
        return mutationOptions<MarkNotificationAsReadMutationResponse, ResponseErrorConfig<MarkNotificationAsRead400 | MarkNotificationAsRead401 | MarkNotificationAsRead500>, {notificationID: MarkNotificationAsReadPathParams["notificationID"]}, TContext>({
          mutationKey,
          mutationFn: async({ notificationID }) => {
            return markNotificationAsRead(notificationID, config)
          },
        })

}

/**
 * @description Mark a single notification as read
 * @summary Mark notification as read
 * {@link /notifications/:notificationID/read}
 */
export function useMarkNotificationAsRead<TContext>(options: 
{
  mutation?: UseMutationOptions<MarkNotificationAsReadMutationResponse, ResponseErrorConfig<MarkNotificationAsRead400 | MarkNotificationAsRead401 | MarkNotificationAsRead500>, {notificationID: MarkNotificationAsReadPathParams["notificationID"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? markNotificationAsReadMutationKey()

          const baseOptions = markNotificationAsReadMutationOptions(config) as UseMutationOptions<MarkNotificationAsReadMutationResponse, ResponseErrorConfig<MarkNotificationAsRead400 | MarkNotificationAsRead401 | MarkNotificationAsRead500>, {notificationID: MarkNotificationAsReadPathParams["notificationID"]}, TContext>
          

          return useMutation<MarkNotificationAsReadMutationResponse, ResponseErrorConfig<MarkNotificationAsRead400 | MarkNotificationAsRead401 | MarkNotificationAsRead500>, {notificationID: MarkNotificationAsReadPathParams["notificationID"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<MarkNotificationAsReadMutationResponse, ResponseErrorConfig<MarkNotificationAsRead400 | MarkNotificationAsRead401 | MarkNotificationAsRead500>, {notificationID: MarkNotificationAsReadPathParams["notificationID"]}, TContext>
      
}