/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RegisterMutationRequest, RegisterMutationResponse, RegisterHeaderParams, Register400, Register409, Register500 } from "../models/Register.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { register } from "../clients/register.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const registerMutationKey = () => [{ url: '/auth/register' }] as const

export type RegisterMutationKey = ReturnType<typeof registerMutationKey>

export function registerMutationOptions<TContext = unknown>(config: Partial<RequestConfig<RegisterMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = registerMutationKey()
        return mutationOptions<RegisterMutationResponse, ResponseErrorConfig<Register400 | Register409 | Register500>, {data: RegisterMutationRequest, headers?: RegisterHeaderParams}, TContext>({
          mutationKey,
          mutationFn: async({ data, headers }) => {
            return register(data, headers, config)
          },
        })

}

/**
 * @description Create a new user account and return tokens (user is immediately logged in).
 * Web clients (default): refresh_token is set as an HttpOnly cookie; omitted from response body.
 * Mobile clients (X-Client-Type: mobile): refresh_token is returned in the response body.
 * @summary Register a new account
 * {@link /auth/register}
 */
export function useRegister<TContext>(options: 
{
  mutation?: UseMutationOptions<RegisterMutationResponse, ResponseErrorConfig<Register400 | Register409 | Register500>, {data: RegisterMutationRequest, headers?: RegisterHeaderParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<RegisterMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? registerMutationKey()

          const baseOptions = registerMutationOptions(config) as UseMutationOptions<RegisterMutationResponse, ResponseErrorConfig<Register400 | Register409 | Register500>, {data: RegisterMutationRequest, headers?: RegisterHeaderParams}, TContext>
          

          return useMutation<RegisterMutationResponse, ResponseErrorConfig<Register400 | Register409 | Register500>, {data: RegisterMutationRequest, headers?: RegisterHeaderParams}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<RegisterMutationResponse, ResponseErrorConfig<Register400 | Register409 | Register500>, {data: RegisterMutationRequest, headers?: RegisterHeaderParams}, TContext>
      
}