/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResendWebhookMutationResponse, ResendWebhook400, ResendWebhook401, ResendWebhook500 } from "../models/ResendWebhook.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { resendWebhook } from "../clients/resendWebhook.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const resendWebhookMutationKey = () => [{ url: '/webhooks/resend' }] as const

export type ResendWebhookMutationKey = ReturnType<typeof resendWebhookMutationKey>

export function resendWebhookMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = resendWebhookMutationKey()
        return mutationOptions<ResendWebhookMutationResponse, ResponseErrorConfig<ResendWebhook400 | ResendWebhook401 | ResendWebhook500>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return resendWebhook(config)
          },
        })

}

/**
 * @description Receives Resend delivery events (delivered, bounced, complained) and updates the email delivery log. Authenticated by the Svix signature headers, not by a bearer token. Only registered when RESEND_WEBHOOK_SECRET is configured.
 * @summary Resend delivery webhook
 * {@link /webhooks/resend}
 */
export function useResendWebhook<TContext>(options: 
{
  mutation?: UseMutationOptions<ResendWebhookMutationResponse, ResponseErrorConfig<ResendWebhook400 | ResendWebhook401 | ResendWebhook500>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? resendWebhookMutationKey()

          const baseOptions = resendWebhookMutationOptions(config) as UseMutationOptions<ResendWebhookMutationResponse, ResponseErrorConfig<ResendWebhook400 | ResendWebhook401 | ResendWebhook500>, void, TContext>
          

          return useMutation<ResendWebhookMutationResponse, ResponseErrorConfig<ResendWebhook400 | ResendWebhook401 | ResendWebhook500>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ResendWebhookMutationResponse, ResponseErrorConfig<ResendWebhook400 | ResendWebhook401 | ResendWebhook500>, void, TContext>
      
}