/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RefreshTokenMutationRequest, RefreshTokenMutationResponse, RefreshTokenHeaderParams, RefreshToken400, RefreshToken401, RefreshToken500 } from "../models/RefreshToken.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { refreshToken } from "../clients/refreshToken.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const refreshTokenMutationKey = () => [{ url: '/auth/refresh' }] as const

export type RefreshTokenMutationKey = ReturnType<typeof refreshTokenMutationKey>

export function refreshTokenMutationOptions<TContext = unknown>(config: Partial<RequestConfig<RefreshTokenMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = refreshTokenMutationKey()
        return mutationOptions<RefreshTokenMutationResponse, ResponseErrorConfig<RefreshToken400 | RefreshToken401 | RefreshToken500>, {data?: RefreshTokenMutationRequest, headers?: RefreshTokenHeaderParams}, TContext>({
          mutationKey,
          mutationFn: async({ data, headers }) => {
            return refreshToken(data, headers, config)
          },
        })

}

/**
 * @description Exchange a valid refresh token for a new access token and refresh token.
 * Web clients (default): refresh_token is read from the HttpOnly cookie automatically; request body is not required.
 * Mobile clients (X-Client-Type: mobile): refresh_token must be provided in the request body.
 * @summary Refresh access token
 * {@link /auth/refresh}
 */
export function useRefreshToken<TContext>(options: 
{
  mutation?: UseMutationOptions<RefreshTokenMutationResponse, ResponseErrorConfig<RefreshToken400 | RefreshToken401 | RefreshToken500>, {data?: RefreshTokenMutationRequest, headers?: RefreshTokenHeaderParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<RefreshTokenMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? refreshTokenMutationKey()

          const baseOptions = refreshTokenMutationOptions(config) as UseMutationOptions<RefreshTokenMutationResponse, ResponseErrorConfig<RefreshToken400 | RefreshToken401 | RefreshToken500>, {data?: RefreshTokenMutationRequest, headers?: RefreshTokenHeaderParams}, TContext>
          

          return useMutation<RefreshTokenMutationResponse, ResponseErrorConfig<RefreshToken400 | RefreshToken401 | RefreshToken500>, {data?: RefreshTokenMutationRequest, headers?: RefreshTokenHeaderParams}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<RefreshTokenMutationResponse, ResponseErrorConfig<RefreshToken400 | RefreshToken401 | RefreshToken500>, {data?: RefreshTokenMutationRequest, headers?: RefreshTokenHeaderParams}, TContext>
      
}