/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResendVerificationMutationRequest, ResendVerificationMutationResponse, ResendVerification400, ResendVerification500 } from "../models/ResendVerification.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { resendVerification } from "../clients/resendVerification.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const resendVerificationMutationKey = () => [{ url: '/auth/resend-verification' }] as const

export type ResendVerificationMutationKey = ReturnType<typeof resendVerificationMutationKey>

export function resendVerificationMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ResendVerificationMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = resendVerificationMutationKey()
        return mutationOptions<ResendVerificationMutationResponse, ResponseErrorConfig<ResendVerification400 | ResendVerification500>, {data: ResendVerificationMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return resendVerification(data, config)
          },
        })

}

/**
 * @description Resend the email verification link to the specified email address
 * @summary Resend verification email
 * {@link /auth/resend-verification}
 */
export function useResendVerification<TContext>(options: 
{
  mutation?: UseMutationOptions<ResendVerificationMutationResponse, ResponseErrorConfig<ResendVerification400 | ResendVerification500>, {data: ResendVerificationMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ResendVerificationMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? resendVerificationMutationKey()

          const baseOptions = resendVerificationMutationOptions(config) as UseMutationOptions<ResendVerificationMutationResponse, ResponseErrorConfig<ResendVerification400 | ResendVerification500>, {data: ResendVerificationMutationRequest}, TContext>
          

          return useMutation<ResendVerificationMutationResponse, ResponseErrorConfig<ResendVerification400 | ResendVerification500>, {data: ResendVerificationMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ResendVerificationMutationResponse, ResponseErrorConfig<ResendVerification400 | ResendVerification500>, {data: ResendVerificationMutationRequest}, TContext>
      
}