/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SearchQueryResponse, SearchQueryParams, Search400, Search500 } from "../models/Search.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { search } from "../clients/search.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const searchSuspenseQueryKey = (params: SearchQueryParams) => [{ url: '/search' }, ...(params ? [params] : [])] as const

export type SearchSuspenseQueryKey = ReturnType<typeof searchSuspenseQueryKey>

export function searchSuspenseQueryOptions(params: SearchQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = searchSuspenseQueryKey(params)
        return queryOptions<SearchQueryResponse, ResponseErrorConfig<Search400 | Search500>, SearchQueryResponse, typeof queryKey>({
         enabled: !!(params),
         queryKey,
         queryFn: async ({ signal }) => {
            return search(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Search across users, posts, and hashtags in a single request.
 * Use type=all (default) to fetch top results from every category,
 * or specify type=users|posts|hashtags for a focused search.
 * @summary Unified search
 * {@link /search}
 */
export function useSearchSuspense<TData = SearchQueryResponse, TQueryKey extends QueryKey = SearchSuspenseQueryKey>(params: SearchQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<SearchQueryResponse, ResponseErrorConfig<Search400 | Search500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? searchSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...searchSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Search400 | Search500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}