/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SearchQueryResponse, SearchQueryParams, Search400, Search500 } from "../models/Search.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { search } from "../clients/search.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const searchQueryKey = (params: SearchQueryParams) => [{ url: '/search' }, ...(params ? [params] : [])] as const

export type SearchQueryKey = ReturnType<typeof searchQueryKey>

export function searchQueryOptions(params: SearchQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = searchQueryKey(params)
        return queryOptions<SearchQueryResponse, ResponseErrorConfig<Search400 | Search500>, SearchQueryResponse, typeof queryKey>({
         enabled: !!(params),
         queryKey,
         queryFn: async ({ signal }) => {
            return search(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Search across users, posts, and hashtags in a single request.
 * Use type=all (default) to fetch top results from every category,
 * or specify type=users|posts|hashtags for a focused search.
 * @summary Unified search
 * {@link /search}
 */
export function useSearch<TData = SearchQueryResponse, TQueryData = SearchQueryResponse, TQueryKey extends QueryKey = SearchQueryKey>(params: SearchQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<SearchQueryResponse, ResponseErrorConfig<Search400 | Search500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? searchQueryKey(params)
         

         const query = useQuery({
          ...searchQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Search400 | Search500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}