/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SearchHashtagsQueryResponse, SearchHashtagsQueryParams, SearchHashtags400, SearchHashtags429, SearchHashtags500 } from "../models/SearchHashtags.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { searchHashtags } from "../clients/searchHashtags.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const searchHashtagsQueryKey = (params: SearchHashtagsQueryParams) => [{ url: '/hashtags/search' }, ...(params ? [params] : [])] as const

export type SearchHashtagsQueryKey = ReturnType<typeof searchHashtagsQueryKey>

export function searchHashtagsQueryOptions(params: SearchHashtagsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = searchHashtagsQueryKey(params)
        return queryOptions<SearchHashtagsQueryResponse, ResponseErrorConfig<SearchHashtags400 | SearchHashtags429 | SearchHashtags500>, SearchHashtagsQueryResponse, typeof queryKey>({
         enabled: !!(params),
         queryKey,
         queryFn: async ({ signal }) => {
            return searchHashtags(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns up to 10 hashtag names that start with the given prefix (min 2 chars). Results cached 2 minutes.
 * @summary Search hashtags by prefix
 * {@link /hashtags/search}
 */
export function useSearchHashtags<TData = SearchHashtagsQueryResponse, TQueryData = SearchHashtagsQueryResponse, TQueryKey extends QueryKey = SearchHashtagsQueryKey>(params: SearchHashtagsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<SearchHashtagsQueryResponse, ResponseErrorConfig<SearchHashtags400 | SearchHashtags429 | SearchHashtags500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? searchHashtagsQueryKey(params)
         

         const query = useQuery({
          ...searchHashtagsQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<SearchHashtags400 | SearchHashtags429 | SearchHashtags500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}