/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ToggleLikeMutationResponse, ToggleLikePathParams, ToggleLike400, ToggleLike401, ToggleLike404, ToggleLike500 } from "../models/ToggleLike.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { toggleLike } from "../clients/toggleLike.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const toggleLikeMutationKey = () => [{ url: '/posts/:postID/like' }] as const

export type ToggleLikeMutationKey = ReturnType<typeof toggleLikeMutationKey>

export function toggleLikeMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = toggleLikeMutationKey()
        return mutationOptions<ToggleLikeMutationResponse, ResponseErrorConfig<ToggleLike400 | ToggleLike401 | ToggleLike404 | ToggleLike500>, {postID: ToggleLikePathParams["postID"]}, TContext>({
          mutationKey,
          mutationFn: async({ postID }) => {
            return toggleLike(postID, config)
          },
        })

}

/**
 * @description Like the post if not yet liked, unlike if already liked. Returns the new like state.
 * @summary Toggle like on a post
 * {@link /posts/:postID/like}
 */
export function useToggleLike<TContext>(options: 
{
  mutation?: UseMutationOptions<ToggleLikeMutationResponse, ResponseErrorConfig<ToggleLike400 | ToggleLike401 | ToggleLike404 | ToggleLike500>, {postID: ToggleLikePathParams["postID"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? toggleLikeMutationKey()

          const baseOptions = toggleLikeMutationOptions(config) as UseMutationOptions<ToggleLikeMutationResponse, ResponseErrorConfig<ToggleLike400 | ToggleLike401 | ToggleLike404 | ToggleLike500>, {postID: ToggleLikePathParams["postID"]}, TContext>
          

          return useMutation<ToggleLikeMutationResponse, ResponseErrorConfig<ToggleLike400 | ToggleLike401 | ToggleLike404 | ToggleLike500>, {postID: ToggleLikePathParams["postID"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ToggleLikeMutationResponse, ResponseErrorConfig<ToggleLike400 | ToggleLike401 | ToggleLike404 | ToggleLike500>, {postID: ToggleLikePathParams["postID"]}, TContext>
      
}