/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ToggleCommentLikeMutationResponse, ToggleCommentLikePathParams, ToggleCommentLike400, ToggleCommentLike401, ToggleCommentLike404, ToggleCommentLike500 } from "../models/ToggleCommentLike.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { toggleCommentLike } from "../clients/toggleCommentLike.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const toggleCommentLikeMutationKey = () => [{ url: '/posts/:postID/comments/:commentID/like' }] as const

export type ToggleCommentLikeMutationKey = ReturnType<typeof toggleCommentLikeMutationKey>

export function toggleCommentLikeMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = toggleCommentLikeMutationKey()
        return mutationOptions<ToggleCommentLikeMutationResponse, ResponseErrorConfig<ToggleCommentLike400 | ToggleCommentLike401 | ToggleCommentLike404 | ToggleCommentLike500>, {postID: ToggleCommentLikePathParams["postID"], commentID: ToggleCommentLikePathParams["commentID"]}, TContext>({
          mutationKey,
          mutationFn: async({ postID, commentID }) => {
            return toggleCommentLike(postID, commentID, config)
          },
        })

}

/**
 * @description Like the comment if not yet liked, unlike if already liked. Returns the new like state.
 * @summary Toggle like on a comment
 * {@link /posts/:postID/comments/:commentID/like}
 */
export function useToggleCommentLike<TContext>(options: 
{
  mutation?: UseMutationOptions<ToggleCommentLikeMutationResponse, ResponseErrorConfig<ToggleCommentLike400 | ToggleCommentLike401 | ToggleCommentLike404 | ToggleCommentLike500>, {postID: ToggleCommentLikePathParams["postID"], commentID: ToggleCommentLikePathParams["commentID"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? toggleCommentLikeMutationKey()

          const baseOptions = toggleCommentLikeMutationOptions(config) as UseMutationOptions<ToggleCommentLikeMutationResponse, ResponseErrorConfig<ToggleCommentLike400 | ToggleCommentLike401 | ToggleCommentLike404 | ToggleCommentLike500>, {postID: ToggleCommentLikePathParams["postID"], commentID: ToggleCommentLikePathParams["commentID"]}, TContext>
          

          return useMutation<ToggleCommentLikeMutationResponse, ResponseErrorConfig<ToggleCommentLike400 | ToggleCommentLike401 | ToggleCommentLike404 | ToggleCommentLike500>, {postID: ToggleCommentLikePathParams["postID"], commentID: ToggleCommentLikePathParams["commentID"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ToggleCommentLikeMutationResponse, ResponseErrorConfig<ToggleCommentLike400 | ToggleCommentLike401 | ToggleCommentLike404 | ToggleCommentLike500>, {postID: ToggleCommentLikePathParams["postID"], commentID: ToggleCommentLikePathParams["commentID"]}, TContext>
      
}