/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UnfollowUserMutationResponse, UnfollowUserPathParams, UnfollowUserQueryParams, UnfollowUser400, UnfollowUser401, UnfollowUser500 } from "../models/UnfollowUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { unfollowUser } from "../clients/unfollowUser.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const unfollowUserMutationKey = () => [{ url: '/users/:userKey/follow' }] as const

export type UnfollowUserMutationKey = ReturnType<typeof unfollowUserMutationKey>

export function unfollowUserMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = unfollowUserMutationKey()
        return mutationOptions<UnfollowUserMutationResponse, ResponseErrorConfig<UnfollowUser400 | UnfollowUser401 | UnfollowUser500>, {userKey: UnfollowUserPathParams["userKey"], params?: UnfollowUserQueryParams}, TContext>({
          mutationKey,
          mutationFn: async({ userKey, params }) => {
            return unfollowUser(userKey, params, config)
          },
        })

}

/**
 * @description Unfollow a user by UUID or username (with ?by=username). No-op if not following.
 * @summary Unfollow a user
 * {@link /users/:userKey/follow}
 */
export function useUnfollowUser<TContext>(options: 
{
  mutation?: UseMutationOptions<UnfollowUserMutationResponse, ResponseErrorConfig<UnfollowUser400 | UnfollowUser401 | UnfollowUser500>, {userKey: UnfollowUserPathParams["userKey"], params?: UnfollowUserQueryParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? unfollowUserMutationKey()

          const baseOptions = unfollowUserMutationOptions(config) as UseMutationOptions<UnfollowUserMutationResponse, ResponseErrorConfig<UnfollowUser400 | UnfollowUser401 | UnfollowUser500>, {userKey: UnfollowUserPathParams["userKey"], params?: UnfollowUserQueryParams}, TContext>
          

          return useMutation<UnfollowUserMutationResponse, ResponseErrorConfig<UnfollowUser400 | UnfollowUser401 | UnfollowUser500>, {userKey: UnfollowUserPathParams["userKey"], params?: UnfollowUserQueryParams}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UnfollowUserMutationResponse, ResponseErrorConfig<UnfollowUser400 | UnfollowUser401 | UnfollowUser500>, {userKey: UnfollowUserPathParams["userKey"], params?: UnfollowUserQueryParams}, TContext>
      
}