/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UploadAvatarMutationRequest, UploadAvatarMutationResponse, UploadAvatar400, UploadAvatar401, UploadAvatar404, UploadAvatar500 } from "../models/UploadAvatar.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { uploadAvatar } from "../clients/uploadAvatar.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const uploadAvatarMutationKey = () => [{ url: '/me/avatar' }] as const

export type UploadAvatarMutationKey = ReturnType<typeof uploadAvatarMutationKey>

export function uploadAvatarMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UploadAvatarMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = uploadAvatarMutationKey()
        return mutationOptions<UploadAvatarMutationResponse, ResponseErrorConfig<UploadAvatar400 | UploadAvatar401 | UploadAvatar404 | UploadAvatar500>, {data: UploadAvatarMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return uploadAvatar(data, config)
          },
        })

}

/**
 * @description Upload a new avatar image for the authenticated user
 * @summary Upload avatar
 * {@link /me/avatar}
 */
export function useUploadAvatar<TContext>(options: 
{
  mutation?: UseMutationOptions<UploadAvatarMutationResponse, ResponseErrorConfig<UploadAvatar400 | UploadAvatar401 | UploadAvatar404 | UploadAvatar500>, {data: UploadAvatarMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UploadAvatarMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? uploadAvatarMutationKey()

          const baseOptions = uploadAvatarMutationOptions(config) as UseMutationOptions<UploadAvatarMutationResponse, ResponseErrorConfig<UploadAvatar400 | UploadAvatar401 | UploadAvatar404 | UploadAvatar500>, {data: UploadAvatarMutationRequest}, TContext>
          

          return useMutation<UploadAvatarMutationResponse, ResponseErrorConfig<UploadAvatar400 | UploadAvatar401 | UploadAvatar404 | UploadAvatar500>, {data: UploadAvatarMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UploadAvatarMutationResponse, ResponseErrorConfig<UploadAvatar400 | UploadAvatar401 | UploadAvatar404 | UploadAvatar500>, {data: UploadAvatarMutationRequest}, TContext>
      
}