/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateMyProfileMutationRequest, UpdateMyProfileMutationResponse, UpdateMyProfile400, UpdateMyProfile401, UpdateMyProfile404, UpdateMyProfile500 } from "../models/UpdateMyProfile.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { updateMyProfile } from "../clients/updateMyProfile.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateMyProfileMutationKey = () => [{ url: '/me' }] as const

export type UpdateMyProfileMutationKey = ReturnType<typeof updateMyProfileMutationKey>

export function updateMyProfileMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateMyProfileMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateMyProfileMutationKey()
        return mutationOptions<UpdateMyProfileMutationResponse, ResponseErrorConfig<UpdateMyProfile400 | UpdateMyProfile401 | UpdateMyProfile404 | UpdateMyProfile500>, {data: UpdateMyProfileMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return updateMyProfile(data, config)
          },
        })

}

/**
 * @description Update the authenticated user's social profile fields
 * @summary Update my profile
 * {@link /me}
 */
export function useUpdateMyProfile<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateMyProfileMutationResponse, ResponseErrorConfig<UpdateMyProfile400 | UpdateMyProfile401 | UpdateMyProfile404 | UpdateMyProfile500>, {data: UpdateMyProfileMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateMyProfileMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateMyProfileMutationKey()

          const baseOptions = updateMyProfileMutationOptions(config) as UseMutationOptions<UpdateMyProfileMutationResponse, ResponseErrorConfig<UpdateMyProfile400 | UpdateMyProfile401 | UpdateMyProfile404 | UpdateMyProfile500>, {data: UpdateMyProfileMutationRequest}, TContext>
          

          return useMutation<UpdateMyProfileMutationResponse, ResponseErrorConfig<UpdateMyProfile400 | UpdateMyProfile401 | UpdateMyProfile404 | UpdateMyProfile500>, {data: UpdateMyProfileMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateMyProfileMutationResponse, ResponseErrorConfig<UpdateMyProfile400 | UpdateMyProfile401 | UpdateMyProfile404 | UpdateMyProfile500>, {data: UpdateMyProfileMutationRequest}, TContext>
      
}