/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdatePostMutationRequest, UpdatePostMutationResponse, UpdatePostPathParams, UpdatePost400, UpdatePost401, UpdatePost403, UpdatePost404, UpdatePost500 } from "../models/UpdatePost.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { updatePost } from "../clients/updatePost.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updatePostMutationKey = () => [{ url: '/posts/:postID' }] as const

export type UpdatePostMutationKey = ReturnType<typeof updatePostMutationKey>

export function updatePostMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdatePostMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updatePostMutationKey()
        return mutationOptions<UpdatePostMutationResponse, ResponseErrorConfig<UpdatePost400 | UpdatePost401 | UpdatePost403 | UpdatePost404 | UpdatePost500>, {postID: UpdatePostPathParams["postID"], data: UpdatePostMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ postID, data }) => {
            return updatePost(postID, data, config)
          },
        })

}

/**
 * @description Update content or visibility of an owned post
 * @summary Update a post
 * {@link /posts/:postID}
 */
export function useUpdatePost<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdatePostMutationResponse, ResponseErrorConfig<UpdatePost400 | UpdatePost401 | UpdatePost403 | UpdatePost404 | UpdatePost500>, {postID: UpdatePostPathParams["postID"], data: UpdatePostMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdatePostMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updatePostMutationKey()

          const baseOptions = updatePostMutationOptions(config) as UseMutationOptions<UpdatePostMutationResponse, ResponseErrorConfig<UpdatePost400 | UpdatePost401 | UpdatePost403 | UpdatePost404 | UpdatePost500>, {postID: UpdatePostPathParams["postID"], data: UpdatePostMutationRequest}, TContext>
          

          return useMutation<UpdatePostMutationResponse, ResponseErrorConfig<UpdatePost400 | UpdatePost401 | UpdatePost403 | UpdatePost404 | UpdatePost500>, {postID: UpdatePostPathParams["postID"], data: UpdatePostMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdatePostMutationResponse, ResponseErrorConfig<UpdatePost400 | UpdatePost401 | UpdatePost403 | UpdatePost404 | UpdatePost500>, {postID: UpdatePostPathParams["postID"], data: UpdatePostMutationRequest}, TContext>
      
}