/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UploadCoverMutationRequest, UploadCoverMutationResponse, UploadCover400, UploadCover401, UploadCover404, UploadCover500 } from "../models/UploadCover.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { uploadCover } from "../clients/uploadCover.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const uploadCoverMutationKey = () => [{ url: '/me/cover' }] as const

export type UploadCoverMutationKey = ReturnType<typeof uploadCoverMutationKey>

export function uploadCoverMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UploadCoverMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = uploadCoverMutationKey()
        return mutationOptions<UploadCoverMutationResponse, ResponseErrorConfig<UploadCover400 | UploadCover401 | UploadCover404 | UploadCover500>, {data: UploadCoverMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return uploadCover(data, config)
          },
        })

}

/**
 * @description Upload a new cover image for the authenticated user
 * @summary Upload cover image
 * {@link /me/cover}
 */
export function useUploadCover<TContext>(options: 
{
  mutation?: UseMutationOptions<UploadCoverMutationResponse, ResponseErrorConfig<UploadCover400 | UploadCover401 | UploadCover404 | UploadCover500>, {data: UploadCoverMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UploadCoverMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? uploadCoverMutationKey()

          const baseOptions = uploadCoverMutationOptions(config) as UseMutationOptions<UploadCoverMutationResponse, ResponseErrorConfig<UploadCover400 | UploadCover401 | UploadCover404 | UploadCover500>, {data: UploadCoverMutationRequest}, TContext>
          

          return useMutation<UploadCoverMutationResponse, ResponseErrorConfig<UploadCover400 | UploadCover401 | UploadCover404 | UploadCover500>, {data: UploadCoverMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UploadCoverMutationResponse, ResponseErrorConfig<UploadCover400 | UploadCover401 | UploadCover404 | UploadCover500>, {data: UploadCoverMutationRequest}, TContext>
      
}