/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UploadMediaMutationRequest, UploadMediaMutationResponse, UploadMedia400, UploadMedia401, UploadMedia413, UploadMedia415, UploadMedia500 } from "../models/UploadMedia.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { uploadMedia } from "../clients/uploadMedia.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const uploadMediaMutationKey = () => [{ url: '/media/upload' }] as const

export type UploadMediaMutationKey = ReturnType<typeof uploadMediaMutationKey>

export function uploadMediaMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UploadMediaMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = uploadMediaMutationKey()
        return mutationOptions<UploadMediaMutationResponse, ResponseErrorConfig<UploadMedia400 | UploadMedia401 | UploadMedia413 | UploadMedia415 | UploadMedia500>, {data: UploadMediaMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return uploadMedia(data, config)
          },
        })

}

/**
 * @description Upload an image or video file. Returns the storage key and public URL.
 * Supported types: image/jpeg, image/png, image/webp, image/gif, video/mp4, video/webm
 * Max size: 10 MB for images, 100 MB for videos.
 * @summary Upload a media file
 * {@link /media/upload}
 */
export function useUploadMedia<TContext>(options: 
{
  mutation?: UseMutationOptions<UploadMediaMutationResponse, ResponseErrorConfig<UploadMedia400 | UploadMedia401 | UploadMedia413 | UploadMedia415 | UploadMedia500>, {data: UploadMediaMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UploadMediaMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? uploadMediaMutationKey()

          const baseOptions = uploadMediaMutationOptions(config) as UseMutationOptions<UploadMediaMutationResponse, ResponseErrorConfig<UploadMedia400 | UploadMedia401 | UploadMedia413 | UploadMedia415 | UploadMedia500>, {data: UploadMediaMutationRequest}, TContext>
          

          return useMutation<UploadMediaMutationResponse, ResponseErrorConfig<UploadMedia400 | UploadMedia401 | UploadMedia413 | UploadMedia415 | UploadMedia500>, {data: UploadMediaMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UploadMediaMutationResponse, ResponseErrorConfig<UploadMedia400 | UploadMedia401 | UploadMedia413 | UploadMedia415 | UploadMedia500>, {data: UploadMediaMutationRequest}, TContext>
      
}