/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateUserMutationRequest, UpdateUserMutationResponse, UpdateUserPathParams, UpdateUserQueryParams, UpdateUser400, UpdateUser404, UpdateUser409, UpdateUser500 } from "../models/UpdateUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { updateUser } from "../clients/updateUser.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateUserMutationKey = () => [{ url: '/users/:userKey' }] as const

export type UpdateUserMutationKey = ReturnType<typeof updateUserMutationKey>

export function updateUserMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateUserMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateUserMutationKey()
        return mutationOptions<UpdateUserMutationResponse, ResponseErrorConfig<UpdateUser400 | UpdateUser404 | UpdateUser409 | UpdateUser500>, {userKey: UpdateUserPathParams["userKey"], data: UpdateUserMutationRequest, params?: UpdateUserQueryParams}, TContext>({
          mutationKey,
          mutationFn: async({ userKey, data, params }) => {
            return updateUser(userKey, data, params, config)
          },
        })

}

/**
 * @description Update user account fields (e.g. email) by UUID or username (with ?by=username)
 * @summary Update user account
 * {@link /users/:userKey}
 */
export function useUpdateUser<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateUserMutationResponse, ResponseErrorConfig<UpdateUser400 | UpdateUser404 | UpdateUser409 | UpdateUser500>, {userKey: UpdateUserPathParams["userKey"], data: UpdateUserMutationRequest, params?: UpdateUserQueryParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateUserMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateUserMutationKey()

          const baseOptions = updateUserMutationOptions(config) as UseMutationOptions<UpdateUserMutationResponse, ResponseErrorConfig<UpdateUser400 | UpdateUser404 | UpdateUser409 | UpdateUser500>, {userKey: UpdateUserPathParams["userKey"], data: UpdateUserMutationRequest, params?: UpdateUserQueryParams}, TContext>
          

          return useMutation<UpdateUserMutationResponse, ResponseErrorConfig<UpdateUser400 | UpdateUser404 | UpdateUser409 | UpdateUser500>, {userKey: UpdateUserPathParams["userKey"], data: UpdateUserMutationRequest, params?: UpdateUserQueryParams}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateUserMutationResponse, ResponseErrorConfig<UpdateUser400 | UpdateUser404 | UpdateUser409 | UpdateUser500>, {userKey: UpdateUserPathParams["userKey"], data: UpdateUserMutationRequest, params?: UpdateUserQueryParams}, TContext>
      
}