/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VerifyEmailMutationRequest, VerifyEmailMutationResponse, VerifyEmail400, VerifyEmail500 } from "../models/VerifyEmail.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { verifyEmail } from "../clients/verifyEmail.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const verifyEmailMutationKey = () => [{ url: '/auth/verify-email' }] as const

export type VerifyEmailMutationKey = ReturnType<typeof verifyEmailMutationKey>

export function verifyEmailMutationOptions<TContext = unknown>(config: Partial<RequestConfig<VerifyEmailMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = verifyEmailMutationKey()
        return mutationOptions<VerifyEmailMutationResponse, ResponseErrorConfig<VerifyEmail400 | VerifyEmail500>, {data: VerifyEmailMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return verifyEmail(data, config)
          },
        })

}

/**
 * @description Verify a user's email address using the token sent via email
 * @summary Verify email address
 * {@link /auth/verify-email}
 */
export function useVerifyEmail<TContext>(options: 
{
  mutation?: UseMutationOptions<VerifyEmailMutationResponse, ResponseErrorConfig<VerifyEmail400 | VerifyEmail500>, {data: VerifyEmailMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<VerifyEmailMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? verifyEmailMutationKey()

          const baseOptions = verifyEmailMutationOptions(config) as UseMutationOptions<VerifyEmailMutationResponse, ResponseErrorConfig<VerifyEmail400 | VerifyEmail500>, {data: VerifyEmailMutationRequest}, TContext>
          

          return useMutation<VerifyEmailMutationResponse, ResponseErrorConfig<VerifyEmail400 | VerifyEmail500>, {data: VerifyEmailMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<VerifyEmailMutationResponse, ResponseErrorConfig<VerifyEmail400 | VerifyEmail500>, {data: VerifyEmailMutationRequest}, TContext>
      
}