/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorDetail } from "./ErrorDetail.ts";

export type ErrorsErrorResponse = {
    /**
     * @type object | undefined
    */
    error?: ErrorsErrorDetail;
};