/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ErrorsErrorDetail = {
    /**
     * @type string | undefined
    */
    code?: string;
    /**
     * @type object | undefined
    */
    details?: {
        [key: string]: any;
    };
    /**
     * @type string | undefined
    */
    message?: string;
};