/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoFeedSettingsResponse } from "./dto/FeedSettingsResponse.ts";
import type { DtoUpdateFeedSettingsRequest } from "./dto/UpdateFeedSettingsRequest.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description OK
*/
export type AdminUpdateFeedSettings200 = DtoFeedSettingsResponse;

/**
 * @description Bad Request
*/
export type AdminUpdateFeedSettings400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type AdminUpdateFeedSettings401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type AdminUpdateFeedSettings403 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type AdminUpdateFeedSettings500 = ErrorsErrorResponse;

/**
 * @description Fields to change
*/
export type AdminUpdateFeedSettingsMutationRequest = DtoUpdateFeedSettingsRequest;

export type AdminUpdateFeedSettingsMutationResponse = AdminUpdateFeedSettings200;

export type AdminUpdateFeedSettingsMutation = {
    Response: AdminUpdateFeedSettings200;
    Request: AdminUpdateFeedSettingsMutationRequest;
    Errors: AdminUpdateFeedSettings400 | AdminUpdateFeedSettings401 | AdminUpdateFeedSettings403 | AdminUpdateFeedSettings500;
};