/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAdminSendNotificationRequest } from "./dto/AdminSendNotificationRequest.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type AdminSendNotificationToUserPathParams = {
    /**
     * @description Target user UUID
     * @type string
    */
    id: string;
};

/**
 * @description No Content
*/
export type AdminSendNotificationToUser204 = any;

/**
 * @description Bad Request
*/
export type AdminSendNotificationToUser400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type AdminSendNotificationToUser401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type AdminSendNotificationToUser403 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type AdminSendNotificationToUser404 = ErrorsErrorResponse;

/**
 * @description Notification payload
*/
export type AdminSendNotificationToUserMutationRequest = DtoAdminSendNotificationRequest;

export type AdminSendNotificationToUserMutationResponse = AdminSendNotificationToUser204;

export type AdminSendNotificationToUserMutation = {
    Response: AdminSendNotificationToUser204;
    Request: AdminSendNotificationToUserMutationRequest;
    PathParams: AdminSendNotificationToUserPathParams;
    Errors: AdminSendNotificationToUser400 | AdminSendNotificationToUser401 | AdminSendNotificationToUser403 | AdminSendNotificationToUser404;
};