/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAdminStatsResponse } from "./dto/AdminStatsResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description OK
*/
export type AdminGetStats200 = DtoAdminStatsResponse;

/**
 * @description Unauthorized
*/
export type AdminGetStats401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type AdminGetStats403 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type AdminGetStats500 = ErrorsErrorResponse;

export type AdminGetStatsQueryResponse = AdminGetStats200;

export type AdminGetStatsQuery = {
    Response: AdminGetStats200;
    Errors: AdminGetStats401 | AdminGetStats403 | AdminGetStats500;
};