/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoFeedSettingsResponse } from "./dto/FeedSettingsResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description OK
*/
export type AdminGetFeedSettings200 = DtoFeedSettingsResponse;

/**
 * @description Unauthorized
*/
export type AdminGetFeedSettings401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type AdminGetFeedSettings403 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type AdminGetFeedSettings500 = ErrorsErrorResponse;

export type AdminGetFeedSettingsQueryResponse = AdminGetFeedSettings200;

export type AdminGetFeedSettingsQuery = {
    Response: AdminGetFeedSettings200;
    Errors: AdminGetFeedSettings401 | AdminGetFeedSettings403 | AdminGetFeedSettings500;
};