/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoListRolesResponse } from "./dto/ListRolesResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description OK
*/
export type AdminListRoles200 = DtoListRolesResponse;

/**
 * @description Unauthorized
*/
export type AdminListRoles401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type AdminListRoles403 = ErrorsErrorResponse;

export type AdminListRolesQueryResponse = AdminListRoles200;

export type AdminListRolesQuery = {
    Response: AdminListRoles200;
    Errors: AdminListRoles401 | AdminListRoles403;
};