/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAdminUserResponse } from "./dto/AdminUserResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type AdminGetUserPathParams = {
    /**
     * @description User UUID
     * @type string
    */
    id: string;
};

/**
 * @description OK
*/
export type AdminGetUser200 = DtoAdminUserResponse;

/**
 * @description Bad Request
*/
export type AdminGetUser400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type AdminGetUser401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type AdminGetUser403 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type AdminGetUser404 = ErrorsErrorResponse;

export type AdminGetUserQueryResponse = AdminGetUser200;

export type AdminGetUserQuery = {
    Response: AdminGetUser200;
    PathParams: AdminGetUserPathParams;
    Errors: AdminGetUser400 | AdminGetUser401 | AdminGetUser403 | AdminGetUser404;
};