/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAssignRoleRequest } from "./dto/AssignRoleRequest.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type AdminAssignRolePathParams = {
    /**
     * @description User UUID
     * @type string
    */
    id: string;
};

/**
 * @description No Content
*/
export type AdminAssignRole204 = any;

/**
 * @description Unknown role name
*/
export type AdminAssignRole400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type AdminAssignRole401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type AdminAssignRole403 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type AdminAssignRole404 = ErrorsErrorResponse;

/**
 * @description Role to assign
*/
export type AdminAssignRoleMutationRequest = DtoAssignRoleRequest;

export type AdminAssignRoleMutationResponse = AdminAssignRole204;

export type AdminAssignRoleMutation = {
    Response: AdminAssignRole204;
    Request: AdminAssignRoleMutationRequest;
    PathParams: AdminAssignRolePathParams;
    Errors: AdminAssignRole400 | AdminAssignRole401 | AdminAssignRole403 | AdminAssignRole404;
};