/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUserRolesResponse } from "./dto/UserRolesResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type AdminGetUserRolesPathParams = {
    /**
     * @description User UUID
     * @type string
    */
    id: string;
};

/**
 * @description OK
*/
export type AdminGetUserRoles200 = DtoUserRolesResponse;

/**
 * @description Bad Request
*/
export type AdminGetUserRoles400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type AdminGetUserRoles401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type AdminGetUserRoles403 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type AdminGetUserRoles404 = ErrorsErrorResponse;

export type AdminGetUserRolesQueryResponse = AdminGetUserRoles200;

export type AdminGetUserRolesQuery = {
    Response: AdminGetUserRoles200;
    PathParams: AdminGetUserRolesPathParams;
    Errors: AdminGetUserRoles400 | AdminGetUserRoles401 | AdminGetUserRoles403 | AdminGetUserRoles404;
};