/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export const adminRemoveRolePathParamsRoleEnum = {
    admin: "admin",
    moderator: "moderator"
} as const;

export type AdminRemoveRolePathParamsRoleEnumKey = (typeof adminRemoveRolePathParamsRoleEnum)[keyof typeof adminRemoveRolePathParamsRoleEnum];

export type AdminRemoveRolePathParams = {
    /**
     * @description User UUID
     * @type string
    */
    id: string;
    /**
     * @description Role name
     * @type string
    */
    role: AdminRemoveRolePathParamsRoleEnumKey;
};

/**
 * @description No Content
*/
export type AdminRemoveRole204 = any;

/**
 * @description Unknown role name
*/
export type AdminRemoveRole400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type AdminRemoveRole401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type AdminRemoveRole403 = ErrorsErrorResponse;

export type AdminRemoveRoleMutationResponse = AdminRemoveRole204;

export type AdminRemoveRoleMutation = {
    Response: AdminRemoveRole204;
    PathParams: AdminRemoveRolePathParams;
    Errors: AdminRemoveRole400 | AdminRemoveRole401 | AdminRemoveRole403;
};