/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAdminBroadcastNotificationResponse } from "./dto/AdminBroadcastNotificationResponse.ts";
import type { DtoAdminSendNotificationRequest } from "./dto/AdminSendNotificationRequest.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description OK
*/
export type AdminBroadcastNotification200 = DtoAdminBroadcastNotificationResponse;

/**
 * @description Bad Request
*/
export type AdminBroadcastNotification400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type AdminBroadcastNotification401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type AdminBroadcastNotification403 = ErrorsErrorResponse;

/**
 * @description Notification payload
*/
export type AdminBroadcastNotificationMutationRequest = DtoAdminSendNotificationRequest;

export type AdminBroadcastNotificationMutationResponse = AdminBroadcastNotification200;

export type AdminBroadcastNotificationMutation = {
    Response: AdminBroadcastNotification200;
    Request: AdminBroadcastNotificationMutationRequest;
    Errors: AdminBroadcastNotification400 | AdminBroadcastNotification401 | AdminBroadcastNotification403;
};