/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAdminSetUserStatusRequest } from "./dto/AdminSetUserStatusRequest.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type AdminSetUserStatusPathParams = {
    /**
     * @description User UUID
     * @type string
    */
    id: string;
};

/**
 * @description No Content
*/
export type AdminSetUserStatus204 = any;

/**
 * @description Bad Request
*/
export type AdminSetUserStatus400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type AdminSetUserStatus401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type AdminSetUserStatus403 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type AdminSetUserStatus404 = ErrorsErrorResponse;

/**
 * @description Status payload
*/
export type AdminSetUserStatusMutationRequest = DtoAdminSetUserStatusRequest;

export type AdminSetUserStatusMutationResponse = AdminSetUserStatus204;

export type AdminSetUserStatusMutation = {
    Response: AdminSetUserStatus204;
    Request: AdminSetUserStatusMutationRequest;
    PathParams: AdminSetUserStatusPathParams;
    Errors: AdminSetUserStatus400 | AdminSetUserStatus401 | AdminSetUserStatus403 | AdminSetUserStatus404;
};