/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAdminListUsersResponse } from "./dto/AdminListUsersResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type AdminListUsersQueryParams = {
    /**
     * @description Max items per page (default 20)
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Number of items to skip
     * @type integer | undefined
    */
    offset?: number;
    /**
     * @description Search by username, email, or display name
     * @type string | undefined
    */
    q?: string;
    /**
     * @description Filter by active status (omit for all)
     * @type boolean | undefined
    */
    is_active?: boolean;
};

/**
 * @description OK
*/
export type AdminListUsers200 = DtoAdminListUsersResponse;

/**
 * @description Unauthorized
*/
export type AdminListUsers401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type AdminListUsers403 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type AdminListUsers500 = ErrorsErrorResponse;

export type AdminListUsersQueryResponse = AdminListUsers200;

export type AdminListUsersQuery = {
    Response: AdminListUsers200;
    QueryParams: AdminListUsersQueryParams;
    Errors: AdminListUsers401 | AdminListUsers403 | AdminListUsers500;
};