/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoChangePasswordRequest } from "./dto/ChangePasswordRequest.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";
import type { HttputilMessageResponse } from "./httputil/MessageResponse.ts";

/**
 * @description Password changed successfully
*/
export type ChangePassword200 = HttputilMessageResponse;

/**
 * @description Invalid request
*/
export type ChangePassword400 = ErrorsErrorResponse;

/**
 * @description Invalid old password or not authenticated
*/
export type ChangePassword401 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type ChangePassword500 = ErrorsErrorResponse;

/**
 * @description Password change data
*/
export type ChangePasswordMutationRequest = DtoChangePasswordRequest;

export type ChangePasswordMutationResponse = ChangePassword200;

export type ChangePasswordMutation = {
    Response: ChangePassword200;
    Request: ChangePasswordMutationRequest;
    Errors: ChangePassword400 | ChangePassword401 | ChangePassword500;
};