/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreatePostRequest } from "./dto/CreatePostRequest.ts";
import type { DtoPostResponse } from "./dto/PostResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description Created
*/
export type CreatePost201 = DtoPostResponse;

/**
 * @description Bad Request
*/
export type CreatePost400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type CreatePost401 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type CreatePost500 = ErrorsErrorResponse;

/**
 * @description Post data
*/
export type CreatePostMutationRequest = DtoCreatePostRequest;

export type CreatePostMutationResponse = CreatePost201;

export type CreatePostMutation = {
    Response: CreatePost201;
    Request: CreatePostMutationRequest;
    Errors: CreatePost400 | CreatePost401 | CreatePost500;
};