/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCommentResponse } from "./dto/CommentResponse.ts";
import type { DtoCreateCommentRequest } from "./dto/CreateCommentRequest.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type CreateCommentPathParams = {
    /**
     * @description Post ID (UUID)
     * @type string
    */
    postID: string;
};

/**
 * @description Created
*/
export type CreateComment201 = DtoCommentResponse;

/**
 * @description Bad Request
*/
export type CreateComment400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type CreateComment401 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type CreateComment404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type CreateComment500 = ErrorsErrorResponse;

/**
 * @description Comment data
*/
export type CreateCommentMutationRequest = DtoCreateCommentRequest;

export type CreateCommentMutationResponse = CreateComment201;

export type CreateCommentMutation = {
    Response: CreateComment201;
    Request: CreateCommentMutationRequest;
    PathParams: CreateCommentPathParams;
    Errors: CreateComment400 | CreateComment401 | CreateComment404 | CreateComment500;
};