/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";
import type { HttputilMessageResponse } from "./httputil/MessageResponse.ts";

export type DeactivateUserPathParams = {
    /**
     * @description User ID (UUID) or username
     * @type string
    */
    userKey: string;
};

export const deactivateUserQueryParamsByEnum = {
    username: "username"
} as const;

export type DeactivateUserQueryParamsByEnumKey = (typeof deactivateUserQueryParamsByEnum)[keyof typeof deactivateUserQueryParamsByEnum];

export type DeactivateUserQueryParams = {
    /**
     * @description Resolve key as \'username\' instead of UUID
     * @type string | undefined
    */
    by?: DeactivateUserQueryParamsByEnumKey;
};

/**
 * @description User deactivated successfully
*/
export type DeactivateUser200 = HttputilMessageResponse;

/**
 * @description Bad Request
*/
export type DeactivateUser400 = ErrorsErrorResponse;

/**
 * @description User not found
*/
export type DeactivateUser404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type DeactivateUser500 = ErrorsErrorResponse;

export type DeactivateUserMutationResponse = DeactivateUser200;

export type DeactivateUserMutation = {
    Response: DeactivateUser200;
    PathParams: DeactivateUserPathParams;
    QueryParams: DeactivateUserQueryParams;
    Errors: DeactivateUser400 | DeactivateUser404 | DeactivateUser500;
};