/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type DeleteCommentPathParams = {
    /**
     * @description Post ID (UUID)
     * @type string
    */
    postID: string;
    /**
     * @description Comment ID (UUID)
     * @type string
    */
    commentID: string;
};

/**
 * @description No Content
*/
export type DeleteComment204 = any;

/**
 * @description Bad Request
*/
export type DeleteComment400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type DeleteComment401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type DeleteComment403 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type DeleteComment404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type DeleteComment500 = ErrorsErrorResponse;

export type DeleteCommentMutationResponse = DeleteComment204;

export type DeleteCommentMutation = {
    Response: DeleteComment204;
    PathParams: DeleteCommentPathParams;
    Errors: DeleteComment400 | DeleteComment401 | DeleteComment403 | DeleteComment404 | DeleteComment500;
};