/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type DeletePostPathParams = {
    /**
     * @description Post ID (UUID)
     * @type string
    */
    postID: string;
};

/**
 * @description No Content
*/
export type DeletePost204 = any;

/**
 * @description Bad Request
*/
export type DeletePost400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type DeletePost401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type DeletePost403 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type DeletePost404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type DeletePost500 = ErrorsErrorResponse;

export type DeletePostMutationResponse = DeletePost204;

export type DeletePostMutation = {
    Response: DeletePost204;
    PathParams: DeletePostPathParams;
    Errors: DeletePost400 | DeletePost401 | DeletePost403 | DeletePost404 | DeletePost500;
};