/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type FollowUserPathParams = {
    /**
     * @description User ID (UUID) or username
     * @type string
    */
    userKey: string;
};

export const followUserQueryParamsByEnum = {
    username: "username"
} as const;

export type FollowUserQueryParamsByEnumKey = (typeof followUserQueryParamsByEnum)[keyof typeof followUserQueryParamsByEnum];

export type FollowUserQueryParams = {
    /**
     * @description Resolve key as \'username\' instead of UUID
     * @type string | undefined
    */
    by?: FollowUserQueryParamsByEnumKey;
};

/**
 * @description No Content
*/
export type FollowUser204 = any;

/**
 * @description Invalid user identifier or self-follow
*/
export type FollowUser400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type FollowUser401 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type FollowUser500 = ErrorsErrorResponse;

export type FollowUserMutationResponse = FollowUser204;

export type FollowUserMutation = {
    Response: FollowUser204;
    PathParams: FollowUserPathParams;
    QueryParams: FollowUserQueryParams;
    Errors: FollowUser400 | FollowUser401 | FollowUser500;
};