/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoForgotPasswordRequest } from "./dto/ForgotPasswordRequest.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";
import type { HttputilMessageResponse } from "./httputil/MessageResponse.ts";

/**
 * @description Reset link sent if account exists
*/
export type ForgotPassword200 = HttputilMessageResponse;

/**
 * @description Invalid request
*/
export type ForgotPassword400 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type ForgotPassword500 = ErrorsErrorResponse;

/**
 * @description Email address
*/
export type ForgotPasswordMutationRequest = DtoForgotPasswordRequest;

export type ForgotPasswordMutationResponse = ForgotPassword200;

export type ForgotPasswordMutation = {
    Response: ForgotPassword200;
    Request: ForgotPasswordMutationRequest;
    Errors: ForgotPassword400 | ForgotPassword500;
};