/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCommentListResponse } from "./dto/CommentListResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type GetCommentsPathParams = {
    /**
     * @description Post ID (UUID)
     * @type string
    */
    postID: string;
};

export type GetCommentsQueryParams = {
    /**
     * @description Max results (default 20)
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset (default 0)
     * @type integer | undefined
    */
    offset?: number;
};

/**
 * @description OK
*/
export type GetComments200 = DtoCommentListResponse;

/**
 * @description Bad Request
*/
export type GetComments400 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type GetComments404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetComments500 = ErrorsErrorResponse;

export type GetCommentsQueryResponse = GetComments200;

export type GetCommentsQuery = {
    Response: GetComments200;
    PathParams: GetCommentsPathParams;
    QueryParams: GetCommentsQueryParams;
    Errors: GetComments400 | GetComments404 | GetComments500;
};