/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";
import type { HandlerDiscoverResponse } from "./handler/DiscoverResponse.ts";

export type GetDiscoverQueryParams = {
    /**
     * @description Pagination cursor from previous response
     * @type string | undefined
    */
    cursor?: string;
    /**
     * @description Max results (default 20)
     * @type integer | undefined
    */
    limit?: number;
};

/**
 * @description OK
*/
export type GetDiscover200 = HandlerDiscoverResponse;

/**
 * @description Bad Request
*/
export type GetDiscover400 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetDiscover500 = ErrorsErrorResponse;

export type GetDiscoverQueryResponse = GetDiscover200;

export type GetDiscoverQuery = {
    Response: GetDiscover200;
    QueryParams: GetDiscoverQueryParams;
    Errors: GetDiscover400 | GetDiscover500;
};