/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoFollowListResponse } from "./dto/FollowListResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type GetFollowersPathParams = {
    /**
     * @description User ID (UUID) or username
     * @type string
    */
    userKey: string;
};

export const getFollowersQueryParamsByEnum = {
    username: "username"
} as const;

export type GetFollowersQueryParamsByEnumKey = (typeof getFollowersQueryParamsByEnum)[keyof typeof getFollowersQueryParamsByEnum];

export type GetFollowersQueryParams = {
    /**
     * @description Resolve key as \'username\' instead of UUID
     * @type string | undefined
    */
    by?: GetFollowersQueryParamsByEnumKey;
    /**
     * @description Max results (default 20)
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset (default 0)
     * @type integer | undefined
    */
    offset?: number;
};

/**
 * @description OK
*/
export type GetFollowers200 = DtoFollowListResponse;

/**
 * @description Invalid user identifier
*/
export type GetFollowers400 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetFollowers500 = ErrorsErrorResponse;

export type GetFollowersQueryResponse = GetFollowers200;

export type GetFollowersQuery = {
    Response: GetFollowers200;
    PathParams: GetFollowersPathParams;
    QueryParams: GetFollowersQueryParams;
    Errors: GetFollowers400 | GetFollowers500;
};