/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";
import type { HandlerFeedResponse } from "./handler/FeedResponse.ts";

export type GetFeedQueryParams = {
    /**
     * @description Pagination cursor from previous response
     * @type string | undefined
    */
    cursor?: string;
};

/**
 * @description OK
*/
export type GetFeed200 = HandlerFeedResponse;

/**
 * @description Bad Request
*/
export type GetFeed400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type GetFeed401 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetFeed500 = ErrorsErrorResponse;

export type GetFeedQueryResponse = GetFeed200;

export type GetFeedQuery = {
    Response: GetFeed200;
    QueryParams: GetFeedQueryParams;
    Errors: GetFeed400 | GetFeed401 | GetFeed500;
};