/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoFollowListResponse } from "./dto/FollowListResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type GetFollowingPathParams = {
    /**
     * @description User ID (UUID) or username
     * @type string
    */
    userKey: string;
};

export const getFollowingQueryParamsByEnum = {
    username: "username"
} as const;

export type GetFollowingQueryParamsByEnumKey = (typeof getFollowingQueryParamsByEnum)[keyof typeof getFollowingQueryParamsByEnum];

export type GetFollowingQueryParams = {
    /**
     * @description Resolve key as \'username\' instead of UUID
     * @type string | undefined
    */
    by?: GetFollowingQueryParamsByEnumKey;
    /**
     * @description Max results (default 20)
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset (default 0)
     * @type integer | undefined
    */
    offset?: number;
};

/**
 * @description OK
*/
export type GetFollowing200 = DtoFollowListResponse;

/**
 * @description Invalid user identifier
*/
export type GetFollowing400 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetFollowing500 = ErrorsErrorResponse;

export type GetFollowingQueryResponse = GetFollowing200;

export type GetFollowingQuery = {
    Response: GetFollowing200;
    PathParams: GetFollowingPathParams;
    QueryParams: GetFollowingQueryParams;
    Errors: GetFollowing400 | GetFollowing500;
};