/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUserResponse } from "./dto/UserResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description OK
*/
export type GetMe200 = DtoUserResponse;

/**
 * @description Unauthorized
*/
export type GetMe401 = ErrorsErrorResponse;

/**
 * @description User not found
*/
export type GetMe404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetMe500 = ErrorsErrorResponse;

export type GetMeQueryResponse = GetMe200;

export type GetMeQuery = {
    Response: GetMe200;
    Errors: GetMe401 | GetMe404 | GetMe500;
};