/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUserResponse } from "./dto/UserResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description OK
*/
export type GetMyProfile200 = DtoUserResponse;

/**
 * @description Unauthorized
*/
export type GetMyProfile401 = ErrorsErrorResponse;

/**
 * @description User not found
*/
export type GetMyProfile404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetMyProfile500 = ErrorsErrorResponse;

export type GetMyProfileQueryResponse = GetMyProfile200;

export type GetMyProfileQuery = {
    Response: GetMyProfile200;
    Errors: GetMyProfile401 | GetMyProfile404 | GetMyProfile500;
};