/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoNotificationListResponse } from "./dto/NotificationListResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type GetNotificationsQueryParams = {
    /**
     * @description Pagination cursor from previous response
     * @type string | undefined
    */
    cursor?: string;
};

/**
 * @description OK
*/
export type GetNotifications200 = DtoNotificationListResponse;

/**
 * @description Bad Request
*/
export type GetNotifications400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type GetNotifications401 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetNotifications500 = ErrorsErrorResponse;

export type GetNotificationsQueryResponse = GetNotifications200;

export type GetNotificationsQuery = {
    Response: GetNotifications200;
    QueryParams: GetNotificationsQueryParams;
    Errors: GetNotifications400 | GetNotifications401 | GetNotifications500;
};