/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoHashtagPostListResponse } from "./dto/HashtagPostListResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type GetPostsByHashtagPathParams = {
    /**
     * @description Hashtag name (without #)
     * @type string
    */
    name: string;
};

export type GetPostsByHashtagQueryParams = {
    /**
     * @description Pagination cursor
     * @type string | undefined
    */
    cursor?: string;
    /**
     * @description Max results (default 20)
     * @type integer | undefined
    */
    limit?: number;
};

/**
 * @description OK
*/
export type GetPostsByHashtag200 = DtoHashtagPostListResponse;

/**
 * @description Bad Request
*/
export type GetPostsByHashtag400 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetPostsByHashtag500 = ErrorsErrorResponse;

export type GetPostsByHashtagQueryResponse = GetPostsByHashtag200;

export type GetPostsByHashtagQuery = {
    Response: GetPostsByHashtag200;
    PathParams: GetPostsByHashtagPathParams;
    QueryParams: GetPostsByHashtagQueryParams;
    Errors: GetPostsByHashtag400 | GetPostsByHashtag500;
};