/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPostResponse } from "./dto/PostResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type GetPostPathParams = {
    /**
     * @description Post ID (UUID)
     * @type string
    */
    postID: string;
};

/**
 * @description OK
*/
export type GetPost200 = DtoPostResponse;

/**
 * @description Bad Request
*/
export type GetPost400 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type GetPost404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetPost500 = ErrorsErrorResponse;

export type GetPostQueryResponse = GetPost200;

export type GetPostQuery = {
    Response: GetPost200;
    PathParams: GetPostPathParams;
    Errors: GetPost400 | GetPost404 | GetPost500;
};