/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCommentListResponse } from "./dto/CommentListResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type GetRepliesPathParams = {
    /**
     * @description Post ID (UUID)
     * @type string
    */
    postID: string;
    /**
     * @description Comment ID (UUID)
     * @type string
    */
    commentID: string;
};

export type GetRepliesQueryParams = {
    /**
     * @description Max results (default 20)
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset (default 0)
     * @type integer | undefined
    */
    offset?: number;
};

/**
 * @description OK
*/
export type GetReplies200 = DtoCommentListResponse;

/**
 * @description Bad Request
*/
export type GetReplies400 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type GetReplies404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetReplies500 = ErrorsErrorResponse;

export type GetRepliesQueryResponse = GetReplies200;

export type GetRepliesQuery = {
    Response: GetReplies200;
    PathParams: GetRepliesPathParams;
    QueryParams: GetRepliesQueryParams;
    Errors: GetReplies400 | GetReplies404 | GetReplies500;
};