/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoTrendingHashtagListResponse } from "./dto/TrendingHashtagListResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description OK
*/
export type GetTrendingHashtags200 = DtoTrendingHashtagListResponse;

/**
 * @description Internal Server Error
*/
export type GetTrendingHashtags500 = ErrorsErrorResponse;

export type GetTrendingHashtagsQueryResponse = GetTrendingHashtags200;

export type GetTrendingHashtagsQuery = {
    Response: GetTrendingHashtags200;
    Errors: GetTrendingHashtags500;
};