/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUnreadCountResponse } from "./dto/UnreadCountResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description OK
*/
export type GetUnreadCount200 = DtoUnreadCountResponse;

/**
 * @description Unauthorized
*/
export type GetUnreadCount401 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetUnreadCount500 = ErrorsErrorResponse;

export type GetUnreadCountQueryResponse = GetUnreadCount200;

export type GetUnreadCountQuery = {
    Response: GetUnreadCount200;
    Errors: GetUnreadCount401 | GetUnreadCount500;
};