/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPostListResponse } from "./dto/PostListResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type GetUserPostsPathParams = {
    /**
     * @description Author user ID (UUID)
     * @type string
    */
    userID: string;
};

export type GetUserPostsQueryParams = {
    /**
     * @description Pagination cursor from previous response
     * @type string | undefined
    */
    cursor?: string;
    /**
     * @description Max results (default 20)
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Filter by visibility: public, followers, private
     * @type string | undefined
    */
    visibility?: string;
};

/**
 * @description OK
*/
export type GetUserPosts200 = DtoPostListResponse;

/**
 * @description Bad Request
*/
export type GetUserPosts400 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetUserPosts500 = ErrorsErrorResponse;

export type GetUserPostsQueryResponse = GetUserPosts200;

export type GetUserPostsQuery = {
    Response: GetUserPosts200;
    PathParams: GetUserPostsPathParams;
    QueryParams: GetUserPostsQueryParams;
    Errors: GetUserPosts400 | GetUserPosts500;
};