/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoProfileResponse } from "./dto/ProfileResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type GetUserProfilePathParams = {
    /**
     * @description User ID (UUID) or username
     * @type string
    */
    userKey: string;
};

export const getUserProfileQueryParamsByEnum = {
    username: "username"
} as const;

export type GetUserProfileQueryParamsByEnumKey = (typeof getUserProfileQueryParamsByEnum)[keyof typeof getUserProfileQueryParamsByEnum];

export type GetUserProfileQueryParams = {
    /**
     * @description Resolve key as \'username\' instead of UUID
     * @type string | undefined
    */
    by?: GetUserProfileQueryParamsByEnumKey;
};

/**
 * @description OK
*/
export type GetUserProfile200 = DtoProfileResponse;

/**
 * @description Invalid user identifier
*/
export type GetUserProfile400 = ErrorsErrorResponse;

/**
 * @description User not found
*/
export type GetUserProfile404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetUserProfile500 = ErrorsErrorResponse;

export type GetUserProfileQueryResponse = GetUserProfile200;

export type GetUserProfileQuery = {
    Response: GetUserProfile200;
    PathParams: GetUserProfilePathParams;
    QueryParams: GetUserProfileQueryParams;
    Errors: GetUserProfile400 | GetUserProfile404 | GetUserProfile500;
};