/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUserResponse } from "./dto/UserResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type GetUserPathParams = {
    /**
     * @description User ID (UUID) or username
     * @type string
    */
    userKey: string;
};

export const getUserQueryParamsByEnum = {
    username: "username"
} as const;

export type GetUserQueryParamsByEnumKey = (typeof getUserQueryParamsByEnum)[keyof typeof getUserQueryParamsByEnum];

export type GetUserQueryParams = {
    /**
     * @description Resolve key as \'username\' instead of UUID
     * @type string | undefined
    */
    by?: GetUserQueryParamsByEnumKey;
};

/**
 * @description OK
*/
export type GetUser200 = DtoUserResponse;

/**
 * @description Invalid user identifier
*/
export type GetUser400 = ErrorsErrorResponse;

/**
 * @description User not found
*/
export type GetUser404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetUser500 = ErrorsErrorResponse;

export type GetUserQueryResponse = GetUser200;

export type GetUserQuery = {
    Response: GetUser200;
    PathParams: GetUserPathParams;
    QueryParams: GetUserQueryParams;
    Errors: GetUser400 | GetUser404 | GetUser500;
};