/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoLoginRequest } from "./dto/LoginRequest.ts";
import type { DtoLoginResponse } from "./dto/LoginResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type LoginHeaderParams = {
    /**
     * @description Set to \'mobile\' to receive refresh_token in response body instead of HttpOnly cookie
     * @type string | undefined
    */
    "X-Client-Type"?: string;
};

/**
 * @description OK
*/
export type Login200 = DtoLoginResponse;

/**
 * @description Invalid request body
*/
export type Login400 = ErrorsErrorResponse;

/**
 * @description Invalid credentials
*/
export type Login401 = ErrorsErrorResponse;

/**
 * @description Account deactivated
*/
export type Login403 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type Login500 = ErrorsErrorResponse;

/**
 * @description Login credentials
*/
export type LoginMutationRequest = DtoLoginRequest;

export type LoginMutationResponse = Login200;

export type LoginMutation = {
    Response: Login200;
    Request: LoginMutationRequest;
    HeaderParams: LoginHeaderParams;
    Errors: Login400 | Login401 | Login403 | Login500;
};