/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoLogoutRequest } from "./dto/LogoutRequest.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";
import type { HttputilMessageResponse } from "./httputil/MessageResponse.ts";

export type LogoutHeaderParams = {
    /**
     * @description Set to \'mobile\' to send refresh_token in request body
     * @type string | undefined
    */
    "X-Client-Type"?: string;
};

/**
 * @description Logged out successfully
*/
export type Logout200 = HttputilMessageResponse;

/**
 * @description Invalid request body
*/
export type Logout400 = ErrorsErrorResponse;

/**
 * @description Missing refresh token cookie (web clients)
*/
export type Logout401 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type Logout500 = ErrorsErrorResponse;

/**
 * @description Refresh token to revoke (mobile clients only)
*/
export type LogoutMutationRequest = DtoLogoutRequest;

export type LogoutMutationResponse = Logout200;

export type LogoutMutation = {
    Response: Logout200;
    Request: LogoutMutationRequest;
    HeaderParams: LogoutHeaderParams;
    Errors: Logout400 | Logout401 | Logout500;
};