/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";
import type { HttputilMessageResponse } from "./httputil/MessageResponse.ts";

/**
 * @description All sessions logged out successfully
*/
export type LogoutAllSessions200 = HttputilMessageResponse;

/**
 * @description Unauthorized
*/
export type LogoutAllSessions401 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type LogoutAllSessions500 = ErrorsErrorResponse;

export type LogoutAllSessionsMutationResponse = LogoutAllSessions200;

export type LogoutAllSessionsMutation = {
    Response: LogoutAllSessions200;
    Errors: LogoutAllSessions401 | LogoutAllSessions500;
};