/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type MarkNotificationAsReadPathParams = {
    /**
     * @description Notification ID (UUID)
     * @type string
    */
    notificationID: string;
};

/**
 * @description No Content
*/
export type MarkNotificationAsRead204 = any;

/**
 * @description Bad Request
*/
export type MarkNotificationAsRead400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type MarkNotificationAsRead401 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type MarkNotificationAsRead500 = ErrorsErrorResponse;

export type MarkNotificationAsReadMutationResponse = MarkNotificationAsRead204;

export type MarkNotificationAsReadMutation = {
    Response: MarkNotificationAsRead204;
    PathParams: MarkNotificationAsReadPathParams;
    Errors: MarkNotificationAsRead400 | MarkNotificationAsRead401 | MarkNotificationAsRead500;
};