/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description No Content
*/
export type MarkAllNotificationsAsRead204 = any;

/**
 * @description Unauthorized
*/
export type MarkAllNotificationsAsRead401 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type MarkAllNotificationsAsRead500 = ErrorsErrorResponse;

export type MarkAllNotificationsAsReadMutationResponse = MarkAllNotificationsAsRead204;

export type MarkAllNotificationsAsReadMutation = {
    Response: MarkAllNotificationsAsRead204;
    Errors: MarkAllNotificationsAsRead401 | MarkAllNotificationsAsRead500;
};