/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoRefreshTokenRequest } from "./dto/RefreshTokenRequest.ts";
import type { DtoRefreshTokenResponse } from "./dto/RefreshTokenResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type RefreshTokenHeaderParams = {
    /**
     * @description Set to \'mobile\' to send/receive refresh_token in request/response body
     * @type string | undefined
    */
    "X-Client-Type"?: string;
};

/**
 * @description OK
*/
export type RefreshToken200 = DtoRefreshTokenResponse;

/**
 * @description Invalid request body
*/
export type RefreshToken400 = ErrorsErrorResponse;

/**
 * @description Invalid or expired refresh token
*/
export type RefreshToken401 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type RefreshToken500 = ErrorsErrorResponse;

/**
 * @description Refresh token (mobile clients only)
*/
export type RefreshTokenMutationRequest = DtoRefreshTokenRequest;

export type RefreshTokenMutationResponse = RefreshToken200;

export type RefreshTokenMutation = {
    Response: RefreshToken200;
    Request: RefreshTokenMutationRequest;
    HeaderParams: RefreshTokenHeaderParams;
    Errors: RefreshToken400 | RefreshToken401 | RefreshToken500;
};