/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoRegisterRequest } from "./dto/RegisterRequest.ts";
import type { DtoRegisterResponse } from "./dto/RegisterResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type RegisterHeaderParams = {
    /**
     * @description Set to \'mobile\' to receive refresh_token in response body instead of HttpOnly cookie
     * @type string | undefined
    */
    "X-Client-Type"?: string;
};

/**
 * @description Created
*/
export type Register201 = DtoRegisterResponse;

/**
 * @description Invalid request body
*/
export type Register400 = ErrorsErrorResponse;

/**
 * @description Username or email already exists
*/
export type Register409 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type Register500 = ErrorsErrorResponse;

/**
 * @description Registration data
*/
export type RegisterMutationRequest = DtoRegisterRequest;

export type RegisterMutationResponse = Register201;

export type RegisterMutation = {
    Response: Register201;
    Request: RegisterMutationRequest;
    HeaderParams: RegisterHeaderParams;
    Errors: Register400 | Register409 | Register500;
};