/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoResetPasswordRequest } from "./dto/ResetPasswordRequest.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";
import type { HttputilMessageResponse } from "./httputil/MessageResponse.ts";

/**
 * @description Password reset successfully
*/
export type ResetPassword200 = HttputilMessageResponse;

/**
 * @description Invalid or expired token
*/
export type ResetPassword400 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type ResetPassword500 = ErrorsErrorResponse;

/**
 * @description Reset token and new password
*/
export type ResetPasswordMutationRequest = DtoResetPasswordRequest;

export type ResetPasswordMutationResponse = ResetPassword200;

export type ResetPasswordMutation = {
    Response: ResetPassword200;
    Request: ResetPasswordMutationRequest;
    Errors: ResetPassword400 | ResetPassword500;
};