/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";
import type { HttputilMessageResponse } from "./httputil/MessageResponse.ts";

/**
 * @description Event accepted
*/
export type ResendWebhook200 = HttputilMessageResponse;

/**
 * @description Malformed payload
*/
export type ResendWebhook400 = ErrorsErrorResponse;

/**
 * @description Signature verification failed
*/
export type ResendWebhook401 = ErrorsErrorResponse;

/**
 * @description Event could not be applied; the provider will retry
*/
export type ResendWebhook500 = ErrorsErrorResponse;

export type ResendWebhookMutationResponse = ResendWebhook200;

export type ResendWebhookMutation = {
    Response: ResendWebhook200;
    Errors: ResendWebhook400 | ResendWebhook401 | ResendWebhook500;
};