/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoResendVerificationRequest } from "./dto/ResendVerificationRequest.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";
import type { HttputilMessageResponse } from "./httputil/MessageResponse.ts";

/**
 * @description Verification email sent if account exists
*/
export type ResendVerification200 = HttputilMessageResponse;

/**
 * @description Invalid request
*/
export type ResendVerification400 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type ResendVerification500 = ErrorsErrorResponse;

/**
 * @description Email address
*/
export type ResendVerificationMutationRequest = DtoResendVerificationRequest;

export type ResendVerificationMutationResponse = ResendVerification200;

export type ResendVerificationMutation = {
    Response: ResendVerification200;
    Request: ResendVerificationMutationRequest;
    Errors: ResendVerification400 | ResendVerification500;
};