/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoSearchResponse } from "./dto/SearchResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type SearchQueryParams = {
    /**
     * @description Search query (min 2 chars)
     * @type string
    */
    q: string;
    /**
     * @description Entity type: all | users | posts | hashtags (default: all)
     * @type string | undefined
    */
    type?: string;
    /**
     * @description Max results per category (default 20, max 50; ignored for type=all)
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset for pagination (ignored for type=all)
     * @type integer | undefined
    */
    offset?: number;
};

/**
 * @description OK
*/
export type Search200 = DtoSearchResponse;

/**
 * @description Bad Request
*/
export type Search400 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type Search500 = ErrorsErrorResponse;

export type SearchQueryResponse = Search200;

export type SearchQuery = {
    Response: Search200;
    QueryParams: SearchQueryParams;
    Errors: Search400 | Search500;
};