/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoHashtagSearchResponse } from "./dto/HashtagSearchResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type SearchHashtagsQueryParams = {
    /**
     * @description Prefix to search (min 2 chars, without #)
     * @type string
    */
    q: string;
};

/**
 * @description OK
*/
export type SearchHashtags200 = DtoHashtagSearchResponse;

/**
 * @description Bad Request
*/
export type SearchHashtags400 = ErrorsErrorResponse;

/**
 * @description Too Many Requests
*/
export type SearchHashtags429 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type SearchHashtags500 = ErrorsErrorResponse;

export type SearchHashtagsQueryResponse = SearchHashtags200;

export type SearchHashtagsQuery = {
    Response: SearchHashtags200;
    QueryParams: SearchHashtagsQueryParams;
    Errors: SearchHashtags400 | SearchHashtags429 | SearchHashtags500;
};