/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description SSE stream
*/
export type StreamNotifications200 = any;

/**
 * @description Unauthorized
*/
export type StreamNotifications401 = ErrorsErrorResponse;

/**
 * @description SSE not available (Redis disabled)
*/
export type StreamNotifications501 = ErrorsErrorResponse;

export type StreamNotificationsQueryResponse = StreamNotifications200;

export type StreamNotificationsQuery = {
    Response: StreamNotifications200;
    Errors: StreamNotifications401 | StreamNotifications501;
};