/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type StreamNotificationsQueryParams = {
    /**
     * @description JWT access token (alternative to Authorization header)
     * @type string | undefined
    */
    token?: string;
};

/**
 * @description SSE stream
*/
export type StreamNotifications200 = any;

/**
 * @description Unauthorized
*/
export type StreamNotifications401 = ErrorsErrorResponse;

/**
 * @description SSE not available (Redis disabled)
*/
export type StreamNotifications501 = ErrorsErrorResponse;

export type StreamNotificationsQueryResponse = StreamNotifications200;

export type StreamNotificationsQuery = {
    Response: StreamNotifications200;
    QueryParams: StreamNotificationsQueryParams;
    Errors: StreamNotifications401 | StreamNotifications501;
};