/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type ToggleCommentLikePathParams = {
    /**
     * @description Post ID (UUID)
     * @type string
    */
    postID: string;
    /**
     * @description Comment ID (UUID)
     * @type string
    */
    commentID: string;
};

/**
 * @description liked: true if now liked, false if now unliked
*/
export type ToggleCommentLike200 = {
    [key: string]: boolean;
};

/**
 * @description Bad Request
*/
export type ToggleCommentLike400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type ToggleCommentLike401 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type ToggleCommentLike404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type ToggleCommentLike500 = ErrorsErrorResponse;

export type ToggleCommentLikeMutationResponse = ToggleCommentLike200;

export type ToggleCommentLikeMutation = {
    Response: ToggleCommentLike200;
    PathParams: ToggleCommentLikePathParams;
    Errors: ToggleCommentLike400 | ToggleCommentLike401 | ToggleCommentLike404 | ToggleCommentLike500;
};