/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type ToggleLikePathParams = {
    /**
     * @description Post ID (UUID)
     * @type string
    */
    postID: string;
};

/**
 * @description liked: true if now liked, false if now unliked
*/
export type ToggleLike200 = {
    [key: string]: boolean;
};

/**
 * @description Invalid post ID or self-like
*/
export type ToggleLike400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type ToggleLike401 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type ToggleLike404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type ToggleLike500 = ErrorsErrorResponse;

export type ToggleLikeMutationResponse = ToggleLike200;

export type ToggleLikeMutation = {
    Response: ToggleLike200;
    PathParams: ToggleLikePathParams;
    Errors: ToggleLike400 | ToggleLike401 | ToggleLike404 | ToggleLike500;
};