/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type UnfollowUserPathParams = {
    /**
     * @description User ID (UUID) or username
     * @type string
    */
    userKey: string;
};

export const unfollowUserQueryParamsByEnum = {
    username: "username"
} as const;

export type UnfollowUserQueryParamsByEnumKey = (typeof unfollowUserQueryParamsByEnum)[keyof typeof unfollowUserQueryParamsByEnum];

export type UnfollowUserQueryParams = {
    /**
     * @description Resolve key as \'username\' instead of UUID
     * @type string | undefined
    */
    by?: UnfollowUserQueryParamsByEnumKey;
};

/**
 * @description No Content
*/
export type UnfollowUser204 = any;

/**
 * @description Invalid user identifier or self-unfollow
*/
export type UnfollowUser400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type UnfollowUser401 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type UnfollowUser500 = ErrorsErrorResponse;

export type UnfollowUserMutationResponse = UnfollowUser204;

export type UnfollowUserMutation = {
    Response: UnfollowUser204;
    PathParams: UnfollowUserPathParams;
    QueryParams: UnfollowUserQueryParams;
    Errors: UnfollowUser400 | UnfollowUser401 | UnfollowUser500;
};