/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateUserRequest } from "./dto/UpdateUserRequest.ts";
import type { DtoUserResponse } from "./dto/UserResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type UpdateUserPathParams = {
    /**
     * @description User ID (UUID) or username
     * @type string
    */
    userKey: string;
};

export const updateUserQueryParamsByEnum = {
    username: "username"
} as const;

export type UpdateUserQueryParamsByEnumKey = (typeof updateUserQueryParamsByEnum)[keyof typeof updateUserQueryParamsByEnum];

export type UpdateUserQueryParams = {
    /**
     * @description Resolve key as \'username\' instead of UUID
     * @type string | undefined
    */
    by?: UpdateUserQueryParamsByEnumKey;
};

/**
 * @description OK
*/
export type UpdateUser200 = DtoUserResponse;

/**
 * @description Bad Request
*/
export type UpdateUser400 = ErrorsErrorResponse;

/**
 * @description User not found
*/
export type UpdateUser404 = ErrorsErrorResponse;

/**
 * @description Email already exists
*/
export type UpdateUser409 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type UpdateUser500 = ErrorsErrorResponse;

/**
 * @description User update data
*/
export type UpdateUserMutationRequest = DtoUpdateUserRequest;

export type UpdateUserMutationResponse = UpdateUser200;

export type UpdateUserMutation = {
    Response: UpdateUser200;
    Request: UpdateUserMutationRequest;
    PathParams: UpdateUserPathParams;
    QueryParams: UpdateUserQueryParams;
    Errors: UpdateUser400 | UpdateUser404 | UpdateUser409 | UpdateUser500;
};