/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPostResponse } from "./dto/PostResponse.ts";
import type { DtoUpdatePostRequest } from "./dto/UpdatePostRequest.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

export type UpdatePostPathParams = {
    /**
     * @description Post ID (UUID)
     * @type string
    */
    postID: string;
};

/**
 * @description OK
*/
export type UpdatePost200 = DtoPostResponse;

/**
 * @description Bad Request
*/
export type UpdatePost400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type UpdatePost401 = ErrorsErrorResponse;

/**
 * @description Forbidden
*/
export type UpdatePost403 = ErrorsErrorResponse;

/**
 * @description Not Found
*/
export type UpdatePost404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type UpdatePost500 = ErrorsErrorResponse;

/**
 * @description Updated fields
*/
export type UpdatePostMutationRequest = DtoUpdatePostRequest;

export type UpdatePostMutationResponse = UpdatePost200;

export type UpdatePostMutation = {
    Response: UpdatePost200;
    Request: UpdatePostMutationRequest;
    PathParams: UpdatePostPathParams;
    Errors: UpdatePost400 | UpdatePost401 | UpdatePost403 | UpdatePost404 | UpdatePost500;
};