/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateProfileRequest } from "./dto/UpdateProfileRequest.ts";
import type { DtoUserResponse } from "./dto/UserResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description OK
*/
export type UpdateMyProfile200 = DtoUserResponse;

/**
 * @description Invalid request body
*/
export type UpdateMyProfile400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type UpdateMyProfile401 = ErrorsErrorResponse;

/**
 * @description User not found
*/
export type UpdateMyProfile404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type UpdateMyProfile500 = ErrorsErrorResponse;

/**
 * @description Profile update data
*/
export type UpdateMyProfileMutationRequest = DtoUpdateProfileRequest;

export type UpdateMyProfileMutationResponse = UpdateMyProfile200;

export type UpdateMyProfileMutation = {
    Response: UpdateMyProfile200;
    Request: UpdateMyProfileMutationRequest;
    Errors: UpdateMyProfile400 | UpdateMyProfile401 | UpdateMyProfile404 | UpdateMyProfile500;
};