/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";
import type { HandlerUploadResponse } from "./handler/UploadResponse.ts";

/**
 * @description OK
*/
export type UploadMedia200 = HandlerUploadResponse;

/**
 * @description Missing file
*/
export type UploadMedia400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type UploadMedia401 = ErrorsErrorResponse;

/**
 * @description File too large
*/
export type UploadMedia413 = ErrorsErrorResponse;

/**
 * @description Unsupported media type
*/
export type UploadMedia415 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type UploadMedia500 = ErrorsErrorResponse;

export type UploadMediaMutationRequest = {
    /**
     * @description File to upload
     * @type string, binary
    */
    file: Blob;
};

export type UploadMediaMutationResponse = UploadMedia200;

export type UploadMediaMutation = {
    Response: UploadMedia200;
    Request: UploadMediaMutationRequest;
    Errors: UploadMedia400 | UploadMedia401 | UploadMedia413 | UploadMedia415 | UploadMedia500;
};