/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUserResponse } from "./dto/UserResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description OK
*/
export type UploadAvatar200 = DtoUserResponse;

/**
 * @description Invalid file
*/
export type UploadAvatar400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type UploadAvatar401 = ErrorsErrorResponse;

/**
 * @description User not found
*/
export type UploadAvatar404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type UploadAvatar500 = ErrorsErrorResponse;

export type UploadAvatarMutationRequest = {
    /**
     * @description Avatar image (JPEG or PNG, max 10MB)
     * @type string, binary
    */
    file: Blob;
};

export type UploadAvatarMutationResponse = UploadAvatar200;

export type UploadAvatarMutation = {
    Response: UploadAvatar200;
    Request: UploadAvatarMutationRequest;
    Errors: UploadAvatar400 | UploadAvatar401 | UploadAvatar404 | UploadAvatar500;
};