/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUserResponse } from "./dto/UserResponse.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";

/**
 * @description OK
*/
export type UploadCover200 = DtoUserResponse;

/**
 * @description Invalid file
*/
export type UploadCover400 = ErrorsErrorResponse;

/**
 * @description Unauthorized
*/
export type UploadCover401 = ErrorsErrorResponse;

/**
 * @description User not found
*/
export type UploadCover404 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type UploadCover500 = ErrorsErrorResponse;

export type UploadCoverMutationRequest = {
    /**
     * @description Cover image (JPEG or PNG, max 10MB)
     * @type string, binary
    */
    file: Blob;
};

export type UploadCoverMutationResponse = UploadCover200;

export type UploadCoverMutation = {
    Response: UploadCover200;
    Request: UploadCoverMutationRequest;
    Errors: UploadCover400 | UploadCover401 | UploadCover404 | UploadCover500;
};