/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoVerifyEmailRequest } from "./dto/VerifyEmailRequest.ts";
import type { ErrorsErrorResponse } from "./errors/ErrorResponse.ts";
import type { HttputilMessageResponse } from "./httputil/MessageResponse.ts";

/**
 * @description Email verified successfully
*/
export type VerifyEmail200 = HttputilMessageResponse;

/**
 * @description Invalid or expired token
*/
export type VerifyEmail400 = ErrorsErrorResponse;

/**
 * @description Internal Server Error
*/
export type VerifyEmail500 = ErrorsErrorResponse;

/**
 * @description Verification token
*/
export type VerifyEmailMutationRequest = DtoVerifyEmailRequest;

export type VerifyEmailMutationResponse = VerifyEmail200;

export type VerifyEmailMutation = {
    Response: VerifyEmail200;
    Request: VerifyEmailMutationRequest;
    Errors: VerifyEmail400 | VerifyEmail500;
};